
import {getStore} from "@netlify/blobs";
import {esc} from "./_common.mjs";
const p=(a)=>Array.isArray(a.body_paragraphs)?a.body_paragraphs:[];
function render(a){
 const url=`https://curiomondo.it/notizie/${encodeURIComponent(a.slug)}.html`;
 const img=a.image?.url||"https://curiomondo.it/curiomondo-logo-512.png";
 const sourceHtml=(a.sources||[]).map(s=>`<li><a href="${esc(s.url)}" rel="noopener noreferrer nofollow" target="_blank">${esc(s.name||s.url)}</a></li>`).join("");
 const image=a.image?`<figure class="article-image"><img src="${esc(a.image.url)}" alt="${esc(a.title)}" loading="eager" fetchpriority="high"><figcaption>Immagine: ${esc(a.image.author||"Wikimedia Commons")} · ${esc(a.image.license)} · <a href="${esc(a.image.source_page)}" target="_blank" rel="noopener">fonte/licenza</a></figcaption></figure>`:"";
 const body=p(a).map((x,i)=>`<p${i===0?' class="cm-first"':''}>${esc(x)}</p>`).join("");
 const ld=JSON.stringify({"@context":"https://schema.org","@type":"NewsArticle",headline:a.title,description:a.description,datePublished:a.published_at,dateModified:a.modified_at,author:{"@type":"Organization","name":"Redazione CurioMondo","url":"https://curiomondo.it/pagine/chi-siamo.html"},publisher:{"@type":"Organization","name":"CurioMondo","url":"https://curiomondo.it/","logo":{"@type":"ImageObject","url":"https://curiomondo.it/curiomondo-logo-512.png"}},mainEntityOfPage:{"@type":"WebPage","@id":url},image:a.image?[a.image.url]:[],articleSection:`${a.category||""} / ${a.sub_category||""}`,isAccessibleForFree:true});
 return `<!doctype html><html lang="it"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(a.title)} | CurioMondo</title><meta name="description" content="${esc(a.description||"")}"><link rel="canonical" href="${url}"><meta name="robots" content="index,follow,max-image-preview:large"><meta property="og:type" content="article"><meta property="og:site_name" content="CurioMondo"><meta property="og:title" content="${esc(a.title)}"><meta property="og:description" content="${esc(a.description||"")}"><meta property="og:url" content="${url}"><meta property="og:image" content="${esc(img)}"><meta property="article:published_time" content="${esc(a.published_at)}"><script type="application/ld+json">${ld.replace(/</g,"\\u003c")}</script><link rel="stylesheet" href="/assets/css/curiomondo-article-v1.css?v=3"><style>.cm-auto-wrap{max-width:860px;margin:auto;padding:24px 18px 70px}.cm-auto-head{margin:22px 0}.cm-auto-head h1{font:950 clamp(2rem,6vw,4rem)/1.02 system-ui;letter-spacing:-.045em;color:#0b2742}.cm-auto-meta{font:800 .78rem system-ui;color:#2563eb}.cm-auto-desc{font:650 1.08rem/1.55 system-ui;color:#58718d}.article-image{margin:22px 0;border-radius:24px;overflow:hidden;background:#eaf2ff}.article-image img{width:100%;display:block;max-height:620px;object-fit:cover}.article-image figcaption{padding:10px 14px;background:white;font:600 .72rem/1.4 system-ui;color:#52657b}.art-body p{font:500 1.04rem/1.78 system-ui;color:#17324c;margin:0 0 1.35em}.art-body .cm-first:first-letter{float:left;font:950 4.4rem/.78 Georgia;color:#2563eb;padding:.08em .08em 0 0}.cm-sources{margin-top:38px;padding:20px;border:1px solid #dbe7ee;border-radius:18px}.cm-sources a{color:#2563eb}.cm-back{display:inline-flex;text-decoration:none;font:850 .9rem system-ui;color:#2563eb;margin-top:12px}</style></head><body><main class="cm-auto-wrap"><a class="cm-back" href="/">← CurioMondo</a><header class="cm-auto-head"><div class="cm-auto-meta">${esc(a.badge||a.category||"Notizie")} · ${new Date(a.published_at).toLocaleString("it-IT",{timeZone:"Europe/Rome",dateStyle:"long",timeStyle:"short"})}</div><h1>${esc(a.title)}</h1><p class="cm-auto-desc">${esc(a.description||"")}</p></header>${image}<article class="art-body" data-length-policy="5000-7000">${body}</article><section class="cm-sources"><strong>Fonti</strong><ul>${sourceHtml}</ul></section></main></body></html>`;
}
export default async(req)=>{
 const slug=new URL(req.url).searchParams.get("slug")||"";
 const store=getStore({name:"curiomondo-articles",consistency:"strong"});
 const a=await store.get(`article:${slug}`,{type:"json",consistency:"strong"}).catch(()=>null);
 if(!a)return new Response("Not found",{status:404});
 return new Response(render(a),{headers:{"content-type":"text/html; charset=utf-8","cache-control":"public,max-age=120"}});
};
