#!/usr/bin/env python3
"""Pacchetto editoriale del 20 settembre 2026: notizie, domanda, eBook e guide."""
from __future__ import annotations
import hashlib, json, re, shutil, sys
from datetime import datetime
from html import escape
from pathlib import Path
from zoneinfo import ZoneInfo
from PIL import Image

ROOT=Path(__file__).resolve().parents[1]
sys.path[:0]=[str(ROOT),str(ROOT/'tools')]
from automation.newsroom.site import CAPTION, register_image, sync_surfaces, write_article
from daily_question_auto import (render_question_page,render_book_page,update_home,update_archive,
 update_search,update_sitemap,update_feed)

VERSION=448; DATE='2026-09-20'; STAMP='2026-09-20T00:18:00+02:00'

def write(path,text):
 p=ROOT/path; p.parent.mkdir(parents=True,exist_ok=True); p.write_text(text,encoding='utf-8')
def write_json(path,data): write(path,json.dumps(data,ensure_ascii=False,indent=2)+'\n')
def variants(src,key):
 im=Image.open(src).convert('RGB'); ratio=1.5
 if im.width/im.height>ratio:
  w=round(im.height*ratio); x=(im.width-w)//2; im=im.crop((x,0,x+w,im.height))
 else:
  h=round(im.width/ratio); y=(im.height-h)//2; im=im.crop((0,y,im.width,y+h))
 out=ROOT/'assets/images/editorial-auto'; out.mkdir(parents=True,exist_ok=True); result=[]
 for w in (480,800,1200):
  p=out/f'{key}-{w}.webp'; im.resize((w,round(w*2/3)),Image.Resampling.LANCZOS).save(p,'WEBP',quality=86,method=6)
  result.append({'w':w,'src':f'/assets/images/editorial-auto/{p.name}','sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'bytes':p.stat().st_size})
 return result

NEWS=[
 {'slug':'cina-zona-volo-vietato-pechino-in-vigore-20-settembre-2026','titolo':'Cina, entra in vigore la nuova zona aerea protetta intorno a Pechino','sommario':'La restrizione permanente copre un’area di oltre 280.000 chilometri quadrati. Restano autorizzati voli commerciali, servizi approvati ed emergenze.','categoria':'Mondo','luogo':'Pechino','formato':'standard','stato':'UFFICIALE','parole_chiave_titolo':['Cina','zona aerea protetta'],'dati_chiave':[{'icona':'◆','valore':'20 settembre','etichetta':'entrata in vigore della restrizione'},{'icona':'●','valore':'280.000 km²','etichetta':'area interessata stimata'},{'icona':'▦','valore':'24 ore','etichetta':'controllo permanente dello spazio aereo'}],
 'paragrafi':[
  'È entrata in vigore domenica 20 settembre la nuova zona permanente di restrizione aerea centrata su Pechino. L’area, larga circa 600 chilometri e stimata in oltre 280.000 chilometri quadrati, limita i voli non autorizzati sulla capitale cinese, Tianjin, gran parte dello Hebei e porzioni delle regioni circostanti.',
  'Il divieto non blocca il traffico di linea. Possono continuare a operare i voli commerciali, le attività d’affari approvate e i servizi militari, doganali, di polizia, antincendio e soccorso. Ogni movimento ammesso deve rispettare il piano autorizzato e mantenere il contatto radio continuo con il controllo del traffico aereo.',
  'Gli aeromobili autorizzati devono inoltre disporre di sistemi che consentano identificazione e tracciamento elettronico costanti. Qualunque deviazione potenziale dalla rotta richiede una nuova approvazione. Prima di entrare nell’area, i piloti devono comunicare anche lo stato di sicurezza del volo secondo le prescrizioni riportate nell’avviso aeronautico.',
  'La misura segue l’incidente del 26 giugno, quando un piccolo velivolo uscì dalla zona di volo consentita e colpì la CITIC Tower di Pechino. Il pilota morì e tredici persone a terra rimasero ferite. L’articolo non ricostruisce visivamente l’incidente: il nuovo regime riguarda la gestione futura dello spazio aereo.',
  'Per i passeggeri dei voli di linea l’effetto immediato dovrebbe essere soprattutto operativo, non un divieto di viaggio. Compagnie e controllori devono però mantenere rotte, autorizzazioni e comunicazioni più rigide. Eventuali variazioni di percorso o ritardi dipenderanno dall’applicazione concreta delle regole e dalle condizioni del traffico.',
  'La zona comprende decine di aeroporti e campi di volo in una regione abitata da circa cento milioni di persone, secondo una stima geografica riportata da Reuters. La dimensione rende il provvedimento eccezionale, ma non trasforma l’intero spazio aereo cinese in un’area chiusa: la restrizione è concentrata sulla regione della capitale.',
  'Dal 15 novembre Pechino applicherà inoltre un divieto separato su possesso e custodia dei droni nella città. Le due misure hanno scadenze e destinatari diversi: quella attiva da oggi disciplina un’area aerea molto più ampia, mentre il provvedimento sui droni riguarda direttamente proprietari e visitatori nella municipalità.'
 ],'fonti':[
  {'url':'https://notams.aim.faa.gov/notamSearch/','descrizione':'FAA NOTAM Search — avviso aeronautico pubblico richiamato per estensione, deroghe e requisiti operativi.'},
  {'url':'https://www.reuters.com/world/asia-pacific/china-creates-italy-sized-no-fly-zone-around-beijing-after-rare-crash-2026-09-17/','descrizione':'Reuters — dimensioni della zona, data di entrata in vigore e condizioni per i voli autorizzati.'},
  {'url':'https://apnews.com/article/c66efabeb1293231165cf4c75a8bedf6','descrizione':'Associated Press — contesto indipendente sulle ulteriori restrizioni ai droni a Pechino.'}
 ],'correlati':[{'url':'/notizie/cina-industria-al-5-2-ma-consumi-e-investimenti-restano-deboli-15-09-2026.html','titolo':'Cina, industria in crescita ma consumi e investimenti restano deboli'}],
 'source':'/workspace/scratch/d825bbf302f0/generated_images/exec-d233f5c8-c507-4ad5-8cf6-8edbd3a80ea3.png','alt':'Scena editoriale contestuale generata con IA: spazio aereo controllato sopra Pechino con un volo commerciale autorizzato; non è una fotografia documentaria.','prompt':'Beijing skyline and controlled airspace with authorized commercial flight and grounded light aircraft, photorealistic, no text.'},
 {'slug':'giochi-asiatici-aichi-nagoya-prime-medaglie-20-settembre-2026','titolo':'Giochi Asiatici 2026, oggi le prime medaglie ad Aichi-Nagoya','sommario':'Dopo la cerimonia inaugurale, comincia la prima giornata completa di gare. Il triathlon assegna il primo titolo della manifestazione.','categoria':'Sport internazionale','luogo':'Aichi-Nagoya','formato':'standard','stato':'CONFERMATA DA PIÙ FONTI','parole_chiave_titolo':['Giochi Asiatici 2026','prime medaglie'],'dati_chiave':[{'icona':'◆','valore':'45','etichetta':'delegazioni presenti alla manifestazione'},{'icona':'●','valore':'43','etichetta':'sport nel programma complessivo'},{'icona':'▦','valore':'20 settembre','etichetta':'prima giornata completa di gare'}],
 'paragrafi':[
  'I Giochi Asiatici di Aichi-Nagoya entrano domenica 20 settembre nella prima giornata completa di competizioni, dopo la cerimonia inaugurale di sabato. Il triathlon assegna il primo titolo della manifestazione, mentre prendono il via altri tornei del programma distribuito tra Nagoya e la prefettura di Aichi.',
  'All’evento partecipano 45 nazioni e regioni del continente asiatico. La cerimonia allo stadio di Mizuho ha aperto ufficialmente sedici giorni di gare con musica, danza e fuochi d’artificio. L’imperatore Naruhito ha dichiarato aperta la ventesima edizione, la terza organizzata dal Giappone.',
  'La prima medaglia d’oro prevista arriva dal triathlon. La disciplina combina nuoto, ciclismo e corsa senza interruzioni e mette subito alla prova trasporti, sicurezza e coordinamento dei percorsi urbani. Il programma della giornata comprende anche fasi iniziali in altre specialità, ma orari e campi vanno verificati sul calendario ufficiale.',
  'Il programma complessivo comprende 43 sport e introduce o consolida discipline nuove per la manifestazione. Esports, teqball e taekwondo virtuale affiancano atletica, nuoto, sport di squadra e arti marziali. La varietà rende i Giochi più estesi di una singola competizione mondiale e distribuisce le gare su numerose sedi.',
  'L’avvio arriva dopo segnalazioni di problemi logistici negli alloggi, nei trasporti e nelle registrazioni. Delegazioni di Corea del Sud e India hanno sollevato criticità, mentre il Consiglio Olimpico d’Asia ha definito le difficoltà gestibili. La prima giornata effettiva sarà quindi anche un test per la macchina organizzativa.',
  'Per il pubblico italiano non esiste una copertura televisiva uniforme paragonabile a Olimpiadi o grandi eventi europei. Il riferimento più affidabile per risultati, variazioni e programma resta il sito ufficiale di Aichi-Nagoya 2026; disponibilità streaming e diritti possono cambiare in base al territorio.',
  'Le gare proseguiranno fino ai primi giorni di ottobre. Il valore sportivo non dipenderà soltanto dal medagliere: per molte federazioni asiatiche l’evento è un banco di prova verso le qualificazioni internazionali, mentre le discipline emergenti cercano spazio stabile nei grandi programmi multisportivi.'
 ],'fonti':[
  {'url':'https://www.aichi-nagoya2026.org/en/','descrizione':'Aichi-Nagoya 2026 — sito ufficiale, programma, sedi e aggiornamenti della manifestazione.'},
  {'url':'https://www.olympics.com/en/news/asian-games-2026-japan-opening-ceremony-highlights-photos','descrizione':'Olympics.com — apertura ufficiale e contesto della ventesima edizione.'},
  {'url':'https://www.reuters.com/sports/asian-games-open-nagoya-after-troubled-buildup-2026-09-19/','descrizione':'Reuters — delegazioni, sport, prima medaglia prevista e criticità organizzative.'}
 ],'correlati':[{'url':'/notizie/tottenham-aston-villa-2-3-prima-vittoria-emery-19-settembre-2026.html','titolo':'Tottenham-Aston Villa 2-3, prima vittoria per Emery'}],
 'source':'/workspace/scratch/d825bbf302f0/generated_images/exec-ceba194b-dbec-470a-b809-a8fd2ec267b3.png','alt':'Scena editoriale contestuale generata con IA: triatleti asiatici in bicicletta a Nagoya durante una gara multisportiva; non è una fotografia documentaria.','prompt':'Asian triathletes cycling in Nagoya at sunrise for a multisport event, photorealistic, no text or logos.'}
]

QUESTION='È possibile amare un’altra persona se non si impara prima ad amare se stessi?'
QSLUG='e-possibile-amare-un-altra-persona-se-non-si-impara-prima-ad-amare-se-stessi'
PACKAGE={
 'excerpt':'Una riflessione sulla differenza tra autostima perfetta e responsabilità verso di sé: si può amare mentre si è fragili, ma non chiedere all’altro di sostituire interamente il nostro valore.',
 'answer_paragraphs':[
  'L’idea che si debba imparare ad amare se stessi prima di poter amare qualcun altro contiene un’intuizione utile, ma può diventare una sentenza ingiusta. Nessuno arriva a una relazione completamente risolto. Molte persone imparano a trattarsi con più rispetto proprio perché incontrano qualcuno capace di guardarle senza disprezzo e senza possederle.',
  'Amare mentre si è insicuri è possibile. L’insicurezza non cancella la capacità di ascoltare, desiderare il bene dell’altro o assumersi una responsabilità. Il problema nasce quando affidiamo alla relazione il compito esclusivo di dirci chi siamo. Ogni distanza diventa allora una prova di scarso valore e ogni conflitto sembra minacciare la nostra esistenza.',
  'Amare se stessi non significa sentirsi sempre belli, forti o soddisfatti. Significa non abbandonarsi sistematicamente per ottenere approvazione. È la possibilità di riconoscere un bisogno, proteggere un confine e chiedere aiuto senza trasformare il partner nell’unica fonte di sicurezza.',
  'Anche l’amore ricevuto può educarci. Una relazione rispettosa mostra che vicinanza e libertà possono convivere, che un errore non rende indegni e che una richiesta non è automaticamente un peso. Tuttavia l’altro può accompagnare questo apprendimento, non svolgerlo al posto nostro.',
  'La domanda decisiva non è se ci amiamo abbastanza prima di iniziare. È se, dentro il rapporto, continuiamo a esistere come persone. Possiamo dire no? Possiamo tollerare che l’altro abbia spazi propri? Possiamo riconoscere un bisogno senza usarlo come ricatto o vergognarcene?',
  'Forse non esiste un prima perfetto. Impariamo ad amare noi stessi e gli altri nello stesso tempo, attraverso tentativi, limiti e riparazioni. Ma una relazione diventa più libera quando ciascuno assume almeno una parte della responsabilità per la propria dignità. Quale gesto di cura verso di te renderebbe oggi il tuo amore meno dipendente dalla paura?'
 ],
 'book_title':'Amare senza chiedere all’altro di salvarci','book_deck':'Un eBook su autostima, dipendenza, confini e reciprocità: come costruire un amore che accompagna la crescita senza sostituirsi alla responsabilità personale.',
 'book_pages':[
  {'title':'Il mito di arrivare già completi','paragraphs':[
   'La frase «prima devi amare te stesso» sembra offrire una regola chiara, ma la vita affettiva raramente rispetta un ordine così pulito. Le persone entrano nei legami con ferite, capacità e paure ancora in movimento. Se fosse necessario raggiungere una piena serenità prima di amare, quasi nessuno sarebbe pronto. L’amore non è il premio assegnato a chi ha terminato il lavoro interiore; è uno dei luoghi in cui quel lavoro continua e diventa visibile.',
   'L’intuizione corretta riguarda la responsabilità. Una relazione non può sostenere da sola tutto il peso della nostra identità. Quando l’altro deve rassicurarci continuamente, cancellare ogni dubbio e dimostrare senza sosta che valiamo, il legame riceve un compito impossibile. Non perché il bisogno di rassicurazione sia sbagliato, ma perché nessuna presenza esterna può rendere definitiva un’immagine di noi che non riusciamo mai a custodire.',
   'Essere incompleti non significa essere incapaci di cura. Possiamo attraversare periodi di bassa autostima e, nello stesso tempo, rispettare un limite, ascoltare una fatica e mantenere una promessa. La maturità non coincide con l’assenza di fragilità. Si riconosce nella capacità di vedere la propria fragilità senza trasformarla automaticamente in un diritto sul tempo, sul corpo o sulle scelte della persona amata.',
   'Il punto di partenza realistico non è quindi «sono finalmente risolto», ma «so che cosa porto nella relazione e sono disposto a occuparmene». Questa disponibilità comprende chiedere aiuto, imparare a stare nella distanza e accettare che l’altro non possa guarire ogni ferita. L’amore può sostenere la crescita; non deve diventare la prova quotidiana che meritiamo di esistere.',
   'Aspettare di non avere più paura può diventare un modo raffinato per sottrarsi all’incontro. La preparazione utile non cancella il rischio: rende più chiari i propri limiti e la disponibilità a parlare. Una persona pronta ad amare non è invulnerabile. È qualcuno che sa riconoscere quando la propria storia sta parlando più forte del presente e prova a non farne pagare interamente il prezzo a chi ha davanti.'
  ]},
  {'title':'Che cosa significa davvero amarsi','paragraphs':[
   'Amarsi non è provare una costante ammirazione per se stessi. Ci sono giorni in cui il corpo non piace, le decisioni sembrano inadeguate e la fiducia diminuisce. La cura di sé appare soprattutto in ciò che facciamo quando non ci sentiamo degni: come ci parliamo dopo un errore, quali ambienti accettiamo, se chiediamo riposo e se distinguiamo una critica utile dall’umiliazione.',
   'Una forma concreta di amore verso di sé è la continuità. Dormire, mangiare, curarsi, amministrare il denaro e proteggere il tempo possono sembrare gesti lontani dal linguaggio romantico dell’autostima. In realtà comunicano al nostro sistema emotivo che non verremo abbandonati proprio quando siamo più confusi. Questa affidabilità interna riduce la pressione sul partner, che può offrire vicinanza senza dover sostituire ogni struttura mancante.',
   'Amarsi significa anche tollerare una verità non ideale. Possiamo essere generosi e gelosi, competenti e spaventati, desiderosi di intimità e tentati di fuggire. Negare una parte non la elimina; la rende più difficile da riconoscere quando guida un comportamento. Accogliere non vuol dire approvare tutto. Vuol dire guardare con precisione per scegliere che cosa nutrire e che cosa correggere.',
   'L’autostima più stabile non ha bisogno di proclamarsi superiore. Permette di ricevere un no senza trasformarlo sempre in disprezzo, di ascoltare un limite senza sentirsi annullati e di lasciare spazio al successo dell’altro. Non impedisce il dolore, ma evita che ogni dolore diventi una sentenza definitiva sul nostro valore. È una base sufficientemente solida, non una perfezione permanente.',
   'Anche il modo in cui scegliamo le relazioni racconta la cura verso noi stessi. Restare attratti da ciò che è familiare non significa che sia sempre sano. Possiamo scambiare l’incertezza per passione o la fatica per profondità. Imparare ad amarsi include osservare i modelli ripetuti senza condannarsi: capire quali segnali ignoriamo, quali promesse ci trattengono e quale tipo di presenza ci permette davvero di respirare.'
  ]},
  {'title':'Quando l’amore ricevuto ci insegna','paragraphs':[
   'Una relazione rispettosa può cambiare il modo in cui una persona si guarda. Essere ascoltati senza ironia, vedere riconosciuto un bisogno o ricevere una scusa sincera crea esperienze nuove. Il corpo e la mente imparano che la vicinanza non deve sempre comportare controllo. Questo apprendimento non è debolezza: gli esseri umani costruiscono identità e sicurezza anche attraverso le relazioni.',
   'Il rischio compare quando una persona diventa l’unico specchio disponibile. Se tutta la nostra dignità dipende dal suo desiderio, ogni giornata storta assume dimensioni enormi. La presenza affettiva dovrebbe aggiungere una voce favorevole, non essere l’unica autorizzata a parlare. Amicizie, competenze, valori, lavoro personale e legami familiari affidabili rendono l’identità più ampia e proteggono la coppia da una pressione eccessiva.',
   'Ricevere bene richiede capacità. Chi è abituato a diffidare può svalutare ogni gesto o pretendere prove sempre più grandi. In altri casi la gratitudine si trasforma in debito: ci si sente obbligati a restare perché qualcuno è stato gentile. L’amore ricevuto è sano quando aumenta libertà e vitalità, non quando crea una contabilità morale che rende impossibile dire no o cambiare direzione.',
   'Possiamo lasciare che una persona ci aiuti senza consegnarle la definizione completa di chi siamo. La frase utile è «con te scopro qualcosa di me», non «senza di te non sono niente». La prima riconosce il valore dell’incontro; la seconda espone entrambi alla paura. Un legame diventa più resistente quando può essere importante senza dover essere totale.',
   'La gratitudine può convivere con il discernimento. Essere stati amati in un momento difficile non obbliga a considerare giusta ogni dinamica successiva. Possiamo riconoscere ciò che abbiamo ricevuto e, nello stesso tempo, valutare se il presente conserva rispetto e reciprocità. Questo evita due estremi: cancellare il bene quando il rapporto finisce oppure usare il bene passato per giustificare indefinitamente ciò che oggi fa male.'
  ]},
  {'title':'Bisogno, dipendenza e reciprocità','paragraphs':[
   'Avere bisogno non è il contrario dell’amore maturo. La dipendenza reciproca fa parte della vita: ci affidiamo per conforto, progetti, cura e appartenenza. La questione è come il bisogno viene comunicato e distribuito. Una richiesta lascia all’altro la possibilità di rispondere; una pretesa interpreta ogni limite come tradimento e usa colpa, minaccia o silenzio per ottenere presenza.',
   'La dipendenza diventa pericolosa quando restringe progressivamente il mondo. Amicizie, interessi e autonomia economica vengono abbandonati, mentre il partner diventa l’unico interlocutore. Questo isolamento può apparire come intensità romantica, ma rende ogni crisi più minacciosa e riduce la libertà di valutare il rapporto. Conservare più legami non indebolisce la coppia: crea risorse con cui attraversare le difficoltà.',
   'La reciprocità non richiede una simmetria perfetta in ogni momento. Durante una malattia o una crisi uno dei due può sostenere più peso. Conta che lo squilibrio sia riconosciuto, discusso e non trasformato in un diritto permanente. Chi offre cura deve poter nominare la stanchezza; chi la riceve deve poter accettare aiuto senza diventare privo di voce.',
   'Un controllo semplice riguarda l’effetto del legame: la vicinanza ci rende gradualmente più capaci di vivere oppure più impauriti e dipendenti? Nessuna relazione produce soltanto crescita, ma una direzione costante verso isolamento, paura e rinuncia richiede attenzione. L’amore che sostiene non rende l’altro più piccolo per assicurarsi di essere indispensabile.',
   'Parlare apertamente di denaro, tempo e reti di sostegno riduce dipendenze invisibili. Non serve trasformare la coppia in un contratto freddo; serve sapere che cosa accadrebbe durante una difficoltà. Avere accesso alle informazioni comuni, comprendere le spese e mantenere competenze quotidiane protegge entrambi. La sicurezza pratica non sostituisce l’affetto, ma impedisce che la paura materiale diventi una catena che rende impossibile ogni scelta.'
  ]},
  {'title':'Confini che proteggono la vicinanza','paragraphs':[
   'I confini vengono spesso scambiati per freddezza. In realtà indicano il punto in cui una persona può continuare a essere presente senza accumulare risentimento. Dire di avere bisogno di riposo, proteggere una conversazione privata o rifiutare un gesto non significa amare meno. Permette alla disponibilità di restare scelta invece di diventare obbligo.',
   'Un confine sano parla di ciò che faremo noi, non pretende di controllare ogni comportamento altrui. Possiamo dire che interromperemo una conversazione se arrivano insulti; non possiamo usare la parola confine per imporre con chi l’altro debba parlare. La distinzione è importante perché il linguaggio della cura personale può essere usato impropriamente per giustificare distanza punitiva o dominio.',
   'Chi teme l’abbandono può vivere un limite come un rifiuto totale. In quel momento aiuta separare il fatto dalla storia: «ha bisogno di una sera per sé» non equivale automaticamente a «non mi ama». La rassicurazione del partner può essere preziosa, ma anche la persona spaventata può imparare a tollerare l’intervallo senza moltiplicare messaggi, controlli o accuse.',
   'I confini devono poter essere rinegoziati. Lavoro, salute e responsabilità cambiano, e ciò che era sostenibile può non esserlo più. La conversazione non serve a vincere, ma a capire quali condizioni permettono a entrambi di restare integri. Un rapporto senza limiti non è più profondo: spesso è soltanto meno capace di riconoscere il costo nascosto della propria organizzazione.',
   'Un limite diventa credibile quando è accompagnato da un comportamento coerente. Ripeterlo senza conseguenze può aumentare frustrazione e confusione. Coerenza non significa punire, ma proteggere ciò che abbiamo dichiarato importante: interrompere uno scambio offensivo, rimandare una decisione presa sotto pressione o chiedere una presenza esterna competente. Il confine non serve a costringere l’altro a cambiare; chiarisce le condizioni della nostra partecipazione.'
  ]},
  {'title':'Conflitto, vergogna e riparazione','paragraphs':[
   'Quando l’autostima è fragile, il conflitto può sembrare una minaccia all’intera identità. Una critica su un comportamento viene percepita come prova di essere sbagliati. La reazione può essere difendersi, attaccare o scomparire. Imparare a distinguere «ho fatto qualcosa che ha ferito» da «sono una persona senza valore» rende possibile assumersi responsabilità senza collassare nella vergogna.',
   'La vergogna spesso cerca sollievo immediato: negare, minimizzare o chiedere all’altro di rassicurarci proprio mentre esprime dolore. Una riparazione più matura resta sul fatto. Nomina l’azione, ascolta l’impatto e propone un cambiamento verificabile. Non richiede che la persona ferita cancelli subito la propria reazione per proteggere chi ha sbagliato.',
   'Anche chi solleva un problema ha una responsabilità nel linguaggio. Descrivere un episodio e formulare una richiesta è diverso dal definire l’intera persona. Generalizzazioni e disprezzo rendono difficile ogni cambiamento. Questo non significa addolcire violenza o controllo: nelle situazioni abusive la priorità è la sicurezza e può essere necessario cercare sostegno esterno, non migliorare la discussione.',
   'Riparare insieme non sostituisce la cura individuale. Se una ferita precedente viene riattivata continuamente, un partner può offrire pazienza ma non diventare terapeuta, giudice e garante permanente. Cercare uno spazio competente può essere un gesto d’amore verso se stessi e verso la relazione, perché distribuisce il peso e restituisce al legame la possibilità di non esistere soltanto intorno al problema.',
   'La riparazione si misura nel tempo più che nell’intensità delle parole. Una promessa pronunciata dopo una lite può essere sincera e tuttavia insufficiente. Servono gesti ripetuti, accordi osservabili e la possibilità di verificare se il clima cambia davvero. Chi è stato ferito non deve sorvegliare per sempre; chi ha ferito non può chiedere fiducia immediata come prova d’amore. La fiducia ricresce quando realtà e parole tornano gradualmente a coincidere.'
  ]},
  {'title':'Una pratica quotidiana di autonomia','paragraphs':[
   'L’autonomia affettiva si costruisce con gesti piccoli. Mantenere un impegno personale, coltivare un’amicizia, amministrare una parte delle proprie risorse e dedicare tempo a un interesse ricordano che l’identità ha più stanze. Non sono preparativi per andarsene, ma condizioni per restare senza trasformare il rapporto nell’unico luogo da cui ricavare senso.',
   'Può essere utile riconoscere quali bisogni stiamo affidando sempre alla stessa persona. Ascolto, divertimento, validazione, consiglio pratico e conforto non devono necessariamente provenire tutti dal partner. Una rete differenziata rende le richieste più sostenibili e permette alla coppia di scegliere la vicinanza, invece di viverla come un servizio continuo che non può mai fermarsi.',
   'Una pratica semplice consiste nel chiedersi che cosa possiamo fare direttamente e che cosa richiede davvero l’altro. Possiamo regolare il sonno, preparare una conversazione, prendere un appuntamento o cercare informazioni. Possiamo poi chiedere presenza, collaborazione o affetto in modo più preciso. L’iniziativa personale non elimina la relazione; rende più chiaro il contributo che desideriamo ricevere.',
   'Autonomia non significa affrontare tutto da soli. Significa poter chiedere aiuto senza sentirsi inesistenti se la risposta non è immediata. La sicurezza cresce quando sappiamo di avere alternative, competenze e persone diverse a cui rivolgerci. In questo modo il sì del partner conserva valore, perché non è ottenuto sotto la pressione di essere l’unica barriera contro il crollo.',
   'Per allenarla possiamo scegliere un impegno settimanale che appartenga soltanto a noi: un’attività, un incontro, una decisione pratica. Non è necessario nasconderlo o usarlo per creare distanza. Lo scopo è ricordare che la relazione contiene due vite capaci di iniziativa. Tornare al legame dopo aver coltivato una parte personale porta spesso più presenza, perché non chiediamo all’altro di produrre da solo tutta la curiosità e l’energia disponibili.'
  ]},
  {'title':'Amarsi mentre si impara','paragraphs':[
   'Non dobbiamo aspettare una versione perfetta di noi per entrare in relazione. Possiamo però osservare se il legame sostiene la responsabilità o premia la rinuncia a noi stessi. Un amore buono non richiede di essere sempre forti. Richiede che la fragilità possa essere nominata senza diventare un’arma, una scusa permanente o un obbligo imposto all’altro.',
   'Imparare ad amarsi dentro una relazione significa continuare a chiedersi dove finiamo noi e dove comincia l’altro. Possiamo ricevere una critica senza consegnarle tutto il nostro valore, accogliere un complimento senza dipenderne e vivere una distanza senza riempirla subito di significati catastrofici. Sono capacità imperfette, allenate più volte nella vita quotidiana.',
   'Anche il partner deve restare una persona, non lo strumento della nostra guarigione. Può stancarsi, cambiare, sbagliare e avere bisogni che non ci riguardano. Riconoscere questa alterità è una forma profonda di amore: impedisce di ridurlo al ruolo di salvatore. Permette inoltre di scegliere la relazione per ciò che è, non soltanto per il sollievo che produce.',
   'Forse la risposta alla domanda iniziale è che i due apprendimenti procedono insieme. Amando possiamo scoprire dignità e fiducia; prendendoci cura di noi rendiamo l’amore meno impaurito e più libero. Non serve arrivare completi. Serve non smettere di diventare responsabili della propria vita, così che il legame possa essere incontro e non sostituzione.',
   'Una domanda finale può accompagnare questo lavoro: ciò che chiediamo alla persona amata nasce dal desiderio di condivisione o dal terrore di non valere senza la sua risposta? Le due motivazioni possono convivere. Accorgersene non rende falso il sentimento; ci offre una scelta. Possiamo nominare la paura, cercare sostegno e formulare una richiesta più libera. In quel passaggio l’amore non diminuisce: smette soltanto di doverci salvare da soli.'
  ]}
 ]
}

GUIDES=[
 ('come-usare-vpn-gratis','Come usare una VPN gratis senza compromettere privacy e sicurezza','VPN gratuite, limiti reali, configurazione integrata e criteri per evitare servizi che monetizzano dati o espongono il traffico.',[
  ('Prima di scegliere una VPN','Una VPN crea un collegamento cifrato tra il dispositivo e un server remoto. È utile sulle reti non affidabili, per raggiungere risorse aziendali o per presentarsi online con l’indirizzo del server. Non rende anonimi, non elimina cookie e account e non protegge da phishing, malware o password deboli. Prima di installare qualcosa, definisci il problema: sicurezza su Wi‑Fi pubblico, accesso al lavoro o semplice prova del servizio.','I servizi gratuiti sostenibili hanno limiti dichiarati: quantità di dati, pochi server, velocità ridotta o un solo dispositivo. Diffida di chi promette tutto senza spiegare come si finanzia. Controlla titolare, giurisdizione, politica dei log, audit indipendenti, app ufficiali e procedura di cancellazione. Una VPN che inserisce pubblicità, vende dati o installa profili opachi può aumentare il rischio invece di ridurlo.'),
  ('Installazione e uso corretto','Scarica l’app soltanto dallo store ufficiale o dal sito del fornitore verificato. Controlla il nome dello sviluppatore, crea un account con una password unica e abilita l’autenticazione a due fattori se disponibile. Su Windows, macOS, Android e iPhone il sistema chiederà di autorizzare una configurazione VPN: accetta solo se l’app e il fornitore sono quelli scelti. Collega il server più vicino per ridurre latenza e consumo energetico.','Attiva il blocco della connessione quando la VPN cade, se il servizio offre un kill switch affidabile. Evita di cambiare paese senza motivo: può far scattare controlli sugli account e rendere meno pertinenti risultati e servizi locali. Le piattaforme possono limitare accessi da VPN in base ai propri termini. Non usare lo strumento per aggirare obblighi legali, controlli aziendali o restrizioni che sei tenuto a rispettare.'),
  ('Verifiche e alternative','Dopo il collegamento verifica che l’indirizzo IP pubblico sia cambiato e che DNS e traffico IPv6 non escano dal tunnel. Usa pagine di test note, ma non concedere permessi aggiuntivi. Prova una videochiamata e i servizi essenziali; se la connessione rallenta troppo, cambia server vicino o disattiva funzioni non necessarie. Aggiorna sempre app e sistema operativo, perché la cifratura non corregge vulnerabilità del dispositivo.','Per un uso occasionale può bastare la protezione già offerta dai siti HTTPS e dalla rete mobile personale. Per il lavoro usa esclusivamente la VPN indicata dall’organizzazione. Se servono molti dati, più dispositivi o prestazioni costanti, un piano gratuito può non essere adatto: meglio un servizio a pagamento trasparente che una promessa illimitata finanziata in modo poco chiaro.'),
  ('Fonti ufficiali','Consulta il supporto del sistema operativo per aggiungere o rimuovere configurazioni VPN e il centro sicurezza del fornitore scelto. Riferimenti utili: Apple Support sulle impostazioni VPN, Microsoft Support sulle connessioni VPN, Google Android Enterprise e le indicazioni dell’ENISA per la sicurezza delle reti. Verifica sempre la pagina aggiornata, perché menu e funzioni cambiano con le versioni.')]),
 ('come-cambiare-dns','Come cambiare DNS su Windows, Mac, Android, iPhone e router','Una guida pratica per scegliere un resolver affidabile, modificare le impostazioni e tornare indietro se la rete smette di funzionare.',[
  ('Che cosa cambia davvero','Il DNS traduce nomi come curiomondo.it negli indirizzi necessari alla connessione. Cambiare resolver può migliorare affidabilità, applicare filtri familiari o usare protocolli cifrati, ma non aumenta automaticamente la velocità di Internet e non sostituisce una VPN. Il gestore DNS vede le richieste che riceve, quindi la scelta riguarda anche fiducia e privacy. Preferisci operatori con policy chiare, indirizzi pubblicati e assistenza verificabile.','Annota la configurazione attuale prima di modificarla. Molte reti ricevono i DNS automaticamente dal router o dall’operatore: per tornare indietro basta selezionare di nuovo l’opzione automatica. Se il dispositivo appartiene al lavoro o alla scuola, non cambiare parametri gestiti. DNS interni possono essere necessari per stampanti, portali e risorse aziendali.'),
  ('Windows e Mac','In Windows 11 apri Impostazioni, Rete e Internet, scegli Wi‑Fi o Ethernet, poi la connessione e l’assegnazione server DNS. Seleziona Modifica, Manuale, abilita IPv4 o IPv6 e inserisci gli indirizzi del servizio scelto. Dove disponibile, attiva DNS su HTTPS usando il modello corretto. Salva, chiudi e riapri il browser. Se la rete non funziona, torna su Automatico e riavvia la connessione.','Su macOS apri Impostazioni di Sistema, Rete, seleziona il servizio, Dettagli e DNS. Aggiungi gli indirizzi con il pulsante più e rimuovi quelli personalizzati con meno. Conferma con OK. Le voci possono variare tra versioni: usa la ricerca interna delle impostazioni. Un profilo aziendale o un’app di sicurezza può impedire la modifica; non rimuoverlo senza autorizzazione.'),
  ('Android, iPhone e router','Su Android il DNS privato protegge le richieste con DNS over TLS: cerca DNS privato nelle impostazioni di rete e inserisci il nome host indicato dal provider, non un indirizzo IP generico. La modalità agisce sul dispositivo, ma alcune reti con portale di accesso possono richiedere di disattivarla temporaneamente. Le singole reti Wi‑Fi consentono anche parametri statici, che vanno usati con cautela perché includono gateway e indirizzo del telefono.','iPhone e iPad permettono di configurare manualmente i DNS per ogni rete Wi‑Fi da Impostazioni, Wi‑Fi, pulsante informazioni, Configura DNS. Per proteggere le richieste su tutte le reti servono profili o app attendibili. Sul router la modifica raggiunge tutti i dispositivi che ricevono la configurazione automaticamente: entra solo dall’indirizzo locale, salva i valori precedenti e non esporre l’amministrazione a Internet.'),
  ('Test e risoluzione problemi','Dopo la modifica visita alcuni siti noti, prova un dominio nuovo e controlla il resolver con lo strumento ufficiale del servizio. Se una sola pagina non si apre, svuota la cache DNS o riavvia browser e dispositivo. Se nessun sito funziona, ripristina l’impostazione automatica. Un DNS con filtro può bloccare categorie intere: verifica il pannello prima di attribuire il problema alla linea.','Fonti utili: Microsoft Support, guida Apple alle impostazioni DNS, documentazione Android sul DNS privato e istruzioni del produttore del router. Usa gli indirizzi pubblicati direttamente dall’operatore scelto; copiarli da forum o video espone a errori e possibili dirottamenti. Non inserire server ricevuti tramite messaggi o finestre che promettono sblocchi miracolosi.')])
]

def guide_html(slug,title,deck,sections):
 body=''.join(f'<h2>{escape(h)}</h2>'+''.join(f'<p>{escape(p)}</p>' for p in ps) for h,*ps in sections)
 return f'''<!doctype html><html lang="it"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{escape(title)} | Biblioteca CurioMondo</title><meta name="description" content="{escape(deck,quote=True)}"><meta name="robots" content="index,follow"><link rel="canonical" href="https://curiomondo.it/biblioteca/tecnologia-ai/smartphone-computer/{slug}/"><link rel="stylesheet" href="/assets/css/biblioteca-v1.css?v=448"><style>body{{margin:0;background:#f7fbff;color:#16324a;font-family:system-ui,-apple-system,sans-serif}}article{{max-width:920px;background:#fff;margin:24px auto 60px;padding:38px 44px;border:1px solid #d6e7f7;border-radius:26px}}h1{{font-size:clamp(2rem,5vw,3.5rem);color:#0a2b49}}h2{{color:#0d5fcb;margin-top:34px}}p{{font:1.07rem/1.74 Georgia,serif}}@media(max-width:650px){{article{{margin:12px;padding:24px 20px}}}}</style><link rel="stylesheet" href="/assets/css/global-header-v275.css"><script defer src="/assets/js/global-header-v275.js"></script></head><body><header class="cm-global-header" data-cm-global-header="v275"><nav class="cm-global-header__inner"><a class="cm-global-header__back" href="/" aria-label="Torna alla home"><span class="cm-global-header__back-icon" aria-hidden="true"><svg viewBox="0 0 24 24"><path d="M19 12H5"></path><path d="m11 18-6-6 6-6"></path></svg></span></a><a class="cm-global-header__brand" href="/">Curio<span>Mondo</span></a></nav></header><main class="cb-shell"><article><div class="cb-breadcrumb"><a href="/biblioteca/">Biblioteca</a> / <a href="/biblioteca/tecnologia-ai/smartphone-computer/">Smartphone &amp; Computer</a></div><p class="cb-kicker">Guida pratica · 20 settembre 2026</p><h1>{escape(title)}</h1><p><strong>{escape(deck)}</strong></p>{body}</article></main><footer class="cb-footer"><div class="cb-shell">© 2026 CurioMondo</div></footer></body></html>'''

def main():
 published=[]
 for i,a in enumerate(NEWS):
  words=sum(len(re.findall(r"\b[0-9A-Za-zÀ-ÖØ-öø-ÿ'’]+\b",p)) for p in a['paragrafi'])
  if not 300<=words<=600: raise SystemExit(f'word gate {a["slug"]}: {words}')
  existing=ROOT/'notizie'/f'{a["slug"]}.html'
  if existing.exists():
   a['published']=STAMP; published.append(a['slug']); continue
  src=Path(a['source']); local=ROOT/'generated_images'/f'v448-{i}.png'; shutil.copy2(src,local)
  key=f'{a["slug"]}-v{VERSION}'; image={'key':key,'aiGenerated':True,'documentaryPhoto':False,'generator':'ChatGPT/OpenAI image generation','variants':variants(local,key),'alt':a['alt'],'disclosure':CAPTION,'sensitiveContext':False,'reenactedEvent':False,'syntheticLikeness':None,'prompt':a['prompt']}
  slug=write_article(a,image,VERSION); p=ROOT/'notizie'/f'{slug}.html'; html=p.read_text(); html=re.sub(r'"datePublished":"[^"]+"',f'"datePublished":"{STAMP}"',html); html=re.sub(r'"dateModified":"[^"]+"',f'"dateModified":"{STAMP}"',html); p.write_text(html)
  a['published']=STAMP; register_image(image,slug,VERSION); published.append(slug)
  write_json(Path('contenuti/notizie')/f'{slug}.json',{'slug':slug,'title':a['titolo'],'excerpt':a['sommario'],'category':a['categoria'],'published_at':STAMP,'updated_at':STAMP,'development_at':DATE,'status':a['stato'],'public_url':f'https://curiomondo.it/notizie/{slug}.html','publication_state':'pending_deploy','body':a['paragrafi'],'sources':a['fonti'],'image':image})
 sync_surfaces(NEWS,'',VERSION)

 dt=datetime(2026,9,20,0,20,tzinfo=ZoneInfo('Europe/Rome')); qurl=f'/domanda-del-giorno/{QSLUG}/'; burl=f'/biblioteca/vita-relazioni/domande-per-conoscersi/{QSLUG}/'
 chars=sum(len(p) for pg in PACKAGE['book_pages'] for p in pg['paragraphs'])
 if not 15000<=chars<=30000: raise SystemExit(f'ebook gate {chars}')
 write(Path('domanda-del-giorno')/QSLUG/'index.html',render_question_page(QUESTION,PACKAGE,QSLUG,DATE,'20 settembre 2026',burl))
 write(Path('biblioteca/vita-relazioni/domande-per-conoscersi')/QSLUG/'index.html',render_book_page(qurl,burl,PACKAGE))
 update_home(QSLUG,dt,'20 settembre 2026'); update_archive(QUESTION,PACKAGE,QSLUG,'20 settembre 2026'); update_search(QUESTION,PACKAGE,qurl,burl); update_sitemap(DATE,qurl,burl); update_feed(dt,QUESTION,PACKAGE,qurl)

 search=json.loads((ROOT/'assets/data/search-index-v210.json').read_text()); cat=ROOT/'biblioteca/tecnologia-ai/smartphone-computer/index.html'; ch=cat.read_text()
 for slug,title,deck,sections in reversed(GUIDES):
  content=guide_html(slug,title,deck,sections); plain=re.sub('<[^>]+>',' ',content)
  if not 3000<=len(plain)<=15000: raise SystemExit(f'guide gate {slug} {len(plain)}')
  write(Path('biblioteca/tecnologia-ai/smartphone-computer')/slug/'index.html',content)
  card=f'<a class="cb-subcard" href="/biblioteca/tecnologia-ai/smartphone-computer/{slug}/"><span class="cb-kicker">Nuova guida · 20 settembre 2026</span><h2>{escape(title)}</h2><p>{escape(deck)}</p><b>Leggi la guida →</b></a>'
  ch=ch.replace('<section class="cb-manual-grid">','<section class="cb-manual-grid">'+card,1)
  search['items'].insert(0,{'title':title,'excerpt':deck,'url':f'/biblioteca/tecnologia-ai/smartphone-computer/{slug}/','section':'Biblioteca / Tecnologia e informatica'})
  xml=(ROOT/'sitemap.xml').read_text(); block=f'  <url><loc>https://curiomondo.it/biblioteca/tecnologia-ai/smartphone-computer/{slug}/</loc><lastmod>{DATE}</lastmod><changefreq>monthly</changefreq><priority>0.6</priority></url>\n'; (ROOT/'sitemap.xml').write_text(xml.replace('</urlset>',block+'</urlset>'))
 cat.write_text(ch); search['version']=VERSION; write_json(Path('assets/data/search-index-v210.json'),search)

 queue=json.loads((ROOT/'automation/state/guide-topics.json').read_text()); c=queue['categories'][0]
 for topic in ('Come usare VPN gratis','Come cambiare DNS'):
  if topic in c['remaining_topics']: c['remaining_topics'].remove(topic)
  if topic not in c['published_from_queue']: c['published_from_queue'].append(topic)
 write_json(Path('automation/state/guide-topics.json'),queue)
 manifest=json.loads((ROOT/'curiomondo-site-manifest.json').read_text()); manifest['site'].update({'current_site_version':VERSION,'site_version':VERSION}); manifest.update({'site_version':VERSION,'version':f'v{VERSION}','release_version':f'v{VERSION}'})
 daily=manifest['daily_state']; daily.update({'current_question_source_number':452,'last_question_date':DATE,'last_question_slug':QSLUG,'last_daily_guides':['come-usare-vpn-gratis','come-cambiare-dns'],'last_daily_package_date':DATE}); daily.pop('current_question_owner_override',None)
 if 452 not in daily['used_question_source_numbers']: daily['used_question_source_numbers'].append(452)
 manifest['last_release']={'version':VERSION,'date':DATE,'type':'daily-package-and-news','news_added':published,'news_updated':[],'change':'Notizie del 20 settembre, Domanda del giorno n. 452 e due guide Biblioteca','image_policy_applied':'new-openai-contextual-editorial-images'}; write_json(Path('curiomondo-site-manifest.json'),manifest)
 for name in ('RELEASE-STATE.json','CURIOMONDO-RELEASE-STATE.json'):
  p=ROOT/name; s=json.loads(p.read_text()); s.update({'currentVersion':VERSION,'site_version':VERSION,'version':str(VERSION),'date':DATE,'release_date':DATE,'last_daily_question_date':DATE,'last_update':'daily-package-news-v448','articleCount':int(s.get('articleCount',0))+2,'generatedEditorialImages':int(s.get('generatedEditorialImages',0))+2}); write_json(Path(name),s)
 write_json(Path('automation/logs/editoriale-20260920T002000-Europe-Rome.json'),{'run_at':STAMP,'processed':[{'title':a['titolo'],'decision':'publish'} for a in NEWS],'daily_question':{'number':452,'question':QUESTION},'guides':['Come usare VPN gratis','Come cambiare DNS']})
 print(json.dumps({'news':published,'question':452,'ebook_chars':chars},ensure_ascii=False))

if __name__=='__main__': main()
