#!/usr/bin/env python3
from pathlib import Path
import hashlib, json, runpy

ROOT=Path(__file__).resolve().parents[1]; VERSION=316
CAPTION="Illustrazione editoriale CurioMondo generata con IA per rappresentare questa notizia; non è una fotografia documentaria."

ARTICLES=[
{
"slug":"canada-nuovo-pacchetto-difesa-aerea-ucraina-settembre-2026","title":"Ucraina, il Canada prepara un nuovo pacchetto per la difesa aerea","excerpt":"Zelenskyy annuncia un'intesa con Ottawa per rafforzare la protezione dei cieli e sostenere il settore energetico. Carney conferma ulteriore assistenza a Kyiv.","published":"2026-09-10T19:00:00+02:00","category":"Mondo / Ucraina / Canada / Difesa","place":"Canada","key":"canada-ucraina-difesa-aerea-ai-v316","alt":"Volodymyr Zelenskyy e Mark Carney durante un incontro istituzionale in Canada, illustrazione editoriale fotorealistica generata con IA","public_figure":"Volodymyr Zelenskyy e Mark Carney","sensitive":False,
"points":[("nuovo pacchetto","per la difesa aerea ucraina"),("energia","il secondo settore sostenuto"),("25,5 mld C$","l'assistenza canadese complessiva indicata da Reuters")],
"body":[
"Il Canada ha concordato un nuovo e significativo pacchetto di sostegno alla difesa aerea dell'Ucraina, insieme ad aiuti per il settore energetico. Lo ha annunciato il presidente ucraino Volodymyr Zelenskyy durante la visita in Canada del 10 settembre; il primo ministro Mark Carney ha confermato che Ottawa fornirà ulteriore assistenza a Kyiv. Al momento dell'annuncio non sono stati diffusi composizione, valore, calendario di consegna o tipologia dei sistemi: il dato certo è l'impegno politico, non ancora l'elenco delle forniture.",
"La distinzione è importante perché l'espressione «difesa aerea» comprende capacità diverse. Può indicare intercettori e lanciatori, radar, munizioni, componenti di ricambio, addestramento o contributi finanziari a programmi coordinati con gli alleati. Senza una scheda ufficiale non è corretto attribuire all'accordo uno specifico sistema d'arma. Reuters riferisce che Zelenskyy lo ha definito importante, mentre Carney ha ribadito l'intenzione canadese di aumentare il sostegno.",
"Per l'Ucraina la disponibilità di munizioni e sensori è legata alla continuità della protezione di città, reti elettriche e infrastrutture produttive. Un sistema può essere efficace soltanto se inserito in una rete composta da allerta, comando, radar e intercettori con portate differenti. Per questo il valore operativo non coincide con il numero di singoli mezzi annunciati: contano compatibilità, tempi di consegna, scorte e capacità di manutenzione.",
"Il sostegno energetico risponde a un'esigenza parallela. Danni a centrali, sottostazioni e reti di distribuzione possono produrre interruzioni anche quando l'impianto colpito non è definitivamente distrutto. Materiali per le riparazioni, generatori, trasformatori e protezioni fisiche aiutano a ridurre i tempi di ripristino. Anche in questo caso, però, l'annuncio non specifica ancora quali strumenti Ottawa finanzierà o consegnerà.",
"Secondo Reuters, il totale dell'assistenza canadese all'Ucraina dall'inizio dell'invasione su vasta scala ammonta a circa 25,5 miliardi di dollari canadesi, di cui 8,5 miliardi in aiuti militari. Queste cifre descrivono il quadro cumulativo e non il valore del nuovo pacchetto. Sommarle nuovamente all'annuncio del 10 settembre produrrebbe quindi un doppio conteggio.",
"L'incontro ha anche una dimensione diplomatica. Canada e Ucraina discutono sostegno militare, cooperazione con NATO e partner europei e prospettive di ricostruzione. La visita rafforza il segnale di continuità politica, ma non consente di stabilire quando le nuove risorse arriveranno sul campo. Tra decisione, contratto, produzione, trasferimento e piena operatività possono intercorrere tempi diversi.",
"Associated Press colloca la visita nel più ampio coordinamento tra gli alleati di Kyiv. La conferma da una seconda fonte consolida il contenuto generale dell'annuncio, ma non aggiunge dettagli tecnici che le autorità non hanno pubblicato. CurioMondo considera quindi confermati l'accordo sul pacchetto e il sostegno energetico, lasciando aperti quantità, costo e calendario.",
"I prossimi elementi verificabili saranno un comunicato del governo canadese, eventuali stanziamenti di bilancio e indicazioni del ministero della Difesa sulle consegne. Fino ad allora il nuovo pacchetto resta un impegno annunciato al massimo livello. Un aggiornamento sostanziale richiederà dati operativi o finanziari, non la semplice ripetizione delle dichiarazioni politiche."],
"sources":[["https://www.president.gov.ua/en/news","Presidenza dell'Ucraina — 10 settembre 2026 — dichiarazioni di Volodymyr Zelenskyy"],["https://www.pm.gc.ca/en/news","Primo ministro del Canada — 10 settembre 2026 — visita e ulteriore assistenza all'Ucraina"],["https://www.reuters.com/world/americas/canada-provide-ukraine-significant-air-defence-package-zelenskiy-says-2026-09-10/","Reuters — 10 settembre 2026 — annuncio, sostegno energetico e quadro degli aiuti"],["https://apnews.com/","Associated Press — 10 settembre 2026 — conferma indipendente della visita e del sostegno canadese"]]
},
{
"slug":"attacchi-russi-kyiv-dnipro-ukrnafta-bunge-settembre-2026","title":"Ucraina, attacchi colpiscono Kyiv e uno stabilimento agroindustriale a Dnipro","excerpt":"Un drone centra una stazione Ukrnafta a Kyiv, con quattro feriti. A Dnipro due morti e cinque feriti nell'impianto per l'olio di girasole del gruppo Bunge.","published":"2026-09-10T18:40:00+02:00","category":"Mondo / Ucraina / Cronaca","place":"Kyiv e Dnipro","key":"attacchi-kyiv-dnipro-ai-v316","alt":"Stabilimento agroindustriale danneggiato e isolato dopo un attacco in Ucraina, illustrazione editoriale fotorealistica generata con IA","sensitive":True,
"points":[("4 feriti","alla stazione di servizio di Kyiv"),("2 morti","nello stabilimento di Dnipro"),("5 feriti","segnalati nell'impianto Bunge")],
"body":[
"Nuovi attacchi russi hanno colpito infrastrutture civili ed economiche in Ucraina il 10 settembre. A Kyiv un drone ha centrato una stazione di servizio gestita da Ukrnafta, provocando quattro feriti secondo le autorità e l'azienda. A Dnipro è stato colpito uno stabilimento per la produzione di olio di girasole del gruppo Bunge: le informazioni disponibili indicano due morti e cinque feriti. Reuters ha raccolto e confrontato le comunicazioni delle autorità ucraine e delle imprese coinvolte.",
"Le due località e i due bilanci vanno tenuti distinti. I quattro feriti riguardano la stazione di servizio nella capitale; i due morti e cinque feriti riguardano il sito industriale di Dnipro. Unire le cifre senza indicare la provenienza renderebbe più difficile seguire eventuali revisioni. Nei primi aggiornamenti dopo un attacco, infatti, il numero delle persone coinvolte può cambiare con le verifiche dei soccorritori.",
"Ukrnafta ha identificato il sito di Kyiv come una propria stazione e ha riferito che l'impatto è stato causato da un drone a reazione. Questa indicazione è attribuita all'azienda e alle autorità ucraine; non equivale a una verifica tecnica indipendente sul modello dell'arma. Gli elementi confermati sono il danneggiamento della struttura e le persone ferite, mentre restano da chiarire l'esatta traiettoria e l'obiettivo operativo dell'attacco.",
"A Dnipro il bersaglio colpito appartiene al comparto agroalimentare. Lo stabilimento Bunge lavora semi oleosi e produce olio di girasole, una filiera rilevante sia per il mercato interno sia per le esportazioni ucraine. Reuters indica una capacità di lavorazione di circa 1.600 tonnellate di semi al giorno. La capacità nominale aiuta a descrivere la scala del sito, ma non permette di stimare automaticamente produzione perduta o durata della fermata.",
"Gli impianti agroindustriali collegano agricoltori, stoccaggio, trasformazione, energia e trasporti. Un'interruzione può quindi propagarsi lungo la catena anche senza distruggere l'intera struttura: contano danni alle linee, disponibilità elettrica, sicurezza dell'area e accesso logistico. Per misurare l'effetto economico serviranno una valutazione aziendale e dati sull'effettiva ripresa delle attività.",
"Sul piano umano, il bilancio di Dnipro è il dato più grave. CurioMondo non pubblica immagini traumatiche né ricostruzioni visive dell'impatto: l'illustrazione associata mostra soltanto il contesto industriale danneggiato. I nomi delle vittime non vengono riportati in assenza di comunicazioni ufficiali e della certezza che le famiglie siano state informate.",
"Mosca sostiene di non colpire deliberatamente obiettivi civili; le autorità ucraine attribuiscono alla Russia gli attacchi. Questa posizione russa viene riportata come dichiarazione della parte in conflitto e non annulla i danni osservati alle strutture civili. Stabilire intenzione, catena di comando e conformità al diritto internazionale richiede prove ulteriori rispetto al singolo resoconto immediato.",
"Gli aggiornamenti da seguire riguardano condizioni dei feriti, identificazione delle vittime, valutazione dei danni e riapertura dei siti. Un eventuale cambiamento del bilancio sarà indicato con orario e fonte. Allo stato attuale la notizia è confermata da più comunicazioni concordanti e dal riscontro di Reuters, mentre i dettagli tecnici dell'attacco restano attribuiti."],
"sources":[["https://www.ukrnafta.com/en/news","Ukrnafta — 10 settembre 2026 — stazione colpita e persone ferite"],["https://www.bunge.com/News","Bunge — 10 settembre 2026 — informazioni sullo stabilimento di Dnipro"],["https://www.reuters.com/world/europe/russian-attacks-hit-kyiv-gas-station-bunge-plant-dnipro-2026-09-10/","Reuters — 10 settembre 2026 — bilanci, aziende coinvolte e capacità dell'impianto"],["https://kyivcity.gov.ua/en/","Amministrazione della città di Kyiv — aggiornamenti ufficiali sull'attacco"]]
},
{
"slug":"incendio-gombio-reggio-emilia-130-ettari-bilancio-2026","title":"Incendio di Gombio, il bilancio: oltre 130 ettari bruciati","excerpt":"La Regione Emilia-Romagna ricostruisce cinque giorni di operazioni nel Reggiano. Mobilitati Vigili del Fuoco, Protezione civile, volontari, Canadair ed elicotteri.","published":"2026-09-10T18:20:00+02:00","category":"Italia / Emilia-Romagna / Ambiente / Cronaca","place":"Gombio","key":"incendio-gombio-ai-v316","alt":"Ampia area di bosco bruciato sull'Appennino reggiano dopo l'incendio di Gombio, illustrazione editoriale fotorealistica generata con IA","sensitive":True,
"points":[("130+ ettari","la superficie interessata"),("5 giorni","la durata delle operazioni"),("terra e aria","il doppio dispositivo di intervento")],
"body":[
"Oltre 130 ettari di bosco sono stati interessati dall'incendio di Gombio, nel Reggiano, secondo il bilancio diffuso il 10 settembre dalla Regione Emilia-Romagna. Le operazioni sono durate cinque giorni e hanno coinvolto Vigili del Fuoco, Protezione civile, forze dell'ordine e volontari, con il supporto di Canadair ed elicotteri. Il dato regionale aggiorna la dimensione complessiva dell'area percorsa dalle fiamme e ricostruisce lo sforzo necessario per contenere il fronte.",
"L'incendio era iniziato il 6 agosto nell'area appenninica e aveva minacciato abitazioni e attività. Alcune famiglie e un agriturismo erano stati evacuati in via precauzionale. L'assenza di un bilancio di vittime non riduce la gravità dell'evento: in un territorio boschivo, vento, pendenza e accessi limitati possono far cambiare rapidamente direzione al fuoco e rendere indispensabile allontanare le persone prima dell'arrivo delle fiamme.",
"La superficie di 130 ettari misura l'area attraversata dall'incendio, non implica che ogni metro quadrato abbia subito la stessa intensità. All'interno del perimetro possono restare zone meno danneggiate, alberi sopravvissuti e porzioni bruciate in profondità. Le valutazioni forestali successive distinguono severità, stabilità dei versanti, capacità di ricrescita e necessità di interventi.",
"Cinque giorni di operazioni comprendono fasi diverse. All'attacco iniziale per fermare il fronte seguono bonifica, controllo dei punti caldi e sorveglianza contro le riprese. Tronchi, ceppaie e materiale organico possono continuare a covare sotto la superficie anche quando non sono visibili fiamme. Per questo la conclusione dell'incendio attivo non coincide sempre con il ritiro immediato di tutte le squadre.",
"Il dispositivo aereo ha affiancato il lavoro a terra. Canadair ed elicotteri possono scaricare acqua o ritardante sui punti difficili da raggiungere, ma hanno bisogno di coordinamento con le squadre e operano entro limiti di visibilità, vento e sicurezza. Non sostituiscono la bonifica manuale, necessaria per verificare il perimetro e spegnere i focolai nascosti.",
"Il presidente regionale Michele de Pascale ha incontrato a Vedriano di Canossa le persone impegnate nell'emergenza. Il riconoscimento pubblico rende visibile una rete composta da professionisti e volontari con compiti differenti: spegnimento, evacuazioni, viabilità, logistica, comunicazioni e assistenza alla popolazione. La cooperazione tra strutture è uno degli elementi decisivi negli incendi estesi.",
"Dopo il fuoco, la priorità si sposta sul territorio. Le piogge possono trascinare cenere e suolo dai versanti privi di copertura; sentieri e alberi instabili possono restare pericolosi. Eventuali chiusure o interventi di ripristino devono essere definiti dagli enti competenti dopo sopralluoghi. Piantare subito nuovi alberi non è sempre la risposta corretta: in alcuni ambienti la rinnovazione naturale è più efficace, mentre altrove servono opere contro erosione e dissesto.",
"La Regione non attribuisce nel bilancio una causa definitiva dell'incendio. È quindi scorretto trasformare ipotesi sull'innesco in conclusioni. Le informazioni ufficiali consolidano estensione, durata e forze mobilitate; le responsabilità richiedono invece accertamenti specifici. Il prossimo dato utile sarà il piano di messa in sicurezza e recupero dell'area, insieme all'eventuale esito delle indagini."],
"sources":[["https://notizie.regione.emilia-romagna.it/comunicati/2026/settembre/incendio-di-gombio-nel-reggiano-oltre-130-ettari-di-bosco-bruciati","Regione Emilia-Romagna — 10 settembre 2026 — bilancio ufficiale, durata e mezzi impiegati"],["https://www.vigilfuoco.it/","Corpo nazionale dei Vigili del Fuoco — attività istituzionale antincendio"],["https://www.agenziaprotezionecivile.emilia-romagna.it/","Protezione civile Emilia-Romagna — sistema regionale e aggiornamenti operativi"],["https://www.reggionline.com/","Reggionline — 10 settembre 2026 — riscontro locale sul bilancio dell'incendio"]]
},
{
"slug":"pensioni-libretto-previdenziale-dalla-nascita-calderone-2026","title":"Pensioni, il Governo valuta un «libretto previdenziale» dalla nascita","excerpt":"La ministra Calderone presenta l'ipotesi come opzione allo studio e rilancia previdenza complementare e modello multipilastro. Non è ancora una misura approvata.","published":"2026-09-10T18:00:00+02:00","category":"Italia / Economia / Pensioni","place":"Roma","key":"libretto-previdenziale-ai-v316","alt":"Libretto simbolico senza scritte accanto a un giocattolo per neonati e monete euro, illustrazione editoriale fotorealistica generata con IA","sensitive":False,
"points":[("dalla nascita","l'ipotesi indicata dalla ministra"),("allo studio","non ancora approvata"),("più pilastri","il modello previdenziale richiamato")],
"body":[
"Il Governo valuta l'ipotesi di un «libretto previdenziale» aperto fin dalla nascita. Lo ha dichiarato il 10 settembre la ministra del Lavoro Marina Calderone, intervenendo nel programma Rai Parlamento. La proposta è stata presentata come una possibilità allo studio, non come una misura già approvata, finanziata o dotata di regole applicative. La ministra ha collegato l'idea alla necessità di costruire la previdenza complementare dai primi anni di lavoro e a un sistema pensionistico multipilastro.",
"Il nome scelto descrive un contenitore di lungo periodo, ma le caratteristiche essenziali non sono ancora state definite pubblicamente. Non si sa chi verserebbe le somme iniziali, se lo strumento sarebbe volontario o automatico, quali investimenti potrebbe utilizzare, quali costi avrebbe e in quali condizioni il capitale sarebbe riscattabile. Senza questi elementi non è possibile calcolare un beneficio futuro né confrontarlo con fondi pensione e altri strumenti esistenti.",
"Un sistema multipilastro combina fonti diverse di reddito nella vecchiaia. Il primo pilastro è la pensione pubblica obbligatoria; il secondo comprende forme complementari legate al lavoro, mentre il risparmio individuale può costituire un ulteriore sostegno. L'obiettivo dichiarato è distribuire il rischio e integrare l'assegno pubblico, ma ogni pilastro risponde a regole, costi e garanzie differenti.",
"Aprire una posizione molto presto sfrutterebbe un orizzonte temporale lungo: rendimenti e versamenti potrebbero accumularsi per decenni. Questo principio finanziario non garantisce però un risultato. Inflazione, commissioni, continuità dei contributi, profilo di rischio e trattamento fiscale incidono sul valore reale finale. Un'illustrazione con monete e libretto non deve quindi essere letta come promessa di rendimento.",
"La continuità contributiva è il nodo richiamato dalla ministra. Carriere discontinue, salari bassi e ingressi tardivi nel lavoro riducono sia i contributi obbligatori sia la capacità di alimentare una pensione integrativa. Uno strumento aperto alla nascita potrebbe creare una posizione prima dell'occupazione, ma non risolve da solo la mancanza di reddito disponibile negli anni successivi.",
"Restano inoltre questioni di equità. Se i versamenti dipendessero soprattutto dalle famiglie, chi dispone di più risorse potrebbe accumulare un vantaggio maggiore fin dall'infanzia. Un eventuale contributo pubblico richiederebbe invece coperture di bilancio e criteri trasparenti. Sono scelte politiche decisive che non possono essere dedotte dalla sola formula «libretto previdenziale».",
"Per diventare operativa, l'ipotesi dovrebbe passare da un testo normativo, quantificazione dei costi, pareri tecnici e voto parlamentare, salvo l'uso di strumenti legislativi diversi previsti dall'ordinamento. Solo allora si potrebbero verificare beneficiari, importi, gestori e tutele. Al 10 settembre non esiste ancora un diritto individuale né una procedura per richiederlo.",
"La notizia va quindi letta come apertura di un cantiere previdenziale. I prossimi passaggi concreti saranno l'eventuale inserimento in un disegno di legge o nella manovra, la relazione tecnica e il confronto con parti sociali e autorità di vigilanza. Fino alla pubblicazione di un testo, simulazioni su assegni futuri o adesioni automatiche restano ipotesi."],
"sources":[["https://www.rai.it/raiparlamento/","Rai Parlamento — 10 settembre 2026 — dichiarazioni della ministra Marina Calderone"],["https://www.lavoro.gov.it/","Ministero del Lavoro e delle Politiche Sociali — quadro istituzionale sulle politiche previdenziali"],["https://www.covip.it/","COVIP — informazioni ufficiali sulla previdenza complementare"],["https://www.corriere.it/economia/pensioni/26_settembre_10/libretto-previdenziale-dalla-nascita-calderone.shtml","Corriere della Sera — 10 settembre 2026 — riscontro giornalistico delle dichiarazioni"]]
},
{
"slug":"legge-elettorale-senato-esame-riforma-10-settembre-2026","title":"Legge elettorale, il Senato entra nel vivo dell'esame della riforma","excerpt":"L'Aula prosegue l'esame del testo per Camera e Senato. La conclusione, con dichiarazioni e voto finale, è programmata per il 15 settembre.","published":"2026-09-10T17:40:00+02:00","category":"Italia / Politica","place":"Roma","key":"senato-legge-elettorale-ai-v316","alt":"Aula del Senato della Repubblica durante una seduta parlamentare, illustrazione editoriale fotorealistica generata con IA","sensitive":False,
"points":[("10 settembre","la prosecuzione in Aula"),("ore 10","l'orario di convocazione"),("15 settembre","la data prevista per il voto finale")],
"body":[
"Il Senato prosegue il 10 settembre l'esame della riforma della legge elettorale per Camera e Senato. L'Aula è stata convocata alle 10 dopo che la commissione competente non aveva completato l'esame del testo. Il provvedimento principale, già approvato dalla Camera, arriva così alla fase più visibile del confronto parlamentare. Il calendario ufficiale indica per martedì 15 settembre la conclusione, con dichiarazioni di voto e voto finale.",
"«Entra nel vivo» non significa che la riforma sia già legge. Durante l'esame possono essere discussi ordini del giorno ed emendamenti, e il testo può essere approvato, respinto o modificato. Se il Senato introducesse modifiche, il provvedimento dovrebbe tornare alla Camera perché entrambe le assemblee approvino lo stesso testo. Solo dopo il completamento dell'iter e la promulgazione si avrebbe una nuova disciplina vigente.",
"Il passaggio diretto all'Aula dopo il mancato completamento in commissione incide sul metodo di lavoro, non elimina il potere decisionale dei senatori. La commissione prepara normalmente il testo e riferisce all'assemblea; quando il calendario impone il passaggio, il dibattito prosegue in Aula secondo le decisioni della Presidenza e della Conferenza dei capigruppo.",
"Una legge elettorale stabilisce come i voti si trasformano in seggi. Le variabili decisive comprendono collegi, soglie, formule proporzionali o maggioritarie, modalità di scelta dei candidati e regole per le coalizioni. Piccole differenze tecniche possono produrre effetti politici rilevanti; per valutarle bisogna leggere il testo e gli emendamenti approvati, non soltanto le dichiarazioni dei partiti.",
"Il voto previsto il 15 settembre è un appuntamento di calendario, non un esito garantito. Tempi e ordine dei lavori possono cambiare con le deliberazioni parlamentari. Il sito del Senato e i resoconti stenografici restano le fonti primarie per verificare convocazioni, interventi e votazioni, mentre i commenti politici descrivono posizioni e strategie.",
"L'esame riguarda Camera e Senato, ma va distinto dalle norme costituzionali che definiscono composizione e funzioni delle due assemblee. Una legge ordinaria può modificare il sistema di attribuzione dei seggi entro i vincoli costituzionali; non può alterare da sola elementi che richiedono una revisione della Costituzione. Questa distinzione aiuta a capire quali cambiamenti possono entrare nel testo in discussione.",
"Per i cittadini gli indicatori più utili saranno il testo risultante dal voto, il numero e il contenuto degli emendamenti approvati e l'eventuale necessità di una nuova lettura alla Camera. Anche la data di entrata in vigore e le norme transitorie conteranno per stabilire a quali elezioni si applicherebbe il nuovo sistema.",
"CurioMondo aggiornerà questa pagina se il calendario cambierà o quando il Senato avrà concluso la votazione. Al momento il fatto ufficiale è la prosecuzione dell'esame in Aula, con un voto finale programmato ma non ancora avvenuto. Titoli che presentassero la riforma come approvata anticiperebbero impropriamente l'esito parlamentare."],
"sources":[["https://www.senato.it/leg/19/BGT/Schede/ProcANL/ProcANLscheda.htm","Senato della Repubblica — calendario e iter del provvedimento"],["https://www.senato.it/leg/19/BGT/Schede/Ddliter/aula.htm","Senato della Repubblica — lavori dell'Aula e sedute del 10 e 15 settembre 2026"],["https://www.senato.it/leg/19/BGT/Schede/Resaula/","Senato della Repubblica — resoconti ufficiali delle sedute"],["https://www.camera.it/leg19/126","Camera dei deputati — precedente esame e approvazione del testo"]]
},
{
"slug":"piantedosi-casapound-roma-sara-sgomberata-settembre-2026","title":"Piantedosi: «CasaPound a Roma sarà sgomberata»","excerpt":"Il ministro dell'Interno afferma che l'immobile occupato sarà liberato. Nessuna data operativa è stata indicata; nello stesso intervento parla anche dell'iniziativa di Vannacci.","published":"2026-09-10T17:20:00+02:00","category":"Italia / Politica / Cronaca","place":"Roma","key":"piantedosi-casapound-ai-v316","alt":"Ritratto istituzionale neutrale del ministro Matteo Piantedosi con bandiere italiana ed europea, illustrazione editoriale fotorealistica generata con IA","public_figure":"Matteo Piantedosi","sensitive":False,
"points":[("sarà sgomberata","l'impegno dichiarato dal ministro"),("nessuna data","il limite dell'annuncio"),("Roma","la città dell'immobile occupato")],
"body":[
"L'immobile occupato da CasaPound a Roma «sarà sgomberato». Lo ha dichiarato il ministro dell'Interno Matteo Piantedosi il 10 settembre, aggiungendo che nessuno è al di sopra della legge. La dichiarazione conferma l'indirizzo politico del Viminale, ma non contiene una data né dettagli sul piano operativo. Al momento, quindi, è corretto parlare di sgombero annunciato e non di operazione già iniziata o programmata per un giorno preciso.",
"L'edificio di via Napoleone III è da anni al centro di un confronto politico e amministrativo. Uno sgombero richiede coordinamento tra autorità di pubblica sicurezza, proprietà, prefettura e altri soggetti competenti. Possono inoltre essere necessarie valutazioni sull'ordine pubblico e sulle persone presenti. La frase del ministro non sostituisce questi passaggi e non permette di prevedere tempi certi.",
"Il valore della notizia sta nell'impegno esplicito assunto dal responsabile del Viminale. Una dichiarazione ministeriale è una fonte primaria sulla volontà politica dell'esecutivo; non è però una prova dell'avvenuta esecuzione. La verifica successiva dovrà basarsi su provvedimenti, comunicazioni della prefettura o effettive operazioni sul posto.",
"Piantedosi ha affrontato anche il tema di un'iniziativa legata al generale Roberto Vannacci, affermando di non considerarla un evento formativo. Le due questioni appartengono allo stesso intervento pubblico ma non vanno confuse: il giudizio sull'iniziativa è una valutazione politica, mentre lo sgombero dell'immobile implica un procedimento amministrativo e operativo distinto.",
"Nel dibattito sugli immobili occupati ricorrono spesso confronti con altri casi. Ogni intervento, tuttavia, dipende dalla situazione giuridica dell'edificio, dalle decisioni delle autorità e dalle condizioni di sicurezza. Il principio generale di legalità richiamato dal ministro non fornisce da solo un ordine cronologico per tutte le occupazioni presenti nella capitale.",
"Anche il verbo al futuro richiede precisione editoriale. «Sarà sgomberata» indica una promessa o previsione dell'autorità politica. Finché non viene comunicato un atto operativo, titoli come «sgomberata CasaPound» sarebbero falsi; allo stesso modo, l'assenza di una data non significa che il provvedimento sia stato abbandonato. Le due informazioni possono coesistere.",
"Le reazioni di partiti e associazioni possono ampliare il confronto, ma non cambiano lo stato fattuale dell'annuncio. Per stabilire se vi siano novità concrete occorrerà cercare una nota del Ministero dell'Interno, della Prefettura di Roma o delle forze dell'ordine. Dichiarazioni ripetute senza nuovi atti non costituiranno da sole un avanzamento operativo.",
"CurioMondo manterrà separati i livelli della vicenda: impegno politico, procedimento amministrativo ed eventuale esecuzione. Al 10 settembre è ufficiale la dichiarazione di Piantedosi; restano non pubblicati data, modalità e calendario. La pagina sarà aggiornata se emergeranno informazioni istituzionali che modifichino questo quadro."],
"sources":[["https://www.interno.gov.it/it/notizie","Ministero dell'Interno — 10 settembre 2026 — dichiarazioni del ministro Matteo Piantedosi"],["https://prefettura.interno.gov.it/it/prefetture/roma","Prefettura di Roma — autorità territoriale competente e comunicazioni istituzionali"],["https://lespresso.it/c/politica/2026/9/10/piantedosi-casapound-roma-sara-sgomberata/","L'Espresso — 10 settembre 2026 — riscontro giornalistico dell'intervento"],["https://www.open.online/2026/09/10/piantedosi-casapound-roma-sgombero-vannacci/","Open — 10 settembre 2026 — conferma delle dichiarazioni su CasaPound e Vannacci"]]
}
]

src=(ROOT/'tools/build_v310.py').read_text(encoding='utf-8'); ns={'__file__':str(ROOT/'tools/build_v310.py')}
exec(src.split('def article(a):',1)[0],ns); exec('def article(a):'+src.split('def article(a):',1)[1].split('registry_path=',1)[0],ns); article=ns['article']
rp=ROOT/'assets/data/editorial-images-v210.json'; reg=json.loads(rp.read_text())
for a in ARTICLES:
 out=article(a).replace('8 settembre 2026','10 settembre 2026').replace('?v=310','?v=316')
 attrs=' data-ai-generated="true"'
 extra=attrs+(' data-synthetic-likeness="public-figure"' if a.get('public_figure') else '')+f' data-sensitive-context="{str(a.get("sensitive",False)).lower()}"'
 out=out.replace(attrs,extra,1)
 if a.get('public_figure'):
  out=out.replace('"creditText":'+json.dumps(CAPTION,ensure_ascii=False,separators=(',',':')), '"creditText":'+json.dumps(CAPTION,ensure_ascii=False,separators=(',',':'))+',"contentCredentials":"AI-generated synthetic likeness of public figures"',1)
 (ROOT/'notizie'/f"{a['slug']}.html").write_text(out,encoding='utf-8')
 variants=[]
 for w in (480,800,1200):
  f=ROOT/'assets/images/editorial-auto'/f"{a['key']}-{w}.webp"; variants.append({'w':w,'src':f'/assets/images/editorial-auto/{f.name}','sha256':hashlib.sha256(f.read_bytes()).hexdigest(),'bytes':f.stat().st_size})
 item={'key':a['key'],'article':f"/notizie/{a['slug']}.html",'aiGenerated':True,'sensitiveContext':a.get('sensitive',False),'documentaryPhoto':False,'variants':variants,'alt':a['alt'],'disclosure':CAPTION,'portraitOnly':False,'portraitFormat':'contextual-editorial-scene','reenactedEvent':False}
 if a.get('public_figure'): item.update({'syntheticLikeness':'public-figure','publicFigure':a['public_figure']})
 reg['items'].insert(0,item)
reg['version']=VERSION; rp.write_text(json.dumps(reg,ensure_ascii=False,indent=2)+'\n')
runpy.run_path(str(ROOT/'tools/finalize_articles_20260906.py'),run_name='__main__')
for rel in ('assets/data/home-feed-v210.json','assets/data/search-index-v210.json','assets/data/editorial-images-v210.json'):
 p=ROOT/rel; d=json.loads(p.read_text()); d['version']=VERSION; p.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n')
runpy.run_path(str(ROOT/'tools/generate_category_pages.py'),run_name='__main__')
mp=ROOT/'curiomondo-site-manifest.json'; m=json.loads(mp.read_text()); m['site']['current_site_version']=VERSION; m['site']['site_version']=VERSION; mp.write_text(json.dumps(m,ensure_ascii=False,indent=2)+'\n')
print(json.dumps({'status':'ok','version':VERSION,'articles':[a['slug'] for a in ARTICLES]},ensure_ascii=False))
