#!/usr/bin/env python3
from pathlib import Path
import hashlib, json, runpy

ROOT=Path(__file__).resolve().parents[1]; VERSION=315
CAPTION="Illustrazione editoriale CurioMondo generata con IA per rappresentare questa notizia; non è una fotografia documentaria."
ARTICLES=[
{
"slug":"bce-alza-tassi-2-50-inflazione-energia-settembre-2026","title":"La BCE alza i tassi al 2,50% contro l’inflazione spinta dall’energia","excerpt":"Secondo rialzo del 2026: Francoforte aumenta il costo del denaro di 25 punti base. Crescita dell’Eurozona rivista allo 0,9%, inflazione attesa al 3%. ","published":"2026-09-10T16:45:00+02:00","category":"Mondo / Economia","place":"Berlino","key":"bce-rialzo-tassi-ai-v315","alt":"Scena editoriale contestuale fotorealistica della sede della Banca centrale europea con il simbolo dell’euro, generata con IA","points":[("2,50%","il nuovo tasso sui depositi"),("+0,25","punti percentuali decisi dalla BCE"),("3,0%","l’inflazione media stimata per il 2026")],"body":[
"La Banca centrale europea ha aumentato di 25 punti base i tre tassi di riferimento, portando quello sui depositi al 2,50%. È il secondo rialzo del 2026, dopo quello di giugno e la pausa di luglio. La decisione, presa il 10 settembre nella riunione del Consiglio direttivo ospitata a Berlino, punta a impedire che il rincaro di petrolio e gas si trasferisca in modo persistente ai prezzi di beni, servizi e salari. Per famiglie e imprese dell’area euro significa che il denaro resterà più costoso mentre la banca centrale valuta se lo shock energetico sia temporaneo o destinato a durare.",
"Il nuovo livello non modifica automaticamente nello stesso giorno tutte le rate. I mutui a tasso fisso già stipulati conservano le condizioni contrattuali; quelli variabili e i nuovi finanziamenti risentono invece dei tassi di mercato e degli indici di riferimento, con tempi e intensità diversi. Anche i rendimenti dei titoli di Stato e i costi di raccolta delle banche contano nella trasmissione. Per questo un aumento di un quarto di punto della BCE non equivale necessariamente a un identico aumento su ogni prestito, ma tende a spingere verso l’alto il costo complessivo del credito.",
"La BCE ha motivato la stretta con un’inflazione tornata ben oltre l’obiettivo del 2%, soprattutto per l’energia. Le nuove proiezioni indicano un aumento medio dei prezzi del 3,0% nel 2026 e del 2,5% nel 2027, mentre l’inflazione di fondo — calcolata senza le componenti più volatili di energia e alimentari — è attesa al 2,5% quest’anno e al 2,6% nel 2027. La distinzione è importante: l’energia può cambiare rapidamente, ma se i rincari entrano nei listini, negli affitti o nelle richieste salariali diventano più difficili da riassorbire.",
"L’economia, secondo Francoforte, sta reggendo meglio di quanto previsto a giugno. La stima di crescita dell’Eurozona per il 2026 sale dallo 0,8% allo 0,9% e quella per il 2027 dall’1,2% all’1,4%. Una domanda ancora solida offre alla banca centrale più spazio per intervenire, ma non elimina il rischio opposto: tassi elevati possono frenare investimenti, edilizia e consumi proprio mentre bollette e carburanti riducono il reddito disponibile. Christine Lagarde ha indicato rischi al rialzo per l’inflazione e al ribasso per la crescita, evitando di anticipare una traiettoria prestabilita.",
"Il tasso sui depositi è quello che la BCE riconosce alle banche quando lasciano liquidità presso l’Eurosistema ed è oggi il riferimento principale della politica monetaria. Insieme ai tassi sulle operazioni di rifinanziamento e sui prestiti marginali, influenza il prezzo a cui il sistema bancario si scambia fondi. La trasmissione attraversa poi obbligazioni, Euribor, condizioni sui mutui e remunerazione dei conti: non è immediata, ma si distribuisce su mesi e può essere diversa tra Paesi e clienti.",
"Il confronto con il 2022 aiuta a misurare, senza minimizzarlo, lo shock attuale. Allora l’inflazione dell’area euro superò il 10% e la BCE avviò una sequenza molto rapida di rialzi. Nel 2026 l’aumento dei prezzi è più contenuto e la crescita dei salari sta rallentando, segnali che riducono il rischio di una spirale prezzi-retribuzioni. Allo stesso tempo il Brent sopra 100 dollari e il gas europeo più caro tengono aperta la possibilità che trasporti, produzione e riscaldamento alimentino nuovi rincari durante l’inverno.",
"Le prossime decisioni dipenderanno dai dati su inflazione, salari, credito e attività economica, non da un calendario automatico. I mercati finanziari ipotizzano altri aumenti, ma questa aspettativa può cambiare rapidamente se l’energia scende o se l’economia rallenta. Per chi deve scegliere un mutuo o rifinanziare un debito, il dato utile non è soltanto il 2,50% della BCE: vanno confrontati TAEG, durata, costi accessori, possibilità di surroga e sostenibilità della rata anche in uno scenario meno favorevole.",
"La decisione del 10 settembre fotografa quindi un compromesso delicato. La BCE vuole evitare che uno shock nato fuori dall’economia europea si trasformi in inflazione duratura, ma riconosce che una stretta eccessiva aggraverebbe la perdita di potere d’acquisto e la debolezza degli investimenti. Il passaggio decisivo sarà capire se i rincari restano concentrati nell’energia oppure compaiono stabilmente nei servizi e nei beni non energetici: è questa propagazione, più del singolo prezzo del petrolio, che orienterà le prossime riunioni."
],"sources":[["https://www.ecb.europa.eu/press/govcdec/mopo/html/index.en.html","BCE — 10 settembre 2026 — decisione di politica monetaria e tassi ufficiali"],["https://www.reuters.com/business/ecb-raises-interest-rates-fight-off-inflation-jump-2026-09-10/","Reuters — 10 settembre 2026 — decisione, proiezioni e contesto energetico"],["https://apnews.com/article/de62b59fba535fccaf6f75e52d037c63","Associated Press — 10 settembre 2026 — conferma indipendente del rialzo e delle motivazioni"],["https://ec.europa.eu/eurostat/web/products-euro-indicators/","Eurostat — indicatori ufficiali sull’inflazione dell’area euro"]]
},
{
"slug":"petrolio-brent-105-dollari-attacchi-navi-hormuz-settembre-2026","title":"Petrolio oltre 105 dollari: gli attacchi alle navi riaccendono l’allarme Hormuz","excerpt":"Il Brent guadagna circa il 4% e il WTI supera quota 100. I flussi nel Golfo restano ridotti mentre il mercato misura il rischio sulle forniture.","published":"2026-09-10T16:25:00+02:00","category":"Mondo / Economia","place":"Stretto di Hormuz","key":"petrolio-hormuz-ai-v315","alt":"Scena editoriale contestuale fotorealistica di petroliere nello Stretto di Hormuz all’alba, generata con IA","points":[("105,26 $","il prezzo intraday del Brent"),("+4%","il rialzo registrato il 10 settembre"),("100,04 $","il WTI, sopra quota 100 da maggio")],"body":[
"Il petrolio è tornato sopra una soglia che non si vedeva da mesi: il 10 settembre il Brent ha raggiunto 105,26 dollari al barile, con un rialzo di circa il 4%, mentre il WTI statunitense è salito a 100,04 dollari. Il movimento è arrivato dopo la più intensa ondata di attacchi contro la navigazione dall’inizio della guerra in Iran e riflette soprattutto il timore che le rotte del Golfo diventino meno accessibili. Il prezzo non misura soltanto quanto greggio manca oggi, ma incorpora il rischio che navi, assicuratori e operatori riducano i transiti nei prossimi giorni.",
"Lo Stretto di Hormuz è un passaggio stretto tra Iran e Oman che collega il Golfo Persico all’Oceano Indiano. Attraverso questa rotta viaggia una quota decisiva delle esportazioni energetiche di Arabia Saudita, Iraq, Kuwait, Emirati Arabi Uniti, Qatar e Iran. Esistono oleodotti alternativi, ma non hanno capacità sufficiente per sostituire integralmente il traffico marittimo. Quando le petroliere rallentano, attendono scorte o cambiano rotta, aumentano tempi, premi assicurativi e costi di trasporto anche prima di un’effettiva perdita di produzione.",
"La tensione è cresciuta dopo attacchi reciproci contro diverse petroliere. L’Iran ha dichiarato di avere colpito dieci navi in risposta agli attacchi statunitensi contro cinque unità iraniane; queste rivendicazioni appartengono alle parti in conflitto e non possono essere considerate, da sole, una ricostruzione indipendente di ogni episodio. È invece verificabile l’effetto sul mercato: i flussi attraverso Hormuz risultano molto inferiori ai livelli precedenti alla guerra e gli operatori pagano un premio maggiore per il rischio di interruzioni prolungate.",
"Il rincaro può raggiungere l’Italia attraverso più canali. Benzina e diesel dipendono dalle quotazioni internazionali dei prodotti raffinati, dal cambio euro-dollaro, dai margini di raffinazione e distribuzione e dalla componente fiscale; per questo non seguono il Brent in modo istantaneo né perfettamente proporzionale. Le imprese energivore e i trasporti possono però subire costi più alti, mentre le aspettative di inflazione influenzano rendimenti obbligazionari e decisioni delle banche centrali. Nella stessa giornata la BCE ha alzato i tassi al 2,50%, indicando proprio l’energia come principale fonte di pressione sui prezzi.",
"Un barile di Brent è un riferimento finanziario e fisico per gran parte del greggio venduto in Europa, ma il valore di 105 dollari non è il prezzo pagato direttamente da automobilisti o aziende. Tra il greggio e la pompa ci sono raffinazione, logistica, stoccaggio, biocarburanti, imposte e tempi di adeguamento. Questa catena spiega perché i carburanti possano muoversi con ritardo o in misura diversa e perché un calo del petrolio non si traduca sempre nello stesso giorno in un calo del prezzo finale.",
"Dal lato dell’offerta, la situazione resta difficile da leggere. Un’indagine Reuters stima che la produzione dei membri OPEC sia diminuita di 640 mila barili al giorno in agosto, soprattutto per le interruzioni delle esportazioni saudite e iraniane. OPEC ha contemporaneamente ridotto per la quinta volta la previsione di crescita della domanda mondiale di petrolio nel 2026, ora indicata in 380 mila barili al giorno. Domanda più debole tende a frenare i prezzi; perdite di offerta e ostacoli alle rotte spingono nella direzione opposta.",
"Anche la Cina è una variabile centrale perché è il maggiore importatore mondiale di greggio. Acquisti cinesi più intensi possono amplificare gli effetti di una disponibilità ridotta, mentre un rallentamento può attenuare la pressione. Il mercato osserva inoltre scorte commerciali, capacità inutilizzata dei produttori e durata delle restrizioni assicurative. Nessuno di questi indicatori permette di prevedere con certezza il prezzo: il 4% del 10 settembre descrive una reazione immediata a un rischio, non una nuova quotazione garantita per settimane.",
"I segnali da seguire sono quindi concreti: volume giornaliero dei transiti a Hormuz, riapertura delle aree interdette, premi assicurativi sulle petroliere, esportazioni dei Paesi del Golfo e capacità di utilizzare rotte terrestri. Una distensione potrebbe rimuovere rapidamente una parte del premio geopolitico; nuovi attacchi o chiusure prolungate potrebbero invece trasferire il rincaro a carburanti, trasporto merci e bollette. Separare fatti osservabili, rivendicazioni militari e aspettative finanziarie è essenziale per non leggere ogni oscillazione come una certezza sul futuro."
],"sources":[["https://www.reuters.com/business/energy/brent-holds-above-100-tanker-attacks-deepen-supply-fear-2026-09-10/","Reuters — 10 settembre 2026 — quotazioni Brent e WTI, flussi e reazione del mercato"],["https://www.reuters.com/world/middle-east/iran-attacks-us-base-jordan-ships-near-hormuz-after-tankers-sunk-2026-09-09/","Reuters — 9 settembre 2026 — attacchi alle navi e dichiarazioni delle parti"],["https://www.opec.org/opec_web/en/publications/338.htm","OPEC — settembre 2026 — Monthly Oil Market Report e previsioni sulla domanda"],["https://www.eia.gov/international/content/analysis/special_topics/World_Oil_Transit_Chokepoints/","U.S. EIA — quadro sul ruolo energetico dello Stretto di Hormuz"]]
},
{
"slug":"agosto-2026-mese-piu-caldo-record-copernicus","title":"Agosto 2026 è il mese più caldo mai registrato insieme a luglio 2023","excerpt":"Copernicus misura una temperatura globale media di 16,96 °C, pari a 1,65 °C sopra il livello preindustriale. Ma un singolo mese non equivale al superamento definitivo della soglia di Parigi.","published":"2026-09-10T16:05:00+02:00","category":"Mondo / Ambiente / Scienza","place":"Bonn","key":"agosto-record-caldo-ai-v315","alt":"Scena editoriale contestuale fotorealistica di Roma durante un’intensa ondata di calore con il Tevere basso, generata con IA","points":[("16,96 °C","la temperatura media globale di agosto"),("+1,65 °C","rispetto al periodo preindustriale"),("1° dal 2025","mese di nuovo sopra 1,5 °C")],"body":[
"Agosto 2026 ha eguagliato luglio 2023 come mese più caldo mai registrato nel dataset del servizio europeo Copernicus. La temperatura media globale dell’aria in superficie è stata di 16,96 °C, pari a 0,85 °C sopra la media 1991-2020 e a 1,65 °C sopra il livello preindustriale. È anche il primo mese da novembre 2025 a superare di nuovo, su base mensile, la soglia di 1,5 °C. Il dato riunisce osservazioni da satelliti, stazioni, navi e boe all’interno del sistema di rianalisi ERA5.",
"La soglia mensile non significa che l’Accordo di Parigi sia stato formalmente violato in agosto. L’obiettivo internazionale riguarda il riscaldamento medio di lungo periodo, valutato su più decenni, non il valore di un singolo mese influenzato dalla variabilità naturale. La temperatura globale di lungo termine è stimata attorno a 1,4 °C sopra l’era preindustriale. Il superamento temporaneo resta però un segnale della vicinanza al limite e della maggiore probabilità di estremi quando il livello medio continua a salire.",
"Il record non si è limitato alla terraferma. Le acque oceaniche al di fuori delle regioni polari hanno registrato una temperatura superficiale media tra le più alte mai osservate per qualunque mese. Mari più caldi possono aumentare l’umidità disponibile per precipitazioni intense, aggravare lo stress degli ecosistemi e ridurre l’efficienza con cui l’oceano assorbe calore dall’atmosfera. Il legame con un singolo evento locale richiede sempre uno studio di attribuzione specifico: il record globale non prova da solo la causa di ogni alluvione, incendio o siccità.",
"Copernicus ha rilevato condizioni particolarmente calde e secche in vaste aree dell’Europa occidentale, uscita dall’estate più calda della propria serie. Portate fluviali basse e suoli aridi hanno aumentato la pressione su agricoltura, trasporti interni e disponibilità d’acqua. Nello stesso mese altre regioni hanno subito piogge estreme e frane. Caldo globale e distribuzione locale delle precipitazioni non sono contraddittori: un’atmosfera più calda può trattenere più vapore e rendere più marcati sia periodi asciutti sia episodi di pioggia intensa.",
"Sul risultato del 2026 agisce anche El Niño, il riscaldamento periodico del Pacifico tropicale che modifica venti e correnti e tende ad aumentare temporaneamente la temperatura media globale. El Niño non sostituisce la causa di fondo del riscaldamento: le emissioni di gas serra prodotte soprattutto dall’uso di carbone, petrolio e gas hanno innalzato la base su cui opera la variabilità naturale. La combinazione delle due componenti rende più probabili nuovi record, ma intensità e distribuzione degli effetti cambiano da regione a regione.",
"ERA5 non è un semplice elenco di termometri. È una rianalisi che combina osservazioni reali e un modello fisico dell’atmosfera per produrre una ricostruzione coerente del clima globale dal 1940. Copernicus confronta inoltre i risultati con serie che risalgono al 1850. Ogni stima ha un margine di incertezza: la differenza tra agosto 2026 e luglio 2023 è tanto piccola da essere trattata come un ex aequo, un dettaglio che evita di trasformare centesimi di grado incerti in una classifica artificiale.",
"Per città e amministrazioni il valore utile del dato sta nelle decisioni di adattamento. Piani contro il caldo, alberature scelte per il clima futuro, edifici più efficienti, reti elettriche resilienti, ombreggiamento e allerta sanitaria riducono l’esposizione anche prima che le emissioni globali diminuiscano. L’adattamento non arresta il riscaldamento e la riduzione delle emissioni non elimina immediatamente i rischi già presenti: sono due interventi complementari, con tempi diversi.",
"Nei prossimi mesi sarà importante osservare l’evoluzione di El Niño, il contenuto di calore degli oceani e la media su dodici mesi, più stabile del singolo record mensile. Un nuovo massimo può attirare l’attenzione, ma la tendenza emerge dalla successione dei dati e dalla coerenza tra sistemi indipendenti. Il dato di agosto conferma che l’intervallo climatico recente si trova ormai fuori dalle condizioni considerate normali pochi decenni fa, mentre resta necessaria cautela nel collegare il valore globale a conseguenze precise in un singolo territorio."
],"sources":[["https://climate.copernicus.eu/","Copernicus Climate Change Service — 10 settembre 2026 — bollettino climatico globale di agosto"],["https://www.reuters.com/sustainability/cop/august-was-worlds-joint-hottest-month-record-scientists-say-2026-09-10/","Reuters — 10 settembre 2026 — dati Copernicus, impatti e contesto scientifico"],["https://apnews.com/article/2a78248322a04b97f417346308d05483","Associated Press — 10 settembre 2026 — conferma indipendente del record e del ruolo di El Niño"],["https://cds.climate.copernicus.eu/datasets/reanalysis-era5-single-levels","Copernicus Climate Data Store — metodo e dataset ERA5"]]
}
]

# The site already contains today's earlier Brent/Hormuz article. Keep the
# researched draft above for audit, but publish only the two non-duplicate items.
ARTICLES=[ARTICLES[0], ARTICLES[2]]

src=(ROOT/'tools/build_v310.py').read_text(encoding='utf-8'); ns={'__file__':str(ROOT/'tools/build_v310.py')}; exec(src.split('def article(a):',1)[0],ns); exec('def article(a):'+src.split('def article(a):',1)[1].split('registry_path=',1)[0],ns); article=ns['article']
rp=ROOT/'assets/data/editorial-images-v210.json'; reg=json.loads(rp.read_text())
for a in ARTICLES:
 out=article(a).replace('8 settembre 2026','10 settembre 2026').replace('?v=310','?v=315')
 (ROOT/'notizie'/f"{a['slug']}.html").write_text(out,encoding='utf-8')
 variants=[]
 for w in (480,800,1200):
  f=ROOT/'assets/images/editorial-auto'/f"{a['key']}-{w}.webp"; variants.append({'w':w,'src':f'/assets/images/editorial-auto/{f.name}','sha256':hashlib.sha256(f.read_bytes()).hexdigest(),'bytes':f.stat().st_size})
 reg['items'].insert(0,{'key':a['key'],'article':f"/notizie/{a['slug']}.html",'aiGenerated':True,'sensitiveContext':False,'documentaryPhoto':False,'variants':variants,'alt':a['alt'],'disclosure':CAPTION,'portraitOnly':False,'portraitFormat':'contextual-editorial-scene','reenactedEvent':False})
reg['version']=VERSION; rp.write_text(json.dumps(reg,ensure_ascii=False,indent=2)+'\n')
runpy.run_path(str(ROOT/'tools/finalize_articles_20260906.py'),run_name='__main__')
for rel in ('assets/data/home-feed-v210.json','assets/data/search-index-v210.json','assets/data/editorial-images-v210.json'):
 p=ROOT/rel; d=json.loads(p.read_text()); d['version']=VERSION; p.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n')
runpy.run_path(str(ROOT/'tools/generate_category_pages.py'),run_name='__main__')
mp=ROOT/'curiomondo-site-manifest.json'; m=json.loads(mp.read_text()); m['site']['current_site_version']=VERSION; m['site']['site_version']=VERSION; mp.write_text(json.dumps(m,ensure_ascii=False,indent=2)+'\n')
print(json.dumps({'status':'ok','version':VERSION,'articles':[a['slug'] for a in ARTICLES]},ensure_ascii=False))
