#!/usr/bin/env python3
from pathlib import Path
import hashlib, json, runpy

ROOT=Path(__file__).resolve().parents[1]; VERSION=313
CAPTION="Illustrazione editoriale CurioMondo generata con IA per rappresentare questa notizia; non è una fotografia documentaria."
ARTICLES=[
{
"slug":"italia-francia-due-accordi-industriali-spazio-parigi-9-settembre-2026","title":"Spazio, firmati a Parigi due accordi industriali tra Italia e Francia","excerpt":"AIKO e Leaf Space lavoreranno con gruppi francesi su intelligenza artificiale per le operazioni satellitari e comunicazioni ottiche. Le intese sono state annunciate al vertice internazionale di Parigi.","published":"2026-09-10T07:20:00+02:00","category":"Italia / Tecnologia / Spazio","place":"Parigi","key":"italia-francia-spazio-accordi-ai-v313","alt":"Scena editoriale contestuale fotorealistica di tecnici italiani e francesi riuniti intorno a sistemi satellitari durante un vertice spaziale a Parigi, generata con IA","points":[("2 accordi","le intese industriali annunciate"),("4 imprese","i partner italiani e francesi coinvolti"),("9–10 settembre","le date del vertice di Parigi")],"body":[
"Due accordi industriali tra imprese italiane e francesi sono stati firmati a Parigi durante l’International Space Summit. Le intese collegano AIKO a Sopra Steria e CS GROUP per applicare l’intelligenza artificiale alle operazioni satellitari, e Leaf Space a Cailabs per sviluppare comunicazioni ottiche tra infrastrutture a terra e satelliti. Il Ministero delle Imprese e del Made in Italy ha comunicato la firma il 9 settembre; l’annuncio costituisce l’esito concreto della prima giornata del vertice, iniziato a Parigi e in programma fino al 10 settembre 2026.",
"Il primo accordo riguarda l’automazione delle attività svolte durante la vita operativa di un satellite. AIKO sviluppa software di intelligenza artificiale per sistemi spaziali; Sopra Steria e la controllata CS GROUP operano nell’ingegneria e nei servizi digitali. La collaborazione punta a integrare strumenti capaci di analizzare dati di missione, supportare decisioni e rendere più efficienti alcune procedure. L’intesa non equivale però alla messa in servizio immediata di un prodotto: tempi, programmi interessati e risultati tecnici dovranno essere verificati attraverso i successivi progetti esecutivi.",
"La seconda collaborazione unisce Leaf Space, che fornisce servizi di stazioni di terra per comunicare con satelliti, e Cailabs, specializzata in tecnologie fotoniche. L’obiettivo dichiarato è lavorare sulle comunicazioni laser tra orbita e Terra. Rispetto ai collegamenti radio tradizionali, i sistemi ottici possono trasferire grandi quantità di dati usando fasci molto direzionali, ma richiedono puntamento preciso e risentono di nuvole e condizioni atmosferiche. Per questo le reti operative combinano spesso più stazioni e soluzioni complementari, riducendo il rischio che un singolo sito non sia disponibile.",
"Il Mimit presenta le intese come un rafforzamento della cooperazione sulle tecnologie abilitanti. La formula indica componenti e capacità che non servono a una sola missione: software autonomo, reti di terra e collegamenti ottici possono essere impiegati nell’osservazione terrestre, nelle telecomunicazioni sicure e nella gestione di costellazioni. Il valore industriale dipenderà dalla possibilità di trasformare la sperimentazione in servizi acquistabili, proprietà intellettuale condivisa e contratti europei, non dal solo numero di protocolli firmati.",
"Il vertice riunisce a Parigi rappresentanti politici, imprese e agenzie spaziali in una fase in cui l’Europa cerca maggiore autonomia nell’accesso all’orbita e nelle comunicazioni protette. L’Agenzia spaziale europea ha indicato tra i temi del summit le attività umane in orbita bassa, le future operazioni lunari e la preparazione delle missioni verso Marte. Il calendario precede inoltre la riunione ministeriale intermedia dell’ESA prevista a Roma nel dicembre 2026 e le discussioni sul prossimo quadro finanziario dell’Unione europea.",
"Italia e Francia cooperano già nei lanciatori Ariane e Vega, nei programmi di osservazione della Terra e nella costellazione europea IRIS² per connettività sicura. Questa base rende plausibile la ricerca di integrazioni industriali, ma crea anche sovrapposizioni e interessi nazionali da conciliare. Le due nuove intese hanno una scala più circoscritta rispetto ai grandi programmi istituzionali: coinvolgono aziende e tecnologie precise e vanno valutate per l’avanzamento dei prototipi, le dimostrazioni in orbita e gli eventuali ordini.",
"Un limite delle informazioni disponibili è l’assenza, nel comunicato iniziale, di valori economici, scadenze contrattuali e missioni già assegnate. CurioMondo distingue quindi la firma delle collaborazioni, che è documentata, dai benefici occupazionali o commerciali futuri, che non possono ancora essere quantificati. Saranno aggiornamenti sostanziali la pubblicazione di investimenti, test completati, contratti di fornitura o risultati tecnici misurabili.",
"Per leggere i prossimi annunci del settore conviene osservare tre passaggi: chi finanzia lo sviluppo, dove viene provata la tecnologia e quale cliente la utilizza. Un’intesa tra imprese crea una cornice; una dimostrazione valida la soluzione in condizioni reali; un contratto dimostra che esiste domanda. Questa sequenza permette di separare la diplomazia industriale dai progressi che modificano davvero la capacità spaziale europea."
],"sources":[["https://www.mimit.gov.it/it/notizie-stampa/spazio-firmati-a-parigi-due-accordi-industriali-italia-francia-urso-rafforziamo-la-cooperazione-sulle-tecnologie-abilitanti","Mimit — 9 settembre 2026 — firma, imprese coinvolte e ambiti delle due intese"],["https://www.mimit.gov.it/it/notizie-stampa/spazio-urso-da-oggi-a-parigi-per-linternational-space-summit","Mimit — 9 settembre 2026 — programma e priorità della partecipazione italiana"],["https://www.esa.int/About_Us/Corporate_news/Europe_s_space_future_in_focus_at_the_International_Space_Summit","ESA — 7 settembre 2026 — temi e calendario istituzionale del vertice"],["https://www.reuters.com/business/aerospace-defense/macron-summit-seek-boost-european-space-despite-no-shows-2026-09-08/","Reuters — 8 settembre 2026 — contesto industriale e politico europeo"]]
},
{
"slug":"brent-oltre-100-dollari-attacchi-navi-stretto-hormuz-10-settembre-2026","title":"Petrolio, Brent oltre 100 dollari mentre cresce il rischio nello Stretto di Hormuz","excerpt":"Gli attacchi alle navi e i flussi ridotti dal Golfo mantengono il greggio sopra la soglia dei 100 dollari. L’EIA alza la previsione per la seconda metà del 2026.","published":"2026-09-10T07:10:00+02:00","category":"Mondo / Economia / Energia","place":"Singapore","key":"brent-oltre-100-hormuz-ai-v313","alt":"Scena editoriale contestuale fotorealistica di petroliere in navigazione nello Stretto di Hormuz all’alba, generata con IA senza rappresentare attacchi","points":[("$101,10","la quotazione Brent rilevata da Reuters"),("+30% circa","l’aumento dai minimi di agosto"),("$90","la media prevista dall’EIA nel secondo semestre")],"body":[
"Il petrolio Brent è rimasto sopra 100 dollari al barile nelle prime contrattazioni del 10 settembre 2026, dopo aver superato la soglia nella seduta precedente. Reuters ha rilevato il contratto a 101,10 dollari intorno alle 02:56 GMT, in lieve calo giornaliero, mentre il West Texas Intermediate era a 96,24 dollari. Il movimento riflette soprattutto il timore che gli attacchi alle navi e le restrizioni al traffico nello Stretto di Hormuz riducano ancora le esportazioni dal Golfo Persico.",
"Le cifre sui singoli attacchi provengono in parte dalle parti coinvolte nel conflitto e devono essere trattate come rivendicazioni finché non esiste una verifica indipendente completa. L’Iran ha dichiarato di aver colpito dieci navi in risposta all’affondamento di cinque petroliere iraniane attribuito agli Stati Uniti. Il fatto economico verificabile è l’aumento del rischio percepito, visibile nei prezzi, nei costi di trasporto e nella riduzione dei flussi; il bilancio militare richiede conferme separate.",
"Lo Stretto di Hormuz è il passaggio marittimo che collega il Golfo Persico al Golfo di Oman. Prima dell’attuale conflitto vi transitava circa un quinto delle forniture mondiali di petrolio e gas, secondo i dati energetici richiamati dalle analisi internazionali. La sua importanza nasce dalla concentrazione: Arabia Saudita, Iraq, Kuwait, Emirati Arabi Uniti, Qatar e Iran dipendono in misura diversa da questa rotta, mentre oleodotti alternativi non possono sostituirne rapidamente tutta la capacità.",
"Il prezzo non misura soltanto i barili che mancano oggi. Include un premio per il rischio che trasporti, assicurazioni o carichi futuri diventino più costosi o imprevedibili. Il Brent è aumentato di quasi il 30% dai minimi toccati all’inizio di agosto. Nel mercato fisico, il Dated Brent usato come riferimento per numerose compravendite era già sopra 100 dollari dal 3 settembre, secondo dati LSEG citati da Reuters. Questa differenza tra contratti finanziari e consegne fisiche aiuta a capire perché la tensione può precedere una carenza visibile ai distributori.",
"L’Energy Information Administration statunitense ha aggiornato il 9 settembre il proprio scenario. L’agenzia prevede per il Brent una media vicina a 90 dollari nella seconda metà del 2026, otto dollari in più rispetto alla stima del mese precedente. La previsione incorpora produzione mediorientale indisponibile e traffico limitato, ma resta uno scenario, non una certezza: un accordo duraturo, un recupero dei transiti o un peggioramento militare cambierebbero rapidamente il risultato.",
"Anche le vie alternative sono sotto pressione. Gli attacchi degli Houthi contro obiettivi sauditi hanno ridotto le esportazioni in partenza dal porto di Yanbu sul Mar Rosso, secondo l’EIA. Yanbu riceve greggio attraverso l’oleodotto est-ovest saudita e permette di evitare Hormuz; se questa uscita perde affidabilità, diminuisce uno dei principali margini di sicurezza logistici disponibili nella regione.",
"Per famiglie e imprese europee il passaggio dal greggio ai prezzi finali non è automatico né immediato. Contano il cambio euro-dollaro, le scorte, i costi di raffinazione, la concorrenza e la fiscalità. Un Brent sopra 100 dollari aumenta comunque il costo potenziale di carburanti, trasporto e produzione e può rendere più persistente l’inflazione energetica. Le banche centrali osservano proprio questo rischio: uno shock temporaneo richiede una risposta diversa da rincari che si trasferiscono a salari e servizi.",
"I dati decisivi nelle prossime giornate saranno i volumi effettivamente transitati, le tariffe assicurative, le partenze dai porti del Golfo e gli aggiornamenti sulle scorte. CurioMondo non trasformerà ogni oscillazione intraday in una nuova storia: la pagina sarà aggiornata se cambieranno in modo sostanziale i flussi, le previsioni ufficiali o la sicurezza delle rotte."
],"sources":[["https://www.reuters.com/business/energy/brent-holds-above-100-tanker-attacks-deepen-supply-fear-2026-09-10/","Reuters — 10 settembre 2026 — prezzi, andamento e quadro dei trasporti"],["https://www.eia.gov/outlooks/steo/report/global_oil.php","U.S. EIA — 9 settembre 2026 — previsione Brent e vincoli alle esportazioni"],["https://www.eia.gov/outlooks/steo/report/energysecurity/article.php","U.S. EIA — dati sui flussi energetici attraverso Hormuz"],["https://www.reuters.com/world/china/global-markets-wrapup-1-2026-09-10/","Reuters — 10 settembre 2026 — reazione dei mercati globali e rendimenti"]]
}
]
src=(ROOT/'tools/build_v310.py').read_text(encoding='utf-8'); ns={'__file__':str(ROOT/'tools/build_v310.py')}; exec(src.split('def article(a):',1)[0],ns); exec('def article(a):'+src.split('def article(a):',1)[1].split('registry_path=',1)[0],ns); article=ns['article']
rp=ROOT/'assets/data/editorial-images-v210.json'; reg=json.loads(rp.read_text())
for a in ARTICLES:
 out=article(a).replace('8 settembre 2026','10 settembre 2026').replace('?v=310','?v=313')
 (ROOT/'notizie'/f"{a['slug']}.html").write_text(out,encoding='utf-8')
 variants=[]
 for w in (480,800,1200):
  f=ROOT/'assets/images/editorial-auto'/f"{a['key']}-{w}.webp"; variants.append({'w':w,'src':f'/assets/images/editorial-auto/{f.name}','sha256':hashlib.sha256(f.read_bytes()).hexdigest(),'bytes':f.stat().st_size})
 reg['items'].insert(0,{'key':a['key'],'article':f"/notizie/{a['slug']}.html",'aiGenerated':True,'sensitiveContext':False,'documentaryPhoto':False,'variants':variants,'alt':a['alt'],'disclosure':CAPTION,'portraitOnly':False,'portraitFormat':'contextual-editorial-scene','reenactedEvent':False})
reg['version']=VERSION; rp.write_text(json.dumps(reg,ensure_ascii=False,indent=2)+'\n')
runpy.run_path(str(ROOT/'tools/finalize_articles_20260906.py'),run_name='__main__')
for rel in ('assets/data/home-feed-v210.json','assets/data/search-index-v210.json','assets/data/editorial-images-v210.json'):
 p=ROOT/rel; d=json.loads(p.read_text()); d['version']=VERSION; p.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n')
runpy.run_path(str(ROOT/'tools/generate_category_pages.py'),run_name='__main__')
mp=ROOT/'curiomondo-site-manifest.json'; m=json.loads(mp.read_text()); m['site']['current_site_version']=VERSION; m['site']['site_version']=VERSION; mp.write_text(json.dumps(m,ensure_ascii=False,indent=2)+'\n')
print(json.dumps({'status':'ok','version':VERSION,'articles':[a['slug'] for a in ARTICLES]},ensure_ascii=False))
