#!/usr/bin/env python3
from pathlib import Path
import hashlib, json, runpy

ROOT=Path(__file__).resolve().parents[1]; VERSION=319
CAPTION="Illustrazione editoriale CurioMondo generata con IA per rappresentare questa notizia; non è una fotografia documentaria."

ARTICLES=[
{
"slug":"diesel-sconto-accise-proroga-17-settembre-2026","title":"Diesel, prorogato fino al 17 settembre lo sconto di 17 centesimi","excerpt":"Il Consiglio dei ministri estende per altri sette giorni la riduzione sul gasolio. Il decreto costa 86 milioni e rinvia la scelta sulle misure successive.","published":"2026-09-11T04:14:00+02:00","category":"Italia / Economia / Carburanti","place":"Roma","key":"diesel-accise-proroga-ai-v319","alt":"Distributore di gasolio in Italia durante un rifornimento, illustrazione editoriale fotorealistica generata con IA","sensitive":False,
"points":[("17 settembre","la nuova scadenza"),("17 cent/litro","la riduzione indicata dal Governo"),("86 milioni","il costo della proroga")],
"body":[
"Il Consiglio dei ministri ha prorogato fino al 17 settembre 2026 la riduzione del prezzo del gasolio usato come carburante. Il beneficio comunicato è di 17 centesimi al litro, considerando anche l'effetto dell'Iva. Il provvedimento evita che lo sconto scada alla mezzanotte del 10 settembre.",
"La misura resta invariata per altri sette giorni. La copertura indicata per il decreto è di 86 milioni di euro, riferiti a questa sola estensione.",
"La nuova scadenza non trasforma il taglio in una misura permanente. Chi fa rifornimento continua a beneficiare della riduzione durante la settimana coperta dal decreto, mentre dal 18 settembre servirà un nuovo intervento per evitare il ritorno all'aliquota ordinaria. Il Governo non ha ancora approvato il sistema di sostegni che potrebbe sostituire le proroghe generalizzate.",
"Il valore di 17 centesimi comprende due componenti. La riduzione dell'accisa è pari a 14 centesimi al litro; poiché l'Iva si calcola anche sull'imposta incorporata nel prezzo, il vantaggio finale sale a circa 17 centesimi. Questo meccanismo spiega perché la cifra comunicata al consumatore è superiore al solo taglio fiscale nominale.",
"La proroga costa 86 milioni perché lo Stato rinuncia temporaneamente a una parte del gettito. Secondo le informazioni diffuse dopo il Consiglio dei ministri, la copertura arriva da una riduzione del Fondo per la politica economica. Il costo riguarda questa estensione settimanale e non riassume la spesa sostenuta per tutte le precedenti misure sui carburanti del 2026.",
"Il provvedimento interviene mentre i prezzi energetici restano sotto pressione. Il Brent ha superato i 100 dollari al barile e le tensioni sulle rotte del Medio Oriente aumentano l'incertezza sui costi di approvvigionamento.",
"Il prezzo alla pompa, però, non dipende soltanto dal greggio. Incidono cambio euro-dollaro, raffinazione, distribuzione, margini commerciali e tempi con cui le variazioni si trasferiscono ai listini.",
"Per verificare l'effetto reale conviene confrontare il prezzo praticato dallo stesso impianto prima e durante la proroga. Lo sconto fiscale stabilisce una riduzione rispetto allo scenario senza intervento, ma non blocca il prezzo finale. Se la componente industriale aumenta nello stesso periodo, il consumatore può trovare un prezzo comunque più alto nonostante il taglio delle accise.",
"L'orizzonte di una sola settimana segnala che la risposta strutturale è ancora aperta. Il Governo valuta aiuti più selettivi, potenzialmente collegati al reddito, per contenere la spesa pubblica rispetto a uno sconto rivolto a tutti. Finché non esiste un testo approvato, destinatari, importi e modalità di accesso restano ipotesi e non devono essere presentati come diritti già disponibili.",
"Il prossimo passaggio decisivo arriverà prima del 17 settembre. Un'altra proroga manterrebbe l'impianto attuale; un decreto diverso potrebbe restringere la platea o cambiare il meccanismo. CurioMondo aggiornerà la notizia soltanto in presenza di un atto approvato, distinguendo le decisioni ufficiali dalle anticipazioni politiche."],
"sources":[["https://www.ansa.it/sito/notizie/topnews/index.shtml","ANSA — 11 settembre 2026 — costo, copertura e scadenza della proroga"],["https://www.televideo.rai.it/televideo/pub/notiziasolotesto.jsp?id=1694318&pagina=622&sottopagina=13","Rai Televideo — 10 settembre 2026 — approvazione del decreto in Consiglio dei ministri"],["https://www.borsaitaliana.it/borsa/notizie/teleborsa/economia/decreto-accise-cdm-approva-ulteriore-proroga-di-una-settimana-239_2026-09-10_TLB.html?lang=it","Borsa Italiana/Teleborsa — 10 settembre 2026 — importo dello sconto e nuova scadenza"],["https://www.reuters.com/business/energy/italy-prepares-new-measures-tackle-spiking-fuel-prices-amid-fiscal-concerns-2026-07-27/","Reuters — 27 luglio 2026 — quadro fiscale e andamento dei carburanti"]]
},
{
"slug":"malpensa-easyjet-emergenza-146-passeggeri-10-settembre-2026","title":"Malpensa, emergenza su un volo EasyJet: evacuati 146 passeggeri","excerpt":"Fumo e un principio d'incendio vengono segnalati durante il rullaggio del volo diretto a Praga. Nessun ferito; lo scalo è rimasto chiuso per circa un'ora.","published":"2026-09-10T19:17:00+02:00","category":"Italia / Lombardia / Cronaca / Trasporti","place":"Malpensa","key":"malpensa-easyjet-emergenza-ai-v319","alt":"Aereo passeggeri fermo su una pista aeroportuale con mezzi antincendio, illustrazione editoriale fotorealistica generata con IA","sensitive":True,
"points":[("146","i passeggeri evacuati"),("circa un'ora","la chiusura dello scalo"),("nessun ferito","il bilancio riferito")],
"body":[
"Un volo EasyJet diretto da Milano Malpensa a Praga ha dichiarato un'emergenza nel pomeriggio del 10 settembre, dopo la segnalazione di fumo e di un principio d'incendio durante il rullaggio. I 146 passeggeri sono stati evacuati e affidati all'assistenza a terra. Non risultano feriti. L'aeroporto è rimasto chiuso dalle 17.30 alle 18.30 circa, con conseguenze temporanee sui movimenti programmati.",
"L'aereo non era ancora decollato quando sono scattate le procedure. Questa distinzione riduce il rischio di interpretare l'episodio come un incendio in volo. Il velivolo si trovava su un raccordo dell'aeroporto; i mezzi di emergenza hanno raggiunto l'area e l'evacuazione è stata completata mentre le autorità mettevano in sicurezza le operazioni.",
"Le prime ricostruzioni parlano di un possibile problema a un gruppo ausiliario di potenza. Questo apparato fornisce energia elettrica e aria compressa quando i motori principali non svolgono tali funzioni, soprattutto durante le operazioni a terra. L'origine tecnica resta però da accertare: una segnalazione iniziale non equivale alla conclusione di un'indagine manutentiva o dell'autorità aeronautica.",
"La chiusura di circa un'ora serve a mantenere libere le aree operative durante l'intervento e a evitare interferenze con i soccorsi. Anche un blocco breve può generare ritardi a catena, perché gli aeromobili in arrivo vengono trattenuti, dirottati o inseriti in una nuova sequenza. Il ripristino dei movimenti non elimina immediatamente tutte le conseguenze sull'orario della serata.",
"L'evacuazione precauzionale non indica da sola la gravità finale del guasto. In aviazione le procedure sono progettate per agire prima che una condizione incerta peggiori. Equipaggio, controllori, gestore aeroportuale e servizi antincendio assumono ruoli separati ma coordinati; il loro compito iniziale è proteggere le persone, mentre l'analisi della causa viene dopo.",
"Il dato più rilevante per i passeggeri è l'assenza di feriti. Restano da verificare il componente coinvolto, l'entità dei danni e il destino operativo dell'aeromobile. Queste informazioni possono arrivare dalla compagnia, dal gestore dello scalo o dagli organismi competenti e non devono essere dedotte da immagini o testimonianze parziali.",
"L'illustrazione associata all'articolo non ricostruisce il momento dell'emergenza e non mostra persone in pericolo. Rappresenta soltanto un aereo fermo con mezzi antincendio in un contesto aeroportuale. È una scelta necessaria per informare senza trasformare una scena generata in una falsa prova documentaria.",
"Eventuali aggiornamenti utili riguarderanno il rapporto tecnico e l'impatto definitivo sui voli. Il bilancio disponibile resta: 146 persone evacuate, nessun ferito e operatività sospesa per circa un'ora. Numeri diversi o cause definitive richiederanno una comunicazione attribuibile e verificabile.",
"Per chi aveva un viaggio programmato, l'informazione operativa affidabile resta quella fornita dalla compagnia e dal gestore aeroportuale. Ritardi, riprotezioni e rimborsi dipendono dal singolo biglietto e dall'effettiva cancellazione, non dalla sola chiusura temporanea della pista."],
"sources":[["https://www.adnkronos.com/regioni/","Adnkronos — 10 settembre 2026 — evacuazione, rotta e chiusura temporanea dello scalo"],["https://www.varesenoi.it/2026/09/10/leggi-notizia/argomenti/cronaca-20/articolo/malpensa-principio-dincendio-su-un-aereo-in-fase-di-decollo-evacuati-i-146-passeggeri-a-bordo.html","VareseNoi — 10 settembre 2026 — riscontro locale e numero dei passeggeri"],["https://it.euronews.com/","Euronews — 10 settembre 2026 — conferma dell'emergenza a Malpensa"],["https://www.milanomalpensa-airport.com/","Milano Malpensa — informazioni operative ufficiali dello scalo"]]
},
{
"slug":"taiwan-vicepresidente-hsiao-italia-ventotene-11-settembre-2026","title":"Taiwan, la vicepresidente Hsiao in Italia per il forum di Ventotene","excerpt":"La visita, mantenuta riservata fino all'arrivo, è rara per un'esponente taiwanese di questo livello. Con lei il ministro degli Esteri Lin Chia-lung.","published":"2026-09-11T03:27:00+02:00","category":"Mondo / Italia / Taiwan / Diplomazia","place":"Italia","key":"hsiao-italia-ventotene-ai-v319","alt":"ritratto editoriale neutrale di Hsiao Bi-khim su sfondo blu, illustrazione fotorealistica generata con IA","public_figure":"Hsiao Bi-khim","sensitive":False,
"points":[("11 settembre","la conferma della visita"),("giovedì-sabato","la durata del forum"),("nessun rapporto formale","tra Italia e Taiwan")],
"body":[
"La vicepresidente di Taiwan Hsiao Bi-khim è in Italia per partecipare alla Ventotene Conference for Freedom and Democracy, insieme al ministro degli Esteri Lin Chia-lung. L'Ufficio presidenziale taiwanese ha confermato la missione l'11 settembre.",
"La presenza era stata mantenuta riservata fino all'arrivo per ragioni di sicurezza, secondo Pina Picierno, vicepresidente del Parlamento europeo. Il forum si svolge da giovedì a sabato.",
"La visita è rilevante perché funzionari taiwanesi di questo livello si recano raramente in Paesi europei privi di relazioni diplomatiche formali con Taipei. L'Italia, come la maggior parte degli Stati, riconosce la Repubblica popolare cinese. Ciò non impedisce contatti economici, parlamentari e culturali con Taiwan, ma rende le missioni politiche più sensibili nei rapporti con Pechino.",
"Hsiao è accompagnata dal responsabile della diplomazia taiwanese, un elemento che aumenta il peso della delegazione. L'Ufficio presidenziale ha fornito soltanto una comunicazione breve e ha annunciato ulteriori dettagli dopo il rientro. Non risultano quindi pubblicati, al momento, un programma completo di incontri bilaterali o intese firmate durante la permanenza italiana.",
"Il nome di Ventotene richiama il manifesto federalista europeo scritto durante il confino fascista da Altiero Spinelli ed Ernesto Rossi. La conferenza contemporanea usa l'isola come luogo simbolico per discutere libertà e democrazia. Questo legame storico spiega il valore politico della sede, ma non trasforma l'evento in un vertice ufficiale dell'Unione europea.",
"Taiwan cerca da anni spazi di dialogo con l'Europa, soprattutto su sicurezza, democrazia e filiere tecnologiche. L'isola ospita un'industria dei semiconduttori centrale per l'economia mondiale. I rapporti con i partner europei combinano quindi interesse strategico e prudenza diplomatica, perché Pechino considera Taiwan una propria provincia mentre il governo taiwanese respinge questa rivendicazione.",
"Hsiao è stata rappresentante di Taiwan negli Stati Uniti prima di diventare vicepresidente nel 2024. La Cina l'ha inserita tra le personalità sanzionate e la definisce sostenitrice dell'indipendenza. Queste sono posizioni attribuite a Pechino; il governo taiwanese sostiene invece che soltanto la popolazione dell'isola possa decidere il proprio futuro.",
"La presenza in Italia non equivale a un riconoscimento diplomatico di Taiwan da parte di Roma. Un incontro in un forum politico può avere importanza simbolica senza modificare automaticamente la politica estera italiana. Per valutare eventuali conseguenze serviranno comunicazioni del Governo, del ministero degli Esteri o delle istituzioni coinvolte.",
"I prossimi fatti verificabili saranno gli interventi pubblici della delegazione, l'elenco degli incontri e le reazioni ufficiali di Italia e Cina. Fino ad allora, CurioMondo considera confermati viaggio, partecipazione al forum e composizione principale della delegazione, evitando di attribuire alla missione risultati non ancora annunciati."],
"sources":[["https://english.president.gov.tw/News","Ufficio del Presidente di Taiwan — 11 settembre 2026 — conferma della missione"],["https://www.reuters.com/world/asia-pacific/taiwans-vice-president-is-visiting-italy-taiwanese-presidential-office-says-2026-09-11/","Reuters — 11 settembre 2026 — visita, forum e contesto diplomatico"],["https://www.europarl.europa.eu/meps/it/197812/PINA_PICIERNO/home","Parlamento europeo — profilo istituzionale della vicepresidente Pina Picierno"],["https://english.president.gov.tw/Page/645","Ufficio del Presidente di Taiwan — profilo ufficiale di Hsiao Bi-khim"]]
}
]

src=(ROOT/'tools/build_v310.py').read_text(encoding='utf-8'); ns={'__file__':str(ROOT/'tools/build_v310.py')}
exec(src.split('def article(a):',1)[0],ns); exec('def article(a):'+src.split('def article(a):',1)[1].split('registry_path=',1)[0],ns); article=ns['article']
rp=ROOT/'assets/data/editorial-images-v210.json'; reg=json.loads(rp.read_text())
for a in ARTICLES:
 out=article(a).replace('8 settembre 2026','11 settembre 2026').replace('?v=310','?v=319')
 out=out.replace('<article class="art-body" data-length-policy="3000-7000">','<article class="art-body" data-length-policy="3000-7000" data-editorial-protocol="4.0" data-article-format="standard">',1)
 attrs=' data-ai-generated="true"'; extra=attrs+(' data-synthetic-likeness="public-figure"' if a.get('public_figure') else '')+f' data-sensitive-context="{str(a.get("sensitive",False)).lower()}"'
 if a.get('public_figure'): extra+=' data-portrait-format="neutral-isolated"'
 out=out.replace(attrs,extra,1)
 if a.get('public_figure'):
  out=out.replace('"creditText":'+json.dumps(CAPTION,ensure_ascii=False,separators=(',',':')), '"creditText":'+json.dumps(CAPTION,ensure_ascii=False,separators=(',',':'))+',"contentCredentials":"AI-generated synthetic likeness of a public figure"',1)
 (ROOT/'notizie'/f"{a['slug']}.html").write_text(out,encoding='utf-8')
 variants=[]
 for w in (480,800,1200):
  f=ROOT/'assets/images/editorial-auto'/f"{a['key']}-{w}.webp"; variants.append({'w':w,'src':f'/assets/images/editorial-auto/{f.name}','sha256':hashlib.sha256(f.read_bytes()).hexdigest(),'bytes':f.stat().st_size})
 item={'key':a['key'],'article':f"/notizie/{a['slug']}.html",'aiGenerated':True,'sensitiveContext':a.get('sensitive',False),'documentaryPhoto':False,'variants':variants,'alt':a['alt'],'disclosure':CAPTION,'portraitOnly':bool(a.get('public_figure')),'portraitFormat':'neutral-isolated' if a.get('public_figure') else 'contextual-editorial-scene','reenactedEvent':False}
 if a.get('public_figure'): item.update({'syntheticLikeness':'public-figure','publicFigure':a['public_figure']})
 reg['items'].insert(0,item)
reg['version']=VERSION; rp.write_text(json.dumps(reg,ensure_ascii=False,indent=2)+'\n')
runpy.run_path(str(ROOT/'tools/finalize_articles_20260906.py'),run_name='__main__')
for rel in ('assets/data/home-feed-v210.json','assets/data/search-index-v210.json','assets/data/editorial-images-v210.json'):
 p=ROOT/rel; d=json.loads(p.read_text()); d['version']=VERSION; p.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n')
runpy.run_path(str(ROOT/'tools/generate_category_pages.py'),run_name='__main__')
mp=ROOT/'curiomondo-site-manifest.json'; m=json.loads(mp.read_text()); m['site']['current_site_version']=VERSION; m['site']['site_version']=VERSION; mp.write_text(json.dumps(m,ensure_ascii=False,indent=2)+'\n')
print(json.dumps({'status':'ok','version':VERSION,'articles':[a['slug'] for a in ARTICLES]},ensure_ascii=False))
