#!/usr/bin/env python3
from pathlib import Path
import hashlib,json,runpy
ROOT=Path(__file__).resolve().parents[1]; VERSION=312
CAPTION="Illustrazione editoriale CurioMondo generata con IA per rappresentare questa notizia; non è una fotografia documentaria."
ARTICLES=[
{
"slug":"electrolux-sciopero-15-settembre-esuberi-chiusura-cerreto-desi-2026","title":"Electrolux, sciopero nazionale il 15 settembre contro esuberi e chiusura di Cerreto d’Esi","excerpt":"I sindacati fermano per otto ore gli stabilimenti italiani dopo il mancato avanzamento della trattativa. Il piano indicato prevede 1.450 esuberi e la chiusura del sito marchigiano.","published":"2026-09-09T18:20:00+02:00","category":"Italia / Economia / Lavoro","place":"Italia","key":"electrolux-sciopero-italia-ai-v312","alt":"Lavoratori all’esterno di uno stabilimento Electrolux in Italia, scena editoriale contestuale fotorealistica generata con IA","points":[("15 settembre","la data dello sciopero nazionale"),("8 ore","la durata proclamata"),("1.450","gli esuberi indicati nel piano")],"body":[
"I sindacati metalmeccanici hanno confermato uno sciopero di otto ore per il 15 settembre in tutti gli stabilimenti Electrolux italiani. La mobilitazione segue il mancato avanzamento del confronto sul piano di riorganizzazione del gruppo, che prevede 1.450 esuberi a livello nazionale e la chiusura dello stabilimento di Cerreto d’Esi, nelle Marche. La data dello sciopero è il nuovo elemento operativo della vertenza; numeri e assetto industriale restano oggetto di negoziato e non corrispondono ancora a licenziamenti già eseguiti.",
"Il piano riguarda sedi con funzioni e produzioni diverse. A Susegana, in Veneto, le informazioni diffuse in occasione del tavolo indicano 420 posizioni coinvolte, fra impiegati e operai. A Cerreto d’Esi la prospettiva di chiusura interessa circa 170 posti diretti, con conseguenze potenziali anche sull’indotto locale. Per altri siti il confronto comprende organizzazione del lavoro, turni, volumi e investimenti. Sommare tutte le posizioni offre la dimensione nazionale, ma non descrive da solo tempi e strumenti previsti per ciascun territorio.",
"La trattativa si è svolta anche al Ministero delle Imprese e del Made in Italy. Il ministro Adolfo Urso ha sottolineato il coordinamento con le Regioni coinvolte, mentre amministrazioni locali e organizzazioni dei lavoratori chiedono modifiche sostanziali. Un tavolo ministeriale non può imporre autonomamente un piano industriale privato, ma può favorire accordi, verificare l’uso degli strumenti pubblici e coordinare ammortizzatori, formazione e possibili soluzioni produttive.",
"Electrolux aveva annunciato a maggio un processo di ottimizzazione dell’assetto italiano. L’azienda collega la riorganizzazione alla competitività del settore europeo degli elettrodomestici, condizionato da domanda debole, costi e capacità produttiva. I sindacati contestano che l’aggiustamento ricada soprattutto sull’occupazione e chiedono garanzie sugli investimenti. Queste sono posizioni delle parti: per valutarle servono dati per stabilimento su produzione, ordini, investimenti già realizzati e alternative esaminate.",
"La parola esubero indica una posizione che l’impresa considera eccedente rispetto alla nuova organizzazione; non equivale automaticamente a un licenziamento immediato. In una vertenza possono intervenire uscite volontarie, pensionamenti, riduzione dell’orario, cassa integrazione, riqualificazione, trasferimenti o ricollocazioni. L’impatto reale dipenderà dall’accordo finale e dal numero di persone per cui non sarà trovata una soluzione condivisa.",
"La chiusura di un sito pone un problema diverso dalla riduzione distribuita. In un territorio con poche alternative industriali, la perdita di uno stabilimento può ridurre redditi, domanda locale e commesse per fornitori. Il valore aggiunto di una soluzione non si misura quindi soltanto dal totale nazionale degli esuberi evitati, ma anche dalla capacità di mantenere competenze e attività produttive nei luoghi più esposti.",
"Lo sciopero del 15 settembre serve ai sindacati per aumentare la pressione prima dei prossimi incontri. Otto ore significano normalmente un’intera giornata o turno di lavoro, ma modalità precise possono variare fra stabilimenti e devono essere comunicate dalle rappresentanze locali. La protesta non chiude il negoziato: segnala che, secondo Fim, Fiom e Uilm, le aperture ricevute non modificano i punti centrali del piano.",
"I prossimi fatti verificabili saranno un eventuale nuovo tavolo al Mimit, proposte aziendali riviste, accordi sugli strumenti occupazionali e il grado di adesione allo sciopero. CurioMondo aggiornerà questa pagina solo in presenza di cambiamenti sostanziali, distinguendo gli esuberi annunciati dalle uscite effettive e le richieste sindacali dagli impegni formalizzati."
],"sources":[["https://www.reuters.com/business/world-at-work/italian-unions-call-one-day-strike-electrolux-over-job-cut-plan-2026-09-09/","Reuters — 9 settembre 2026 — data dello sciopero e stato della trattativa"],["https://www.mimit.gov.it/it/notizie-stampa/electrolux-urso-importante-piena-condivisione-con-regioni","Mimit — 8 settembre 2026 — coordinamento istituzionale sulla vertenza"],["https://www.electroluxgroup.com/en/news/electrolux-group-avvia-un-processo-di-ottimizzazione-del-suo-assetto-organizzativo-e-produttivo-in-italia/","Electrolux Group — piano di riorganizzazione in Italia"],["https://www.cgiltreviso.it/categorie/fiom/comunicati/2662/crisi-electrolux-invariato-il-piano-aziendale-proclamate-8-ore-di-sciopero","Fiom CGIL Treviso — contenuti della mobilitazione e richieste sindacali"]]
},
{
"slug":"usa-divieti-importazioni-canada-alcol-latticini-moto-bombardier-settembre-2026","title":"USA-Canada, dai dazi ai divieti d’importazione: cosa cambia a settembre","excerpt":"Washington vieta l’ingresso di alcune merci canadesi e modifica i dazi nell’escalation commerciale con Ottawa. Le misure scatteranno in due fasi, il 15 e il 29 settembre.","published":"2026-09-09T18:10:00+02:00","category":"Mondo / Economia / Commercio","place":"Washington","key":"usa-canada-divieti-commerciali-ai-v312","alt":"Camion merci in coda a un valico tra Stati Uniti e Canada, scena editoriale contestuale fotorealistica generata con IA","points":[("5 proclami","gli atti firmati dal presidente USA"),("15 settembre","prime modifiche ai prodotti e ai dazi"),("29 settembre","entrata in vigore dei divieti")],"body":[
"Gli Stati Uniti hanno aperto una nuova fase della disputa commerciale con il Canada introducendo divieti d’importazione per alcune categorie di prodotti e modificando dazi già annunciati. Il presidente Donald Trump ha firmato cinque proclami basati sulla Section 338 del Tariff Act del 1930. Secondo la scheda della Casa Bianca, gli spostamenti di prodotti dentro o fuori dagli elenchi tariffari entreranno in vigore il 15 settembre 2026; i divieti veri e propri scatteranno il 29 settembre.",
"Le misure riguardano, fra l’altro, bevande alcoliche, prodotti lattiero-caseari, motocicli e alcune merci collegate ai veicoli. Washington ha inoltre aumentato la pressione su Bombardier e sugli acquisti pubblici di prodotti canadesi. Gli elenchi tecnici contenuti negli allegati sono più importanti delle etichette generali: non ogni bottiglia, alimento o veicolo canadese è necessariamente vietato, perché l’applicazione dipende dai codici doganali indicati.",
"L’Ufficio del rappresentante commerciale statunitense presenta l’azione come risposta alla ritorsione canadese e a trattamenti giudicati discriminatori verso esportazioni americane. Questa è la motivazione dell’amministrazione USA, non una conclusione condivisa fra i due Paesi. Per valutare la disputa occorre confrontare i provvedimenti canadesi richiamati, le regole dell’accordo USMCA e gli eventuali ricorsi nazionali o internazionali.",
"Un divieto d’importazione è più severo di un dazio. Il dazio consente alla merce di entrare pagando un costo aggiuntivo, che può essere assorbito o trasferito sul prezzo. Il divieto blocca l’ingresso della categoria indicata, salvo eccezioni. Le proclamazioni prevedono anche che, se un divieto venisse invalidato, possa tornare applicabile un dazio del 50% per alcune merci: è una clausola di salvaguardia che rende la misura resistente a contestazioni parziali.",
"La base giuridica scelta, la Section 338, attribuisce al presidente poteri contro Paesi ritenuti discriminatori verso il commercio americano. È uno strumento antico e poco utilizzato rispetto alle sezioni 232 e 301 diventate comuni nelle dispute recenti. Il suo impiego amplia il confronto oltre la sicurezza nazionale o le pratiche commerciali specifiche e potrebbe diventare oggetto di contenzioso sulla portata dei poteri presidenziali.",
"Per imprese e consumatori gli effetti non saranno immediati e uniformi. Importatori statunitensi dovranno identificare i codici coinvolti, gestire merci già in viaggio e cercare fornitori alternativi. Produttori canadesi potrebbero perdere accesso al mercato o deviare vendite verso altri Paesi. Prezzi e disponibilità negli Stati Uniti dipenderanno dalla facilità con cui l’offerta canadese può essere sostituita e dalla durata delle restrizioni.",
"La disputa può inoltre interrompere catene produttive integrate. Stati Uniti e Canada scambiano componenti che attraversano il confine più volte prima del prodotto finale, soprattutto nell’automotive. Una misura su un bene intermedio non colpisce soltanto l’esportatore: può aumentare costi e tempi per fabbriche americane che lo utilizzano. Per questo associazioni industriali e dogane dovranno chiarire rapidamente origine, classificazione e deroghe.",
"I prossimi indicatori sono la risposta formale di Ottawa, eventuali negoziati prima delle due scadenze, istruzioni della dogana statunitense e ricorsi. Le date del 15 e 29 settembre lasciano uno spazio limitato per modifiche o accordi. CurioMondo distinguerà gli annunci politici dall’applicazione effettiva ai confini e aggiornerà la pagina se cambieranno prodotti, aliquote o tempi."
],"sources":[["https://www.ustr.gov/about/policy-offices/press-office/press-releases/2026/september/ambassador-greer-issues-statement-president-trumps-response-canadas-continued-retaliation-against","USTR — 8 settembre 2026 — motivazione e base delle misure"],["https://www.whitehouse.gov/fact-sheets/2026/09/fact-sheet-president-donald-j-trump-responds-to-canadas-retaliation/","Casa Bianca — 8 settembre 2026 — categorie e calendario di entrata in vigore"],["https://www.whitehouse.gov/presidential-actions/2026/09/excluding-certain-canadian-alcoholic-beverages-from-importation-into-the-united-states-in-response-to-continued-discrimination-against-the-commerce-of-the-united-states-with-respect-to-alcoholic-bever/","Casa Bianca — proclamazione sui prodotti alcolici canadesi"],["https://www.reuters.com/podcasts/reuters-morning-bid/banned-usa-2026-09-09/","Reuters — 9 settembre 2026 — quadro economico della disputa"]]
},
{
"slug":"norvegia-funerali-stato-re-harald-v-oslo-9-settembre-2026","title":"La Norvegia saluta re Harald V con i funerali di Stato a Oslo","excerpt":"Il feretro è stato portato dal Palazzo reale alla cattedrale davanti a migliaia di persone. Il nuovo re Haakon VIII ha guidato la famiglia reale e le delegazioni straniere.","published":"2026-09-09T18:00:00+02:00","category":"Mondo / Europa / Norvegia","place":"Oslo","key":"re-harald-v-ritratto-neutrale-ai-v312","alt":"Ritratto editoriale neutrale isolato di re Harald V su sfondo blu scuro, somiglianza sintetica fotorealistica generata con IA per un contesto sensibile","points":[("89 anni","l’età del sovrano alla morte"),("35 anni","la durata del regno"),("9 settembre","il giorno dei funerali di Stato")],"sensitive":True,"body":[
"La Norvegia ha celebrato il 9 settembre 2026 i funerali di Stato di re Harald V, morto il 28 agosto a 89 anni dopo 35 anni sul trono. Il feretro ha lasciato il Palazzo reale a mezzogiorno ed è stato portato in processione fino alla cattedrale di Oslo, dove la cerimonia è iniziata alle 13. Migliaia di persone hanno seguito il corteo lungo Karl Johans gate, mentre rappresentanti istituzionali norvegesi e delegazioni reali e politiche straniere partecipavano al rito.",
"Il nuovo re Haakon VIII, la regina Mette-Marit, la regina Sonja e la principessa ereditaria Ingrid Alexandra hanno accompagnato il feretro insieme agli altri membri della famiglia reale. La presenza di capi di Stato, primi ministri e case regnanti europee ha dato alla cerimonia una dimensione internazionale, ma il programma ufficiale ha mantenuto al centro il rapporto fra Harald e la popolazione norvegese.",
"Le Forze armate hanno partecipato con guardie d’onore, salve e rappresentanze provenienti anche da Danimarca, Svezia e Regno Unito. Questi elementi non sono soltanto cerimoniali: in Norvegia il sovrano è formalmente comandante supremo delle forze armate, pur esercitando il ruolo nel quadro costituzionale e parlamentare. La partecipazione militare ha quindi ricordato una funzione istituzionale, non una scelta politica personale del re.",
"Harald era salito al trono nel 1991, succedendo a Olav V. Il suo regno ha attraversato trasformazioni profonde della società norvegese, dall’aumento dell’immigrazione al dibattito sull’identità nazionale e sui diritti. Il sovrano ha conservato una popolarità elevata adottando un linguaggio inclusivo e una presenza pubblica meno distante, mentre le decisioni di governo restavano responsabilità dell’esecutivo eletto.",
"La monarchia norvegese è costituzionale. Il re nomina formalmente il governo e svolge compiti rappresentativi, ma non dirige la politica quotidiana in autonomia. Gli atti sostanziali richiedono responsabilità ministeriale. La successione a Haakon VIII è avvenuta automaticamente alla morte del padre; la cerimonia funebre non trasferisce il potere, ma conclude il periodo pubblico di lutto e accompagna il passaggio simbolico fra due regni.",
"Il governo ha ricordato Harald come un sovrano capace di incontrare il Paese fuori dalle sole occasioni ufficiali. Nel discorso funebre, il primo ministro ha richiamato la gratitudine che il re esprimeva dopo le visite nelle comunità locali. Le parole commemorative descrivono la memoria istituzionale del sovrano e vanno distinte da una valutazione storica completa, che richiederà tempo e fonti più ampie.",
"Dopo il rito nella cattedrale, il feretro è stato trasferito verso la cappella reale della fortezza di Akershus, luogo di sepoltura di diversi membri della casa reale. Il dispositivo di sicurezza e la presenza di grandi folle hanno reso la giornata una delle operazioni pubbliche più complesse organizzate recentemente a Oslo. Le autorità avevano pubblicato in anticipo indicazioni per residenti, trasporti e media.",
"Con i funerali termina il lutto nazionale iniziato dopo la morte del 28 agosto, mentre prosegue il lutto di corte secondo le regole della Casa reale. Per la Norvegia comincia ora la fase ordinaria del regno di Haakon VIII: continuità costituzionale, definizione del nuovo calendario pubblico e costruzione di un rapporto personale con la popolazione."
],"sources":[["https://www.kongehuset.no/for-pressen/information-in-english/the-funeral-of-king-harald-v-en","Casa reale norvegese — programma ufficiale dei funerali"],["https://www.regjeringen.no/en/whats-new/the-prime-ministers-speech-at-the-funeral-of-king-harald-v/id3172089/","Governo norvegese — discorso del primo ministro"],["https://www.forsvaret.no/aktuelt-og-presse/aktuelt/gravferd-kong-harald","Forze armate norvegesi — partecipazione militare e cerimoniale"],["https://apnews.com/article/d34618a2c8d609e273c4c632199f9cc3","Associated Press — 9 settembre 2026 — cronaca e partecipazione pubblica"]]
}
]
src=(ROOT/'tools/build_v310.py').read_text(encoding='utf-8'); ns={'__file__':str(ROOT/'tools/build_v310.py')}; exec(src.split('def article(a):',1)[0],ns); exec('def article(a):'+src.split('def article(a):',1)[1].split('registry_path=',1)[0],ns); article=ns['article']
rp=ROOT/'assets/data/editorial-images-v210.json'; reg=json.loads(rp.read_text())
for a in ARTICLES:
 out=article(a).replace('8 settembre 2026','9 settembre 2026').replace('?v=310','?v=312')
 if a.get('sensitive'):
  out=out.replace('<figure class="article-image" data-ai-generated="true">','<figure class="article-image" data-ai-generated="true" data-synthetic-likeness="public-figure" data-sensitive-context="true" data-portrait-format="neutral-isolated">')
 (ROOT/'notizie'/f"{a['slug']}.html").write_text(out,encoding='utf-8')
 variants=[]
 for w in (480,800,1200):
  f=ROOT/'assets/images/editorial-auto'/f"{a['key']}-{w}.webp"; variants.append({'w':w,'src':f'/assets/images/editorial-auto/{f.name}','sha256':hashlib.sha256(f.read_bytes()).hexdigest(),'bytes':f.stat().st_size})
 reg['items'].insert(0,{'key':a['key'],'article':f"/notizie/{a['slug']}.html",'aiGenerated':True,'sensitiveContext':bool(a.get('sensitive')),'documentaryPhoto':False,'variants':variants,'alt':a['alt'],'disclosure':CAPTION,'portraitOnly':bool(a.get('sensitive')),'portraitFormat':'neutral-isolated' if a.get('sensitive') else 'contextual-editorial-scene','reenactedEvent':False})
reg['version']=VERSION; rp.write_text(json.dumps(reg,ensure_ascii=False,indent=2)+'\n')
runpy.run_path(str(ROOT/'tools/finalize_articles_20260906.py'),run_name='__main__')
for rel in ('assets/data/home-feed-v210.json','assets/data/search-index-v210.json','assets/data/editorial-images-v210.json'):
 p=ROOT/rel; d=json.loads(p.read_text()); d['version']=VERSION; p.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n')
runpy.run_path(str(ROOT/'tools/generate_category_pages.py'),run_name='__main__')
mp=ROOT/'curiomondo-site-manifest.json'; m=json.loads(mp.read_text()); m['site']['current_site_version']=VERSION; m['site']['site_version']=VERSION; mp.write_text(json.dumps(m,ensure_ascii=False,indent=2)+'\n')
print(json.dumps({'status':'ok','version':VERSION,'articles':[a['slug'] for a in ARTICLES]},ensure_ascii=False))
