#!/usr/bin/env python3
from pathlib import Path
import hashlib, json, runpy

ROOT=Path(__file__).resolve().parents[1]; VERSION=314
CAPTION="Illustrazione editoriale CurioMondo generata con IA per rappresentare questa notizia; non è una fotografia documentaria."
ARTICLES=[
{
"slug":"istat-economia-italiana-pil-industria-inflazione-luglio-agosto-2026","title":"Istat, l’industria italiana riparte a luglio ma l’inflazione accelera","excerpt":"La produzione cresce dello 0,7% sul mese, mentre il Pil del secondo trimestre avanza dello 0,2%. L’energia spinge l’inflazione IPCA al 3,2%.","published":"2026-09-10T10:15:00+02:00","category":"Italia / Economia","place":"Roma","key":"istat-economia-italia-ai-v314","alt":"Scena editoriale contestuale fotorealistica di un moderno impianto manifatturiero italiano in attività, generata con IA","points":[("+0,7%","la produzione industriale a luglio su giugno"),("+0,2%","il Pil italiano nel secondo trimestre"),("3,2%","l’inflazione IPCA annua stimata ad agosto")],"body":[
"L’economia italiana ha continuato a crescere nel secondo trimestre del 2026, ma con un equilibrio fragile tra la ripresa dell’industria e la nuova pressione dei prezzi energetici. Nella nota pubblicata il 10 settembre, l’Istat conferma un aumento del prodotto interno lordo dello 0,2% rispetto ai tre mesi precedenti, sostenuto da consumi privati e investimenti. La crescita acquisita per l’intero 2026 è pari allo 0,8%: significa che, se nei trimestri restanti il Pil non variasse, la media annuale risulterebbe già superiore dello 0,8% a quella del 2025.",
"Il segnale più recente arriva dalla produzione industriale. A luglio l’indice destagionalizzato è salito dello 0,7% rispetto a giugno, dopo le flessioni registrate nei due mesi precedenti. Il rimbalzo mensile non cancella però la debolezza del periodo: nella media maggio-luglio la produzione è diminuita dello 0,1% rispetto ai tre mesi precedenti e, al netto degli effetti di calendario, è rimasta invariata rispetto a luglio 2025. Il dato descrive quindi una riapertura dell’attività, non ancora una nuova fase espansiva consolidata.",
"La composizione aiuta a capire il risultato. Su base mensile aumentano i beni di consumo del 2,1%, i beni intermedi dello 0,5% e i beni strumentali dello 0,2%, mentre l’energia arretra dello 0,9%. Nel confronto annuale l’energia cresce invece del 6,4%, ma beni di consumo, intermedi e strumentali restano in calo. Tra i settori spiccano la fornitura di elettricità e gas, salita del 7,6% rispetto a un anno prima, e la farmaceutica, in aumento del 7,4%; le flessioni più ampie riguardano altre manifatture e riparazioni, chimica e apparecchiature elettriche.",
"Il mercato del lavoro offre un quadro più stabile. A luglio gli occupati sono 24 milioni e 370 mila, sostanzialmente invariati rispetto a giugno, mentre il tasso di disoccupazione scende al 5,8%. Dietro la media nazionale si muovono però gruppi diversi: l’occupazione aumenta tra gli uomini e tra i 35-49enni, ma diminuisce tra le donne e nelle altre classi d’età. Nel periodo 2021-2026 il miglioramento è stato più forte tra i 50-64enni, anche per l’invecchiamento della popolazione e le regole pensionistiche; i più giovani non hanno condiviso lo stesso progresso.",
"La parte più delicata riguarda i prezzi. Secondo la stima preliminare richiamata dall’Istat, ad agosto l’indice armonizzato dei prezzi al consumo è cresciuto del 3,2% su base annua, dal 2,9% di luglio. L’accelerazione è alimentata dai beni energetici e avviene mentre il conflitto tra Stati Uniti e Iran continua a disturbare le catene di approvvigionamento internazionali. L’indice armonizzato consente confronti coerenti tra i Paesi europei; non coincide perfettamente con l’indice nazionale usato per descrivere l’inflazione delle famiglie italiane.",
"Per famiglie e imprese, il punto non è soltanto se l’economia cresca, ma da dove provenga la crescita e quanto costi sostenerla. Investimenti e consumi hanno evitato una battuta d’arresto nel secondo trimestre, mentre l’industria mostra capacità di recupero dopo due mesi negativi. Se però energia e trasporti restano costosi, una parte del miglioramento può essere assorbita da margini più bassi per le aziende e minore potere d’acquisto per le famiglie. Il trasferimento non è automatico: dipende da contratti energetici, scorte, cambio e intensità energetica di ciascun settore.",
"I dati hanno inoltre limiti temporali differenti. Il Pil fotografa aprile-giugno, la produzione industriale riguarda luglio e l’inflazione di agosto è ancora preliminare. Metterli insieme serve a osservare la direzione generale, ma non trasforma mesi diversi in un’unica misurazione. Saranno decisivi i prossimi dati su ordini, vendite, salari reali e produzione di agosto per capire se il rimbalzo industriale riesce a durare e se l’aumento dei prezzi si estende oltre l’energia.",
"La lettura più prudente è dunque quella di un’economia ancora in espansione, con occupazione numericamente solida e manifattura in recupero, ma esposta allo shock esterno dei prezzi. La distinzione tra variazione mensile, media trimestrale e confronto annuale evita conclusioni opposte basate sullo stesso indice: il +0,7% segnala un miglioramento rispetto a giugno; il -0,1% trimestrale e lo zero tendenziale mostrano che il livello complessivo resta debole."
],"sources":[["https://www.istat.it/comunicato-stampa/nota-sullandamento-delleconomia-italiana-luglio-agosto-2026/","Istat — 10 settembre 2026 — quadro congiunturale, Pil, lavoro e inflazione"],["https://www.istat.it/comunicato-stampa/produzione-industriale-luglio-2026/","Istat — 10 settembre 2026 — indice industriale, raggruppamenti e settori"],["https://www.istat.it/comunicato-stampa/occupati-e-disoccupati-dati-provvisori-luglio-2026/","Istat — 1 settembre 2026 — occupati e tasso di disoccupazione"],["https://www.istat.it/comunicato-stampa/prezzi-al-consumo-dati-provvisori-agosto-2026/","Istat — 1 settembre 2026 — stima preliminare dei prezzi al consumo"]]
},
{
"slug":"nato-operazione-russa-cavi-sottomarini-artico-svalbard-2026","title":"Cavi artici, Reuters: alleati NATO hanno fermato un’esercitazione russa","excerpt":"Secondo fonti occidentali citate dall’agenzia, sommergibili russi simulavano l’uso di una tecnologia contro i collegamenti delle Svalbard. Nessun cavo è stato danneggiato.","published":"2026-09-10T08:10:00+02:00","category":"Mondo / Sicurezza / Tecnologia","place":"Svalbard","key":"cavi-sottomarini-artico-ai-v314","alt":"Scena editoriale contestuale fotorealistica delle acque artiche presso le Svalbard con navi distanti e un cavo sottomarino integro, generata con IA","points":[("0 danni","nessun cavo risulta colpito"),("2.700 m","la profondità massima dei collegamenti Svalbard-Norvegia"),("1.400 km","la lunghezza di ciascuno dei due cavi")],"body":[
"Un’operazione congiunta di Regno Unito, Norvegia e Stati Uniti avrebbe intercettato nella primavera del 2026 mezzi russi impegnati in un’esercitazione nelle acque artiche vicine alle Svalbard. La ricostruzione è stata pubblicata il 10 settembre da Reuters sulla base di due funzionari occidentali rimasti anonimi. Secondo le fonti, unità legate al GUGI, il direttorato russo per le attività in profondità, stavano simulando il dispiegamento di una tecnologia progettata per rendere inutilizzabili cavi sottomarini. Nessun cavo è stato danneggiato.",
"La parte nuova della notizia — il tipo di tecnologia, il luogo preciso e il coinvolgimento statunitense — non è stata resa pubblica in un documento tecnico consultabile. Va quindi attribuita a Reuters e alle sue fonti, non presentata come un fatto dimostrato da immagini o dati aperti. Sono invece ufficiali le dichiarazioni con cui Regno Unito e Norvegia avevano riconosciuto in aprile attività russe occulte nelle loro acque e la risposta del ministro norvegese della Difesa Tore Sandvik, che ha definito l’operazione congiunta un messaggio contro azioni clandestine sulle infrastrutture critiche. Mosca non ha commentato il singolo episodio e nega di preparare sabotaggi contro Paesi NATO.",
"Il bersaglio potenziale indicato nella ricostruzione è costituito da due collegamenti in fibra ottica lunghi circa 1.400 chilometri tra l’arcipelago e la Norvegia continentale. I cavi raggiungono profondità vicine a 2.700 metri e trasportano anche grandi quantità di dati raccolti dalla stazione satellitare SvalSat. L’importanza della rete non dipende soltanto dall’accesso a internet degli abitanti: le Svalbard ospitano una delle maggiori infrastrutture mondiali per ricevere dati dai satelliti in orbita polare, utilizzati per osservazione terrestre, meteorologia e ricerca.",
"Un cavo sottomarino è difficile da sorvegliare lungo tutta la sua estensione. Può essere posato sul fondale o interrato nei tratti più vulnerabili, ma attraversa aree remote dove distinguere un guasto, un incidente navale e un atto deliberato richiede tempo. L’interruzione fisica non è l’unico rischio: mappatura dei tracciati, avvicinamenti prolungati e attività di mezzi specializzati possono offrire informazioni utili in una crisi futura senza produrre immediatamente un danno visibile.",
"La NATO ha rafforzato la protezione delle infrastrutture sottomarine dal 2024, creando un centro dedicato presso il comando marittimo e una rete di cooperazione con governi e settore privato. Nel gennaio 2025 ha avviato Baltic Sentry dopo una serie di danneggiamenti a cavi e condotte nel Baltico; nel febbraio 2026 ha lanciato Arctic Sentry per coordinare le attività nazionali nell’Alto Nord. Queste missioni non provano la ricostruzione dell’episodio alle Svalbard, ma spiegano perché navi, sensori e sistemi senza equipaggio siano oggi concentrati sull’identificazione rapida di comportamenti anomali.",
"I cavi sono infrastrutture civili con valore strategico. Secondo la NATO, circa il 95% dei flussi globali di dati passa attraverso collegamenti sottomarini e ogni giorno viaggiano su queste reti trasferimenti finanziari per migliaia di miliardi di dollari. La cifra non significa che un singolo taglio possa spegnere internet: le reti sono progettate con percorsi ridondanti e il traffico può essere deviato. In località isolate, tuttavia, le alternative sono meno numerose e un’interruzione simultanea di più collegamenti può produrre conseguenze molto più gravi.",
"La geografia rende l’Artico particolarmente sensibile. I sottomarini russi basati nella penisola di Kola devono attraversare passaggi tra Svalbard, Norvegia e Jan Mayen per raggiungere l’Atlantico settentrionale. Nello stesso spazio si trovano rotte militari, installazioni satellitari e reti civili. La sovrapposizione aumenta il rischio di interpretare un’attività di addestramento come preparazione offensiva, ma rende anche necessario osservare capacità tecniche che potrebbero essere impiegate senza rivendicazione e con attribuzione difficile.",
"Per valutare eventuali sviluppi saranno importanti tre elementi: una conferma documentale dei governi coinvolti, dati pubblici su movimenti e tempi delle unità e informazioni tecniche verificabili sulla presunta tecnologia. Fino ad allora resta stabilito che nessun collegamento è stato colpito e che gli alleati hanno già reso noto un confronto con attività russe nell’Alto Nord; i dettagli operativi aggiuntivi rimangono una ricostruzione giornalistica autorevole, ma fondata in parte su fonti riservate."
],"sources":[["https://www.reuters.com/world/europe/nato-allies-foil-russian-subsea-cable-sabotage-plot-2026-09-10/","Reuters — 10 settembre 2026 — ricostruzione dell’operazione e dichiarazioni dei governi"],["https://www.nato.int/en/what-we-do/deterrence-and-defence/arctic-security","NATO — quadro ufficiale di Arctic Sentry e sicurezza dell’Alto Nord"],["https://www.nato.int/en/what-we-do/operations-and-missions/natos-maritime-activities","NATO — protezione delle infrastrutture sottomarine e Baltic Sentry"],["https://www.nato.int/en/what-we-do/deterrence-and-defence/resilience-civil-preparedness-and-article-3","NATO — dati sul ruolo globale dei cavi sottomarini"]]
}
]

src=(ROOT/'tools/build_v310.py').read_text(encoding='utf-8'); ns={'__file__':str(ROOT/'tools/build_v310.py')}; exec(src.split('def article(a):',1)[0],ns); exec('def article(a):'+src.split('def article(a):',1)[1].split('registry_path=',1)[0],ns); article=ns['article']
rp=ROOT/'assets/data/editorial-images-v210.json'; reg=json.loads(rp.read_text())
for a in ARTICLES:
 out=article(a).replace('8 settembre 2026','10 settembre 2026').replace('?v=310','?v=314')
 (ROOT/'notizie'/f"{a['slug']}.html").write_text(out,encoding='utf-8')
 variants=[]
 for w in (480,800,1200):
  f=ROOT/'assets/images/editorial-auto'/f"{a['key']}-{w}.webp"; variants.append({'w':w,'src':f'/assets/images/editorial-auto/{f.name}','sha256':hashlib.sha256(f.read_bytes()).hexdigest(),'bytes':f.stat().st_size})
 reg['items'].insert(0,{'key':a['key'],'article':f"/notizie/{a['slug']}.html",'aiGenerated':True,'sensitiveContext':False,'documentaryPhoto':False,'variants':variants,'alt':a['alt'],'disclosure':CAPTION,'portraitOnly':False,'portraitFormat':'contextual-editorial-scene','reenactedEvent':False})
reg['version']=VERSION; rp.write_text(json.dumps(reg,ensure_ascii=False,indent=2)+'\n')
runpy.run_path(str(ROOT/'tools/finalize_articles_20260906.py'),run_name='__main__')
for rel in ('assets/data/home-feed-v210.json','assets/data/search-index-v210.json','assets/data/editorial-images-v210.json'):
 p=ROOT/rel; d=json.loads(p.read_text()); d['version']=VERSION; p.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n')
runpy.run_path(str(ROOT/'tools/generate_category_pages.py'),run_name='__main__')
mp=ROOT/'curiomondo-site-manifest.json'; m=json.loads(mp.read_text()); m['site']['current_site_version']=VERSION; m['site']['site_version']=VERSION; mp.write_text(json.dumps(m,ensure_ascii=False,indent=2)+'\n')
print(json.dumps({'status':'ok','version':VERSION,'articles':[a['slug'] for a in ARTICLES]},ensure_ascii=False))
