#!/usr/bin/env python3
from pathlib import Path
import sys
from datetime import datetime
from zoneinfo import ZoneInfo
import json, hashlib
from PIL import Image

ROOT=Path(__file__).resolve().parents[1]
sys.path.insert(0,str(ROOT))
VERSION=354
ROME=ZoneInfo('Europe/Rome')
CAPTION='Illustrazione editoriale CurioMondo generata con IA per rappresentare questa notizia; non è una fotografia documentaria.'

ARTICLES=[
{
 'slug':'italia-centrali-idroelettriche-proprieta-nazionale-15-settembre-2026',
 'titolo':'Idroelettrico, il governo vuole difendere la proprietà nazionale delle centrali',
 'sommario':'Il ministro Pichetto Fratin propone rinnovi delle concessioni legati a investimenti degli operatori. Il dossier riguarda sicurezza energetica, concorrenza e controllo di infrastrutture strategiche.',
 'categoria':'Economia','luogo':'Italia','formato':'standard',
 'parole_chiave_titolo':['proprietà nazionale','centrali'],
 'dati_chiave':[{'icona':'◆','valore':'15 set','etichetta':'sviluppo pubblicato oggi'},{'icona':'●','valore':'Italia','etichetta':'controllo nazionale indicato dal ministro'},{'icona':'⬡','valore':'1','etichetta':'condizione: nuovi investimenti'}],
 'paragrafi':[
  'Il governo italiano vuole mantenere sotto controllo nazionale la proprietà delle centrali idroelettriche. Il ministro dell’Ambiente e della Sicurezza energetica Gilberto Pichetto Fratin ha indicato come strada il rinnovo delle concessioni agli operatori presenti, in cambio di nuovi investimenti sugli impianti.',
  'La posizione è stata riportata il 15 settembre da Reuters e ripresa da Askanews. Non equivale ancora a una nuova norma: definisce l’obiettivo politico con cui l’esecutivo intende affrontare un dossier che coinvolge concessioni regionali, concorrenza europea e sicurezza degli approvvigionamenti.',
  'Le grandi dighe e le centrali trasformano l’acqua accumulata in elettricità programmabile. A differenza di solare ed eolico, alcuni impianti possono aumentare rapidamente la produzione quando cresce la domanda. Il valore strategico non dipende quindi soltanto dall’energia annua generata, ma anche dalla capacità di stabilizzare la rete.',
  'Il rinnovo legato agli investimenti avrebbe due effetti da verificare. Potrebbe accelerare manutenzione, ammodernamento e aumento dell’efficienza, ma ridurrebbe lo spazio per nuove gare se applicato in modo esteso. Modalità, durata delle concessioni e compatibilità con le regole europee restano i punti decisivi non ancora definiti.',
  'La questione riguarda soprattutto le Regioni, titolari di molte concessioni, e gli operatori che già gestiscono gli impianti. Un eventuale intervento nazionale dovrà chiarire come valutare gli investimenti promessi, quali controlli applicare e che cosa accade quando un concessionario non rispetta gli impegni.',
  'Il contesto energetico rende la scelta più urgente. Le tensioni internazionali hanno riportato l’attenzione sulla dipendenza dalle importazioni e sulla protezione delle infrastrutture essenziali. L’idroelettrico offre produzione interna e capacità di accumulo, ma resta condizionato dalla disponibilità d’acqua e dagli effetti della siccità.',
  'Per cittadini e imprese non cambia nulla nell’immediato: tariffe, proprietà e gestione degli impianti restano quelle vigenti. Il passaggio da osservare sarà un atto normativo o amministrativo che trasformi l’indirizzo annunciato in criteri applicabili, con obblighi misurabili e tempi pubblici.'
 ],
 'fonti':[
  {'url':'https://www.reuters.com/business/energy/italy-aims-defend-national-ownership-hydro-power-plants-minister-says-2026-09-14/','descrizione':'Reuters — dichiarazioni del ministro Pichetto Fratin e obiettivo di controllo nazionale delle centrali.'},
  {'url':'https://askanews.it/2026/09/14/pichetto-difendere-proprieta-nazionale-delle-centrali-idroelettriche/','descrizione':'Askanews — proposta di rinnovo delle concessioni in cambio di investimenti.'},
  {'url':'https://www.mase.gov.it/portale','descrizione':'Ministero dell’Ambiente e della Sicurezza energetica — quadro istituzionale e competenze del dicastero.'},
  {'url':'https://energy.ec.europa.eu/topics/renewable-energy/hydropower_en','descrizione':'Commissione europea — ruolo dell’idroelettrico nel sistema energetico e nel quadro delle rinnovabili.'}
 ],
 'image_src':'/workspace/scratch/19c47b808cab/generated_images/exec-0418c425-f1dd-4dc0-9a88-a9b9aff0c136.png',
 'image_key':'italia-idroelettrico-proprieta-nazionale-ai-openai-v354',
 'image_alt':'Scena editoriale ordinaria ultrarealistica di una grande diga idroelettrica nelle Alpi italiane, con bacino e infrastrutture energetiche.'
},
{
 'slug':'houthi-attacchi-arabia-saudita-rotte-petrolio-15-settembre-2026',
 'titolo':'Houthi, nuovi attacchi sull’Arabia Saudita: cresce il rischio per le rotte del petrolio',
 'sommario':'Missili e droni hanno colpito obiettivi sauditi mentre il traffico attraverso Hormuz e Bab el-Mandeb si riduce. L’escalation unisce sicurezza civile, guerra in Yemen e forniture energetiche globali.',
 'categoria':'Mondo','luogo':'Arabia Saudita / Mar Rosso','formato':'standard',
 'parole_chiave_titolo':['nuovi attacchi','rotte del petrolio'],
 'dati_chiave':[{'icona':'◆','valore':'13','etichetta':'civili feriti riferiti'},{'icona':'●','valore':'4','etichetta':'navi merci passate da Hormuz lunedì'},{'icona':'⬡','valore':'125','etichetta':'transiti medi giornalieri prima della guerra'}],
 'paragrafi':[
  'Gli Houthi yemeniti hanno intensificato gli attacchi con missili e droni contro l’Arabia Saudita, colpendo anche l’area della base aerea di Khamis Mushait. Le autorità saudite hanno riferito tredici civili feriti. L’escalation arriva mentre diminuisce il traffico nelle principali rotte energetiche della regione.',
  'La Protezione civile saudita ha successivamente dichiarato cessato il pericolo immediato in sei città, tra cui Gedda, Abha, Jazan, AlUla, Taif e Yanbu. L’allerta resta significativa perché Yanbu è il terminale sul Mar Rosso dell’oleodotto Est-Ovest, già danneggiato da un attacco separato.',
  'Secondo Associated Press, la condotta potrebbe restare in gran parte fuori servizio per tre-cinque settimane. Prima del danno trasferiva tra 2,6 e 4 milioni di barili al giorno verso Yanbu. Il dato descrive la capacità sottratta al sistema, non una perdita automatica della stessa quantità di offerta mondiale.',
  'Anche lo Stretto di Hormuz mostra un calo eccezionale. I dati Kpler citati da Reuters indicano quattro transiti di navi per materie prime lunedì, contro dieci il giorno precedente e una media prebellica di circa 125. Nel Bab el-Mandeb i passaggi giornalieri sono scesi da 28 a 21.',
  'I due colli di bottiglia non sono intercambiabili. Hormuz collega i produttori del Golfo all’Oceano Indiano; Bab el-Mandeb apre la rotta dal Mar Rosso verso Suez. Se entrambi diventano meno accessibili, le navi devono attendere, cambiare percorso o sostenere costi assicurativi più elevati.',
  'La nuova pressione militare si sovrappone all’avanzata Houthi sulle isole Hanish e lungo la costa occidentale dello Yemen, già raccontata da CurioMondo. Lo sviluppo del 15 settembre è diverso: riguarda gli attacchi diretti sul territorio saudita e l’effetto simultaneo sulla sicurezza di porti, oleodotti e navigazione.',
  'Le responsabilità dei singoli episodi restano da distinguere. Riad attribuisce agli Houthi gli attacchi contro città e infrastrutture, mentre il danno all’oleodotto è stato ricondotto ad altre milizie sostenute dall’Iran. Le accuse militari non costituiscono da sole una verifica indipendente dell’origine di ogni vettore.',
  'Nelle prossime ore contano tre elementi: la riapertura effettiva dell’oleodotto, il numero reale di transiti negli stretti e l’eventuale ripresa dei colloqui tra Iran e Stati del Golfo. Finché questi dati non migliorano, il mercato continuerà a incorporare un rischio elevato sulle forniture.'
 ],
 'fonti':[
  {'url':'https://www.reuters.com/world/middle-east/houthis-strike-saudi-targets-anew-talks-over-strait-hormuz-stall-2026-09-15/','descrizione':'Reuters — attacchi Houthi, feriti e rinvio dei colloqui regionali.'},
  {'url':'https://www.reuters.com/world/middle-east/hormuz-traffic-dwindles-after-middle-east-attacks-intensify-2026-09-15/','descrizione':'Reuters — dati Kpler sui transiti attraverso Hormuz e Bab el-Mandeb.'},
  {'url':'https://apnews.com/article/8c18d82c109a8ea91347ce53c0096c53','descrizione':'Associated Press — danni e tempi stimati di fermo dell’oleodotto Est-Ovest.'},
  {'url':'https://my.gov.sa/en/news/2844160','descrizione':'Saudi Press Agency — posizione ufficiale saudita sugli attacchi a infrastrutture civili ed economiche.'},
  {'url':'https://www.ukmto.org/','descrizione':'UKMTO — quadro operativo degli incidenti e degli avvisi alla navigazione nella regione.'}
 ],
 'image_src':'/workspace/scratch/19c47b808cab/generated_images/exec-752dbc89-daad-44bf-8e68-fc1c31fae204.png',
 'image_key':'houthi-arabia-saudita-rotte-petrolio-ai-openai-v354',
 'image_alt':'Scena editoriale sensibile ultrarealistica e non documentaria nel Mar Rosso, con petroliera al largo e infrastrutture energetiche saudite sulla costa, senza attacchi o vittime visibili.',
 'sensitive':True
}
]

def variants(a):
    im=Image.open(a['image_src']).convert('RGB')
    ratio=3/2
    if im.width/im.height>ratio:
        w=round(im.height*ratio); x=(im.width-w)//2; im=im.crop((x,0,x+w,im.height))
    else:
        h=round(im.width/ratio); y=(im.height-h)//2; im=im.crop((0,y,im.width,y+h))
    out=ROOT/'assets/images/editorial-auto'; out.mkdir(parents=True,exist_ok=True)
    vs=[]
    for w in (480,800,1200):
        p=out/f"{a['image_key']}-{w}.webp"; im.resize((w,round(w*2/3)),Image.Resampling.LANCZOS).save(p,'WEBP',quality=88,method=6)
        vs.append({'w':w,'src':'/assets/images/editorial-auto/'+p.name,'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'bytes':p.stat().st_size})
    return vs

def publish_news():
    from automation.newsroom.site import write_article,register_image,sync_surfaces
    built=[]
    for a in ARTICLES:
        meta={'key':a['image_key'],'aiGenerated':True,'documentaryPhoto':False,'variants':variants(a),'alt':a['image_alt'],'disclosure':CAPTION,'sensitiveContext':a.get('sensitive',False)}
        write_article(a,meta,VERSION); register_image(meta,a['slug'],VERSION); built.append(a)
    sync_surfaces(built,'/notizie/'+ARTICLES[1]['slug']+'.html',VERSION)

def publish_question():
    from tools.daily_question_auto import render_question_page,render_book_page,update_home,update_archive,update_search,update_sitemap,update_feed
    q='Se potessi conoscere in anticipo il prezzo reale di ogni scelta, avresti ancora il coraggio di scegliere?'
    slug='se-potessi-conoscere-in-anticipo-il-prezzo-reale-di-ogni-scelta-avresti-ancora-il-coraggio-di-scegliere'
    date='2026-09-15'; label='15 settembre 2026'; qurl=f'/domanda-del-giorno/{slug}/'; burl=f'/biblioteca/vita-relazioni/domande-per-conoscersi/{slug}/'
    answer=[
      'Ogni scelta ha un prezzo, ma quasi mai lo conosciamo interamente quando dobbiamo decidere. Vediamo il tempo da investire, il denaro da spendere o la fatica immediata; restano nascosti i giorni di dubbio, le occasioni che non potremo più prendere e la persona che diventeremo seguendo una strada invece di un’altra.',
      'Se il conto fosse visibile in anticipo, alcune decisioni sembrerebbero più semplici. Eviteremmo promesse che non possiamo mantenere e progetti costruiti soltanto sull’entusiasmo. Eppure una conoscenza completa potrebbe toglierci proprio ciò che rende possibile scegliere: la capacità di muoverci senza possedere ogni risposta.',
      'Il coraggio non consiste nel fingere che il costo non esista. Significa guardare ciò che sappiamo, distinguere un sacrificio sostenibile da un danno inutile e accettare che una parte del futuro resterà fuori dal nostro controllo. La prudenza protegge; la pretesa di certezza, invece, può trasformarsi in immobilità.',
      'Conoscere il prezzo reale includerebbe anche quello del non scegliere. Restare in una situazione consuma tempo, restringe possibilità e ci abitua a chiamare equilibrio ciò che forse è soltanto paura. L’assenza di un gesto non è gratuita: produce conseguenze più silenziose, ma non per questo meno concrete.',
      'Forse sceglieremmo ancora, ma con meno illusioni e più responsabilità. Non perché il risultato sia garantito, bensì perché alcuni valori meritano un rischio misurato: dire la verità, difendere una relazione sana, lasciare ciò che ci spegne, iniziare un lavoro che riconosciamo come nostro.',
      'Oggi non possiamo vedere il conto completo. Possiamo però domandarci quale prezzo siamo disposti a pagare, quale non vogliamo imporre agli altri e quale stiamo già pagando per restare fermi. Se la risposta fosse davanti a te, quale scelta continuerebbe a sembrarti degna del suo costo?'
    ]
    themes=[
      ('Il prezzo che vediamo','Prima di scegliere tendiamo a contare ciò che è immediato: ore, denaro, fatica, rinunce visibili. È un calcolo necessario, ma parziale. Una decisione cambia anche l’attenzione disponibile, le relazioni che possiamo coltivare e il modo in cui immaginiamo il futuro. Il costo reale non vive in una sola cifra: si distribuisce nella vita quotidiana e spesso emerge soltanto quando la novità è finita.','Un nuovo lavoro può offrire uno stipendio migliore e chiedere trasferimenti, reperibilità o distanza. Una relazione può dare vicinanza e richiedere compromessi. Studiare apre possibilità e sottrae tempo ad altro. Nessuno di questi scambi è automaticamente giusto o sbagliato; diventa comprensibile quando smettiamo di considerare soltanto la voce più evidente.','Anche i vantaggi hanno tempi diversi. Alcuni arrivano subito e svaniscono presto; altri maturano lentamente. Conoscere il prezzo significa quindi osservare durata, reversibilità e persone coinvolte. Una rinuncia breve per costruire una competenza non è uguale a un sacrificio indefinito che consuma salute o dignità.','Prima di dire sì, può essere utile descrivere una settimana ordinaria dopo la scelta. Non il giorno ideale, ma un martedì stanco: orari, spostamenti, responsabilità, spazio mentale. La scena concreta mostra costi che l’entusiasmo nasconde e benefici che la paura sottovaluta.'),
      ('Il costo del futuro immaginato','La mente tratta il futuro come una storia che può controllare. Costruiamo scenari, assegniamo probabilità e poi reagiamo emotivamente a immagini che non sono ancora accadute. Questa capacità protegge dai rischi, ma può produrre un conto gonfiato da eventi possibili presentati come certi.','Se conoscessimo davvero ogni conseguenza, non avremmo più bisogno di immaginare. Ma perderemmo anche la possibilità di sorprenderci, imparare e cambiare direzione. Molte scelte diventano buone non perché il piano iniziale fosse perfetto, bensì perché abbiamo corretto il percorso mentre nuove informazioni diventavano disponibili.','Una previsione utile distingue tra pericolo e disagio. Perdere una somma essenziale, compromettere la salute o danneggiare qualcuno sono rischi che chiedono protezioni forti. Sentirsi inesperti, ricevere un rifiuto o attraversare un periodo scomodo può essere il prezzo normale di un cambiamento, non la prova che esso sia sbagliato.','Il futuro non va ignorato né adorato. Va interrogato con domande verificabili: qual è lo scenario peggiore plausibile, come potrei limitarne l’impatto, quali segnali mi farebbero fermare? Così l’incertezza smette di essere nebbia indistinta e diventa uno spazio con confini.'),
      ('Ciò che paghiamo restando fermi','Non scegliere sembra spesso l’opzione neutrale. In realtà conserva la situazione presente e lascia che il tempo decida al posto nostro. Un lavoro inadatto continua a occupare giornate; una conversazione evitata aumenta la distanza; un progetto rinviato perde occasioni. Il costo dell’immobilità è meno rumoroso perché non arriva con una data di acquisto.','La familiarità rende tollerabile ciò che, visto dall’esterno, apparirebbe troppo caro. Ci adattiamo a piccole rinunce ripetute e smettiamo di sommarle. È per questo che una decisione può spaventare più della permanenza, anche quando restare richiede ogni giorno energia, silenzio o una parte della nostra autonomia.','Misurare il non scegliere non significa obbligarsi al cambiamento. Serve a rendere onesto il confronto. Da una parte ci sono rischi e sacrifici dell’azione; dall’altra conseguenze della continuità. Solo quando entrambe le colonne sono visibili possiamo capire se la prudenza ci protegge o mantiene una perdita già in corso.','Una domanda semplice aiuta: se nulla cambiasse per dodici mesi, che cosa migliorerebbe e che cosa peggiorerebbe? La risposta non predice il futuro, ma rivela la direzione implicita della scelta presente. Anche aspettare può essere una decisione valida, purché abbia un motivo e una scadenza.'),
      ('Valori, limiti e responsabilità','Il coraggio senza limiti può diventare imprudenza. Conoscere il prezzo di una scelta richiede anche stabilire ciò che non siamo disposti a sacrificare: sicurezza essenziale, rispetto, legalità, salute, responsabilità verso persone dipendenti da noi. Un confine chiaro non riduce la libertà; impedisce che un desiderio consumi tutto il resto.','I valori aiutano quando due opzioni sono entrambe imperfette. Non eliminano la perdita, ma indicano quale perdita è coerente con la persona che vogliamo essere. Scegliere tempo invece di prestigio, stabilità invece di velocità o verità invece di approvazione comporta sempre una rinuncia. La differenza sta nel riconoscere a che cosa stiamo dando priorità.','La responsabilità comprende gli altri. Una decisione personale può modificare carichi di cura, reddito familiare o fiducia. Coinvolgere chi subirà conseguenze non significa cedere il comando della propria vita; significa evitare di chiamare libertà ciò che scarica costi invisibili su qualcuno che non ha potuto partecipare.','Quando gli interessi entrano in conflitto, servono parole precise: che cosa cambierà, per quanto tempo, quali impegni restano, quali aiuti sono possibili. Le promesse generiche tranquillizzano per un momento. Un accordo concreto rende il prezzo condiviso comprensibile e permette a tutti di decidere con maggiore dignità.'),
      ('Decisioni reversibili e prove limitate','Non tutte le scelte devono essere definitive. Una prova circoscritta permette di raccogliere informazioni senza esporsi subito al costo massimo. Si può testare un nuovo ritmo di lavoro, dedicare alcune settimane a un progetto, visitare una città prima di trasferirsi o fissare un periodo di verifica in una collaborazione.','La reversibilità non è vigliaccheria. È una proprietà della decisione che riduce l’errore quando l’incertezza è alta. Bisogna però definirla prima: durata della prova, risorse massime, indicatori da osservare e condizioni di uscita. Senza questi limiti, ciò che nasce come esperimento rischia di diventare permanenza per inerzia.','Alcune scelte non consentono prove complete, ma possono essere scomposte. Prima di lasciare un impiego si può costruire un fondo, aggiornare competenze e parlare con chi lavora nel settore. Prima di una spesa rilevante si possono confrontare alternative e costi ricorrenti. Ogni passaggio sostituisce una parte dell’ansia con dati reali.','Il vantaggio più importante di una prova è vedere noi stessi dentro la situazione. Le preferenze immaginate non sempre coincidono con quelle vissute. Un’esperienza limitata rivela energia, resistenza, curiosità e fatica meglio di molte ore trascorse a discutere con una versione teorica del futuro.'),
      ('Perdita, rimpianto e identità','Ogni scelta chiude almeno temporaneamente altre strade. Questa perdita può far male anche quando la decisione è corretta. Idealizzare l’alternativa scartata rende il prezzo più pesante, perché confrontiamo la realtà complessa con una possibilità rimasta perfetta proprio perché non è mai stata vissuta.','Il rimpianto non dimostra sempre che abbiamo sbagliato. Può indicare che qualcosa aveva valore e non poteva essere conservato insieme al resto. Una scelta matura non cancella l’affetto per ciò che lasciamo; accetta che la vita abbia limiti e che nessuna combinazione permetta di possedere tutte le versioni di noi stessi.','L’identità entra nel conto quando diciamo: io sono fatto così. Le decisioni passate diventano prove che usiamo per descriverci, ma non sono contratti eterni. Cambiare direzione può sembrare un tradimento della persona che eravamo. A volte è invece il modo più onesto di riconoscere ciò che abbiamo imparato.','Per valutare il rimpianto futuro è utile chiedersi quale omissione peserebbe di più: aver tentato con misura o non aver mai verificato una possibilità importante. La risposta non ordina che cosa fare. Aiuta a capire quale tipo di perdita siamo più capaci di integrare nella nostra storia.'),
      ('Scegliere con informazioni incomplete','Le decisioni migliori non nascono da informazioni infinite, ma da informazioni sufficienti. Continuare a cercare può migliorare il giudizio fino a un certo punto; oltre quella soglia produce dettagli che non cambiano l’esito e rimanda l’assunzione di responsabilità. Stabilire in anticipo che cosa serve sapere protegge da questa ricerca senza fine.','Un criterio pratico separa fatti, ipotesi e paure. I fatti hanno una fonte controllabile; le ipotesi descrivono conseguenze plausibili; le paure raccontano ciò che temiamo, anche senza prove. Tutte e tre meritano ascolto, ma non lo stesso peso. Confonderle rende enorme ogni rischio e invisibile ogni opportunità.','È utile anche cercare una persona che non abbia interesse a spingerci verso una risposta. Non qualcuno che scelga al posto nostro, ma qualcuno capace di vedere contraddizioni, fare domande scomode e distinguere il desiderio dalla fretta. Un confronto buono amplia lo sguardo senza sostituire la nostra responsabilità.','Alla fine arriva un momento in cui decidere significa accettare un margine di errore. Possiamo preparare un piano di recupero, conservare risorse e fissare una verifica. Non possiamo trasformare il futuro in una prova già corretta. Il coraggio comincia quando la preparazione ha fatto il suo lavoro e smette di essere un rifugio.'),
      ('Un patto con il presente','Conoscere il prezzo reale di ogni scelta cambierebbe forse il nostro modo di vivere, ma non eliminerebbe il bisogno di attribuire valore. Sapere che qualcosa costa molto non dice se ne valga la pena. Il significato nasce dal rapporto tra quel costo, ciò che protegge e la vita che rende possibile.','Un patto con il presente può contenere tre impegni: non minimizzare i rischi, non inventarne di nuovi per paura e non ignorare il prezzo del rinvio. È un equilibrio meno spettacolare dell’impulso e meno rassicurante della certezza, ma permette di muoversi senza mentire a se stessi.','Dopo la decisione serve una data per rivederla. Alcuni effetti compaiono presto, altri chiedono tempo. Controllare troppo spesso trasforma ogni giornata difficile in un verdetto; non controllare mai rende la coerenza un alibi. Una verifica stabilita prima aiuta a distinguere l’adattamento normale da un costo diventato insostenibile.','La domanda iniziale resta aperta: avremmo ancora il coraggio di scegliere se vedessimo tutto il prezzo? Forse sì, ma chiameremmo coraggio qualcosa di più sobrio. Non l’assenza di paura, bensì la disponibilità a pagare un costo compreso, limitato dove possibile e coerente con ciò che oggi riconosciamo come essenziale.')
    ]
    supplements=[
      'Un esercizio utile consiste nel separare il costo certo da quello probabile e da quello soltanto temuto. Il primo richiede risorse già identificabili; il secondo può essere stimato attraverso esperienze comparabili; il terzo parla soprattutto della nostra vulnerabilità. Scrivere queste tre categorie impedisce a un timore remoto di pesare quanto una conseguenza inevitabile. Permette anche di scoprire il problema opposto: rischi concreti che l’entusiasmo aveva reso quasi invisibili. Il foglio non sceglie al posto nostro, ma restituisce proporzioni a ciò che nella mente tende a mescolarsi.',
      'Le conseguenze indirette meritano la stessa attenzione. Una scelta può cambiare il sonno, la disponibilità verso le persone vicine, il tempo dedicato al corpo e la qualità delle decisioni successive. Questi effetti non compaiono nei preventivi, eppure diventano spesso il prezzo più duraturo. Per riconoscerli possiamo osservare chi ha già attraversato una situazione simile, senza trasformare la sua esperienza in una profezia. Le storie altrui offrono domande migliori, non risposte automatiche: mostrano variabili che il nostro scenario personale non aveva ancora considerato.',
      'L’attesa ha senso quando produce qualcosa: nuove informazioni, risorse, competenze o condizioni più sicure. Diventa costosa quando ripete lo stesso giro mentale senza modificare la decisione possibile. Stabilire che cosa deve accadere prima di scegliere rende l’attesa verificabile. Se attendiamo un documento, una cifra o una conversazione, possiamo fissare una data. Se attendiamo di non provare più paura, la condizione potrebbe non arrivare mai. In quel caso il tempo non sta preparando la scelta; sta soltanto allontanando il momento in cui dovremo assumerla.',
      'Esiste inoltre un limite morale al calcolo. Non tutto ciò che ha un costo può essere trattato come merce scambiabile. La fiducia di una persona, la salute, la sicurezza e il rispetto non entrano facilmente nella stessa bilancia di prestigio o guadagno. Quando una decisione tocca questi beni, la domanda non è soltanto quanto siamo disposti a pagare, ma quale perdita renderebbe il risultato incompatibile con i nostri principi. Dichiarare prima questi confini impedisce di spostarli poco alla volta quando siamo già coinvolti e desideriamo giustificare il percorso intrapreso.',
      'Una prova limitata funziona soltanto se raccoglie segnali pertinenti. Provare un’attività nel momento più facile può nasconderne la routine; provarla nel momento peggiore può farci scartare qualcosa per ragioni eccezionali. Serve un campione abbastanza normale e una piccola scheda di osservazione: energia prima e dopo, costi effettivi, difficoltà ripetute, aspetti che generano interesse. Alla fine non chiediamoci soltanto se è andata bene, ma che cosa abbiamo imparato e quale ipotesi è stata smentita. L’esperimento vale per la qualità delle informazioni che restituisce.',
      'Dopo una scelta, la mente tende a cercare prove che confermino la decisione oppure, nei giorni difficili, che la condannino. Entrambi gli impulsi alterano il conto. Accettare un periodo di adattamento significa non trasformare ogni ostacolo in un errore, ma anche non usare la fatica iniziale per giustificare all’infinito un danno. Aiuta conservare i criteri scritti prima: risultati attesi, limiti, data di verifica. In questo modo valutiamo il percorso rispetto alle ragioni originali, non soltanto rispetto all’umore del giorno o al bisogno di avere avuto ragione.',
      'Le informazioni sufficienti cambiano secondo la reversibilità. Per una scelta facile da correggere può bastare una verifica breve; per una decisione che coinvolge debiti, salute o trasferimenti familiari la soglia deve essere più alta. Questa differenza evita due errori opposti: studiare per mesi una porta che possiamo riaprire domani e affrontare con leggerezza una conseguenza difficile da annullare. La quantità di ricerca non misura la serietà della persona. Conta la corrispondenza tra profondità del controllo, grandezza del rischio e possibilità concreta di recuperare da un esito sfavorevole.',
      'Il presente offre infine un criterio che nessuna previsione può sostituire: la possibilità di compiere il prossimo gesto onesto. Può essere chiedere un dato, ammettere un dubbio, mettere da parte una somma, definire un confine o rinviare consapevolmente fino a una data precisa. Un gesto simile non risolve l’intera scelta, ma impedisce che essa rimanga un oggetto astratto. Il coraggio diventa allora una sequenza di responsabilità abbastanza piccole da essere vissute. Non promette che il prezzo sarà lieve; promette che non lo pagheremo distrattamente, senza sapere che cosa stiamo scegliendo di proteggere. E questo cambia il modo di procedere.'
    ]
    package={'excerpt':'Una riflessione sul costo visibile e invisibile delle decisioni, sul prezzo dell’immobilità e sul coraggio di scegliere senza possedere il futuro.','answer_paragraphs':answer,'book_title':'Il prezzo delle strade possibili','book_deck':'Un eBook per osservare costi, rinunce, rischi e valori prima di una scelta importante, senza aspettare una certezza impossibile.','book_pages':[{'title':t,'paragraphs':list(ps)+[supplements[i]]} for i,(t,*ps) in enumerate(themes)]}
    (ROOT/f'domanda-del-giorno/{slug}').mkdir(parents=True,exist_ok=True); (ROOT/f'biblioteca/vita-relazioni/domande-per-conoscersi/{slug}').mkdir(parents=True,exist_ok=True)
    (ROOT/f'domanda-del-giorno/{slug}/index.html').write_text(render_question_page(q,package,slug,date,label,burl),encoding='utf-8')
    (ROOT/f'biblioteca/vita-relazioni/domande-per-conoscersi/{slug}/index.html').write_text(render_book_page(qurl,burl,package),encoding='utf-8')
    dt=datetime(2026,9,15,7,0,tzinfo=ROME); update_home(slug,dt,label); update_archive(q,package,slug,label); update_search(q,package,qurl,burl); update_sitemap(date,qurl,burl); update_feed(dt,q,package,qurl)
    m=json.loads((ROOT/'curiomondo-site-manifest.json').read_text()); d=m['daily_state']; d['last_question_date']=date; d['last_question_slug']=slug; d['current_question_source_number']=1002; used=d.setdefault('used_question_source_numbers',[]); 1002 not in used and used.append(1002); (ROOT/'curiomondo-site-manifest.json').write_text(json.dumps(m,ensure_ascii=False,indent=2)+'\n')

if __name__=='__main__':
    publish_question(); publish_news()
