from pathlib import Path
from html import escape
import json
from lxml import html, etree

ROOT = Path(__file__).resolve().parents[1]
VERSION = 294
OLD = "chi-siamo-nei-cinque-minuti-prima-di-addormentarci-quando-cadono-le-maschere-utili"
SLUG = "cosa-faremmo-se-il-tempo-tornasse-indietro-di-dieci-anni-sapendo-cio-che-sappiamo-ora"
QUESTION = "Cosa faremmo se il tempo tornasse indietro di dieci anni, sapendo ciò che sappiamo ora?"
DECK = "Una riflessione su rimpianto, consapevolezza e sul modo in cui il presente cambia ciò che crediamo avremmo scelto nel passato."
BOOK_TITLE = "Dieci anni indietro, con gli occhi di oggi"
BOOK_DECK = "Un eBook sul desiderio di tornare indietro, sul senno di poi e su ciò che la conoscenza presente può ancora cambiare."
QURL = f"/domanda-del-giorno/{SLUG}/"
BURL = f"/biblioteca/vita-relazioni/domande-per-conoscersi/{SLUG}/"

question_paragraphs = [
    "Quando immaginiamo di tornare indietro di dieci anni, raramente desideriamo davvero di rivivere ogni giornata. Vorremmo portare con noi una conoscenza precisa: sapere quale persona non inseguire, quale occasione non rimandare, quale paura attraversare prima che diventi un'abitudine. Il viaggio nel tempo che immaginiamo non riguarda il calendario. Riguarda il desiderio di essere stati, allora, la persona che siamo diventati soltanto dopo.",
    "C'è però un inganno gentile in questa fantasia. Ci giudichiamo con informazioni che la nostra versione di dieci anni fa non possedeva. Oggi conosciamo l'esito di alcune scelte, la tenuta di certe relazioni e il prezzo di rinunce che allora sembravano temporanee. Da questa posizione privilegiata, il passato appare pieno di segnali evidenti. Ma molti di quei segnali sono diventati leggibili soltanto perché abbiamo attraversato ciò che è accaduto.",
    "Se tornassimo davvero indietro conservando tutto ciò che sappiamo, cambieremmo probabilmente alcune decisioni concrete. Diremmo prima una verità, proteggeremmo meglio il nostro tempo, inizieremmo qualcosa senza aspettare di sentirci pronti. Ma perderemmo anche incontri, capacità e sensibilità nate proprio dagli errori che vorremmo cancellare. Non esiste una versione del passato in cui togliamo soltanto il dolore e conserviamo intatto tutto ciò che quel dolore ha trasformato.",
    "La domanda diventa più utile quando smette di essere un processo contro chi eravamo. Quella persona decideva con meno esperienza, ma anche con energie, vincoli e bisogni diversi. Forse non era ingenua: stava facendo il meglio che poteva con una mappa incompleta. Guardarla con comprensione non significa assolvere ogni scelta. Significa riconoscere che la lucidità acquistata dopo non può essere usata come prova che avremmo dovuto possederla prima.",
    "Il punto più vivo della fantasia è ciò che rivela sul presente. Se tornando indietro avremmo iniziato a prenderci cura del corpo, possiamo cominciare oggi. Se avremmo detto a qualcuno quanto contava, forse esiste ancora una persona a cui dirlo. Se avremmo lasciato prima una strada che non ci apparteneva, possiamo chiederci quale strada stiamo continuando adesso soltanto per non ammettere di aver cambiato idea.",
    "Dieci anni non tornano, ma la conoscenza che abbiamo conquistato è già qui. Il passato immaginato ci mostra quali lezioni diciamo di avere imparato; il presente verifica se siamo davvero disposti a viverle. Non possiamo consegnare a chi eravamo la saggezza di oggi. Possiamo però evitare che, fra altri dieci anni, la persona che saremo debba farci esattamente la stessa domanda.",
]

book_pages = [
    (None, [
        "La domanda di oggi è: cosa faremmo se il tempo tornasse indietro di dieci anni, sapendo ciò che sappiamo ora? È una fantasia comune perché promette una combinazione impossibile: l'energia e le possibilità di allora insieme alla conoscenza conquistata dopo. Immaginiamo di poter correggere la traiettoria senza perdere ciò che il viaggio ci ha insegnato.",
        "Questo eBook non prova a compilare l'elenco delle decisioni da rifare. Esplora qualcosa di più utile: perché il passato sembra così chiaro soltanto dopo, quali rimpianti contengono ancora un'indicazione concreta e come trasformare il senno di poi in una responsabilità verso il presente.",
        "Il percorso attraversa memoria, identità, relazioni e scelte. Non chiede di perdonare tutto né di convincersi che ogni dolore fosse necessario. Chiede di distinguere ciò che non potevamo sapere da ciò che oggi continuiamo a evitare, pur sapendolo."],),
    ("Il privilegio di conoscere il finale", [
        "Guardare il passato assomiglia a rileggere un romanzo dopo averne scoperto il finale. Frasi che alla prima lettura sembravano secondarie diventano segnali; esitazioni comuni appaiono svolte decisive. La memoria ricostruisce una trama ordinata, ma la persona che viveva quei giorni non vedeva capitoli: vedeva soltanto il presente, con informazioni incomplete e conseguenze ancora aperte.",
        "Il senno di poi produce una sensazione di evidenza. Pensiamo: era chiaro che quella relazione non avrebbe funzionato, che quel lavoro ci stava consumando, che quell'occasione meritava coraggio. In realtà oggi selezioniamo gli indizi coerenti con l'esito e dimentichiamo quelli che allora sostenevano possibilità diverse. Non è disonestà volontaria; è il modo con cui la mente trasforma una storia complessa in qualcosa che possa essere raccontato.",
        "Riconoscere questo privilegio non cancella la responsabilità. Alcuni segnali erano davvero visibili e forse li abbiamo ignorati. Ma permette un giudizio più preciso: non chiedere se oggi la scelta appare sbagliata, bensì quali elementi erano ragionevolmente disponibili allora, quali pressioni agivano e quale margine reale avevamo.",
        "La domanda più equa verso il nostro passato è: con ciò che sapevo, con le risorse che avevo e con la paura che provavo, quale alternativa riuscivo davvero a vedere? A volte la risposta farà emergere un errore. Altre volte mostrerà che pretendiamo dalla persona di allora una lucidità costruita proprio attraverso quell'esperienza."],),
    (None, [
        "Dieci anni sono abbastanza lunghi da farci sembrare estranea una parte di noi e abbastanza brevi da lasciarne intatti alcuni desideri. In quel periodo possono cambiare lavoro, città, corpo, relazioni e idee; può cambiare persino il significato che diamo alla parola successo. Per questo il viaggio immaginario non riporterebbe nel passato la stessa persona con qualche informazione in più. Porterebbe un'identità diversa dentro una vita progettata per qualcun altro.",
        "Ciò che oggi sappiamo non è un file neutro da trasferire. È legato a perdite, incontri, responsabilità e affetti. Sapere che una relazione finirà significa anche conoscere la persona che saremo dopo la fine. Sapere che un rischio professionale darà frutti significa portare nel passato una sicurezza che allora non poteva esistere. Le decisioni cambierebbero non soltanto per l'informazione, ma perché sarebbe cambiato chi decide.",
        "Questa osservazione protegge da una fantasia crudele: l'idea che sarebbe bastata una frase giusta, pronunciata nel momento giusto, per ottenere una vita perfettamente ordinata. Ogni correzione avrebbe generato conseguenze nuove e invisibili. Salvarci da un errore avrebbe potuto allontanarci da un incontro; evitare una perdita avrebbe potuto conservare una situazione che, più avanti, ci avrebbe limitato in un altro modo.",
        "Non possiamo sapere quale linea temporale sarebbe stata migliore. Possiamo però capire che cosa desideriamo salvare quando immaginiamo di riscriverla: dignità, tempo, salute, presenza, coraggio. Sono questi valori, più delle scene precise, a meritare di essere portati nel presente."],),
    ("Rimpianto, rimorso e nostalgia", [
        "Non tutti i desideri di tornare indietro hanno la stessa origine. Il rimpianto riguarda spesso ciò che non abbiamo fatto: una parola trattenuta, una possibilità non esplorata, un talento lasciato senza spazio. Il rimorso riguarda invece un'azione di cui riconosciamo il danno e può chiedere riparazione. La nostalgia non vuole necessariamente cambiare nulla: desidera ritrovare una sensazione di appartenenza, semplicità o apertura che associamo a un periodo perduto.",
        "Confondere queste esperienze porta a soluzioni sbagliate. Un rimpianto non si scioglie sempre chiedendo scusa; può richiedere un gesto nuovo. Il rimorso non si risolve dicendo che eravamo giovani; chiede di riconoscere la conseguenza e, quando possibile, rimediare. La nostalgia non ordina di ricostruire il passato: segnala una qualità che manca al presente.",
        "Possiamo esaminare una scena che ritorna e chiederci che cosa voglia davvero. Se penso continuamente a un viaggio mai fatto, forse non desidero quel luogo preciso ma una vita con più esplorazione. Se penso a un'amicizia perduta, potrei desiderare quella persona oppure il modo in cui con lei mi sentivo visto. Se penso a una scelta che ha ferito qualcuno, il bisogno potrebbe essere smettere di proteggere la mia immagine e assumermi una responsabilità.",
        "Dare un nome accurato al sentimento riduce il potere indistinto del passato. Non lo rende piccolo: lo rende praticabile. Una memoria può restare dolorosa e, nello stesso tempo, smettere di essere una porta chiusa quando comprendiamo quale azione presente le corrisponde."],),
    (None, [
        "Esiste una differenza importante tra cancellare un errore e impedirgli di ripetersi. La prima possibilità appartiene alla fantasia; la seconda è una forma concreta di libertà. Molti rimpianti diventano sterili perché li usiamo per contemplare una versione ideale di noi stessi invece di modificare il comportamento che li ha prodotti.",
        "Se dieci anni fa non abbiamo difeso un confine, la lezione non è soltanto che avremmo dovuto parlare. È imparare a riconoscere oggi il momento in cui il silenzio smette di essere pazienza e diventa abbandono di sé. Se abbiamo rimandato una cura, non serve promettere che allora saremmo stati più disciplinati: serve rendere più semplice il prossimo appuntamento, chiedere aiuto, mettere una data nel calendario.",
        "Una lezione reale modifica una scelta futura. Finché resta una frase elegante — avrei dovuto credere di più in me, avrei dovuto ascoltare il mio istinto — produce identità, non comportamento. Ci fa sentire persone che hanno capito, ma non dimostra che abbiamo imparato. Per diventare operativa deve indicare una situazione riconoscibile, un segnale e un'azione possibile.",
        "Il passato può allora diventare un laboratorio. Non per simulare infinite alternative, ma per ricavare una regola abbastanza concreta da essere usata. Quando noto che rimando qualcosa importante aspettando sicurezza totale, chiedo un primo passo reversibile. Quando una relazione mi obbliga a restringermi, ne parlo prima che il disagio diventi risentimento. Quando il corpo manda lo stesso segnale, non aspetto che sia il dolore a decidere."],),
    ("Le persone che eravamo", [
        "È facile provare tenerezza per una fotografia di dieci anni fa e durezza per le decisioni della persona ritratta. Il volto ci sembra giovane; le scelte, invece, ci appaiono inspiegabilmente miopi. Ma quella persona non era una bozza mal riuscita di noi. Aveva desideri autentici, una propria idea di sicurezza e forse responsabilità che oggi ricordiamo male.",
        "Trattare il nostro io passato con rispetto non significa idealizzarlo. Possiamo riconoscere egoismo, evitamento o paura senza ridurre un'intera persona a quelle condotte. Questo atteggiamento è importante perché il modo in cui giudichiamo chi eravamo diventa il modello con cui immaginiamo il giudizio del futuro. Se ogni vecchia versione merita disprezzo, nessuna scelta presente sembrerà mai abbastanza sicura.",
        "Possiamo provare un esercizio: descrivere una decisione passata usando soltanto ciò che conoscevamo in quel momento. Eliminare temporaneamente l'esito e ricostruire opzioni, pressioni, consigli ricevuti, rischi percepiti. Poi aggiungere ciò che oggi sappiamo. Lo spazio fra le due descrizioni è il luogo esatto in cui è nata la nostra conoscenza.",
        "A volte scopriremo che avevamo più margine di quanto ammettiamo e che una responsabilità resta. Altre volte vedremo quanta severità abbiamo applicato a una persona che cercava semplicemente di sopravvivere a un periodo difficile. In entrambi i casi il giudizio diventa più vero perché contiene la storia, non soltanto il risultato."],),
    (None, [
        "Le relazioni occupano una parte enorme dei viaggi nel tempo immaginati. Vorremmo riconoscere prima chi ci amava bene, smettere di chiedere conferme a chi non poteva darle, fare una telefonata prima che diventasse impossibile. Qui il desiderio di correzione incontra il limite più doloroso: non tutte le porte sono ancora aperte.",
        "Quando una persona è raggiungibile, il passato può talvolta ricevere un gesto nel presente. Una scusa precisa non chiede all'altro di cancellare ciò che è successo e non trasforma il pentimento in una richiesta di consolazione. Nomina il comportamento, riconosce l'effetto e lascia libertà sulla risposta. Anche un ringraziamento tardivo può restituire significato a qualcosa che avevamo dato per scontato.",
        "Quando il contatto non è possibile o non sarebbe appropriato, la riparazione può cambiare forma. Possiamo trattare diversamente le persone che oggi occupano un ruolo simile, interrompere un modello familiare, offrire ad altri l'attenzione che allora non abbiamo saputo dare. Non è un pareggio contabile e non sostituisce chi abbiamo ferito. È il modo in cui un rimorso smette di essere soltanto dolore privato e diventa responsabilità.",
        "Esistono anche relazioni che rimpiangiamo perché ricordiamo soprattutto ciò che avevano di luminoso. La distanza attenua le incompatibilità e conserva le scene migliori. Prima di riaprire una porta, serve chiedersi se desideriamo la persona reale o la funzione che svolgeva nella nostra vita. A volte la risposta conduce a un incontro; altre volte invita a costruire nel presente quella qualità con persone nuove."],),
    ("Il costo delle vite alternative", [
        "Ogni vita immaginata possiede un vantaggio ingiusto: non deve sopportare le conseguenze. Nella versione alternativa accettiamo il lavoro giusto, investiamo al momento perfetto, lasciamo una relazione senza solitudine e scegliamo una città senza perderne un'altra. La fantasia interrompe il racconto appena raggiunge la correzione desiderata, prima che compaiano nuovi conflitti.",
        "Per rendere l'immaginazione più onesta possiamo continuare la storia. Se avessimo scelto quella strada, a che cosa avremmo rinunciato? Quali capacità non avremmo sviluppato? Quale prezzo avremmo pagato senza saperlo? Non serve dimostrare che la vita attuale è la migliore possibile. Serve ricordare che anche le alternative avrebbero avuto opacità, perdita e caso.",
        "Questo passaggio aiuta soprattutto quando confrontiamo la nostra vita reale con un'unica linea ideale. Il confronto è truccato: da una parte ci sono anni completi, con errori, malattie, noia e dettagli; dall'altra una selezione di risultati desiderabili. Nessuna vita concreta può vincere contro un montaggio che contiene soltanto ciò che avremmo voluto.",
        "La maturità non consiste nel rinunciare a immaginare alternative. Consiste nell'usarle come strumenti, non come tribunali. Possono rivelare un valore trascurato o una possibilità ancora viva. Quando diventano una dimora permanente, sottraggono attenzione all'unica linea temporale in cui possiamo ancora agire."],),
    (None, [
        "Il denaro e il lavoro rendono la fantasia particolarmente seducente. Conosciamo aziende cresciute, occasioni mancate, competenze diventate preziose. Immaginiamo che, tornando indietro, basterebbe comprare l'asset giusto o scegliere il settore corretto. Ma questa parte del gioco rivela quanto confondiamo conoscenza dell'esito e capacità di sostenere il percorso.",
        "Sapere che un investimento salirà elimina l'incertezza che rendeva difficile investirvi. Sapere che una professione avrà futuro non consegna automaticamente tempo, denaro, salute o sostegno necessari per formarsi. E anche con la previsione esatta resterebbero regole, tasse, rischi operativi e la possibilità che il nostro comportamento cambi proprio perché crediamo di conoscere il risultato.",
        "La lezione utile non è rimproverarci di non aver previsto il mercato. È osservare come prendiamo oggi decisioni sotto incertezza. Abbiamo un fondo di sicurezza? Distinguiamo un rischio calcolato da una scommessa? Investiamo in competenze trasferibili? Conserviamo spazio per cambiare direzione? Queste domande non promettono guadagni retroattivi, ma migliorano la qualità delle scelte che non hanno ancora un finale noto.",
        "Anche nel lavoro il rimpianto può indicare una necessità presente. Se immaginiamo di aver iniziato prima, forse desideriamo smettere di considerarci troppo vecchi. Se vorremmo aver lasciato un ambiente prima, forse stiamo tollerando ancora gli stessi segnali altrove. Il decennio perduto non torna, ma può smettere di essere usato per giustificare un altro rinvio."],),
    ("Un messaggio dal futuro", [
        "Possiamo capovolgere l'esperimento. Invece di tornare indietro di dieci anni, immaginiamo la persona che saremo tra dieci anni mentre guarda questo giorno. Non conosciamo il suo finale e proprio per questo l'esercizio non offre certezze. Offre prospettiva: quali rinvii di oggi potrebbero apparirle costosi? Quali paure comprenderà, ma non vorrà più vedere al comando?",
        "La risposta non deve trasformarsi in una corsa ansiosa a ottimizzare ogni scelta. Il futuro non ci chiede di prevedere tutto. Potrebbe chiederci azioni molto comuni: fare una visita, imparare qualcosa con continuità, passare tempo con una persona, risparmiare una piccola somma, documentare un progetto, dormire abbastanza, dire un no che protegge ciò che conta.",
        "Un buon messaggio dal futuro contiene un passo verificabile e una dose di compassione. Non dice: cambia tutta la tua vita prima che sia tardi. Dice: questa settimana fai la telefonata; entro il mese raccogli le informazioni; oggi dedica mezz'ora a ciò che continui a chiamare importante. Le grandi correzioni retroattive diventano così decisioni presenti abbastanza piccole da poter essere iniziate.",
        "Possiamo anche chiedere che cosa il futuro ci ringrazierebbe di non aver forzato. Alcune decisioni hanno bisogno di tempo, confronto e riposo. La paura di un nuovo rimpianto può spingerci ad agire impulsivamente quanto la paura di sbagliare può immobilizzarci. La saggezza non è velocità: è proporzione tra importanza, reversibilità e informazioni disponibili."],),
    (None, [
        "Per trasformare la domanda in uno strumento, possiamo scegliere tre momenti del passato: uno che vorremmo cambiare, uno che oggi comprendiamo meglio e uno che, pur difficile, non cancelleremmo. Per ciascuno scriviamo che cosa sapevamo allora, che cosa sappiamo ora e quale comportamento presente nasce dalla differenza.",
        "Il primo momento mostra una lezione ancora attiva. Il secondo allena uno sguardo meno punitivo verso noi stessi. Il terzo ricorda che non ogni dolore è un errore da eliminare: alcune esperienze restano indesiderabili, ma hanno prodotto incontri o capacità che non possiamo separare facilmente dalla loro origine.",
        "Poi serve una scelta piccola. Se la lezione riguarda il tempo, proteggiamo un'ora. Se riguarda una relazione, prepariamo una conversazione. Se riguarda una competenza, fissiamo la prima sessione. Se riguarda una colpa, valutiamo una riparazione che rispetti l'altra persona. L'azione deve appartenere a oggi, non a una versione ideale di noi che inizierà quando avrà più coraggio.",
        "Infine possiamo stabilire una data di verifica. Fra un mese chiediamoci se la conoscenza dichiarata ha davvero cambiato qualcosa. Questo evita che la riflessione diventi un rituale consolatorio. Il passato non pretende che viviamo senza nuovi errori; ci chiede soltanto di non continuare a chiamare lezione ciò che non abbiamo mai provato a praticare."],),
    ("Ciò che possiamo ancora salvare", [
        "Non tutto ciò che vorremmo cambiare è recuperabile. Alcune persone non ci sono più, alcune occasioni appartenevano a un'età o a un contesto irripetibile, alcune conseguenze non possono essere annullate. Accettare questo limite non è resa: è la condizione per smettere di negoziare con una porta chiusa e rivolgere energia verso ciò che resta aperto.",
        "Possiamo salvare il significato di un incontro, anche se non possiamo ripeterlo. Possiamo salvare una capacità emersa da un periodo difficile, senza dire che quel dolore fosse necessario. Possiamo salvare la responsabilità, quando una riparazione diretta non è più possibile. Possiamo soprattutto salvare il diritto di cambiare adesso, invece di usare gli anni trascorsi come prova che sia troppo tardi.",
        "La persona di dieci anni fa non riceverà il messaggio che vorremmo inviarle. Ma la persona di oggi può riceverlo per intero. Può ascoltare l'avvertimento, accogliere la tenerezza e trasformare il rimpianto in un criterio. Questo è il vero movimento nel tempo disponibile: una conoscenza nata dopo torna indietro quanto basta per raggiungere il prossimo gesto.",
        "Forse fra dieci anni non desidereremo una vita senza errori. Desidereremo ricordare che, quando alcune cose sono diventate chiare, abbiamo smesso di rimandare. Non avremo controllato gli esiti, ma avremo usato le informazioni che possedevamo con più presenza e onestà."],),
    (None, [
        "Se il tempo tornasse indietro, porteremmo con noi nomi, avvertimenti e decisioni. Ma porteremmo anche una persona formata da ciò che vorremmo impedire. Questa contraddizione rende impossibile una risposta semplice e, nello stesso tempo, rende la domanda preziosa.",
        "Non ci chiede davvero di progettare un passato perfetto. Ci mostra dove avvertiamo ancora una distanza fra ciò che sappiamo e ciò che facciamo. Ogni risposta contiene un valore: vorrei aver protetto di più il mio tempo; vorrei aver amato con meno paura; vorrei aver iniziato prima; vorrei aver chiesto aiuto. Quel valore non appartiene soltanto a ieri.",
        "Possiamo guardare chi eravamo senza superiorità, riconoscere gli errori senza costruire una condanna infinita e usare il rimpianto come informazione. Possiamo riparare ciò che è ancora riparabile, lasciare andare le linee temporali che esistono soltanto nella mente e scegliere un gesto che la nostra versione futura non debba desiderare di compiere al posto nostro.",
        "Il tempo non torna indietro. La comprensione, però, può attraversarlo: raggiunge il presente, cambia una decisione e modifica la storia che non è ancora stata vissuta. La domanda finale non è soltanto che cosa avremmo fatto allora. È che cosa faremo adesso, sapendo finalmente ciò che sappiamo."],),
]

def question_page():
    paras = ''.join(f'<p>{escape(p)}</p>' for p in question_paragraphs[:-1])
    paras += f'<p class="q-pull cm-daily-question">{escape(question_paragraphs[-1])}</p>'
    return f'''<!doctype html><html lang="it"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title>{escape(QUESTION)} | CurioMondo</title><meta name="description" content="Domanda del giorno del 6 settembre 2026: {escape(DECK)}"><meta name="robots" content="index,follow"><meta name="theme-color" content="#f5f9ff"><link rel="canonical" href="https://curiomondo.it{QURL}"><link rel="icon" href="/favicon.ico"><link rel="stylesheet" href="/assets/css/site-base-v210.css"><link rel="stylesheet" href="/assets/css/biblioteca-v1.css?v=294"><link rel="stylesheet" href="/assets/css/daily-question-v273.css"><link rel="stylesheet" href="/assets/css/global-header-v275.css"><script defer src="/assets/js/global-header-v275.js"></script></head><body class="cm-daily-page"><header class="cm-global-header" data-cm-global-header="v275"><nav class="cm-global-header__inner" aria-label="Navigazione della pagina"><a class="cm-global-header__back" href="/" aria-label="Torna alla home di CurioMondo"><span class="cm-global-header__back-icon" aria-hidden="true"><svg viewBox="0 0 24 24"><path d="M19 12H5"></path><path d="m11 18-6-6 6-6"></path></svg></span></a><a class="cm-global-header__brand" href="/" aria-label="CurioMondo, home"><span aria-hidden="true">Curio<span>Mondo</span></span></a><button class="cm-global-header__theme" data-cm-global-theme type="button" aria-label="Attiva modalità scura" aria-pressed="false"><span aria-hidden="true">☾</span></button></nav></header><main class="cm-q-page"><section class="cm-q-hero" aria-labelledby="question-title"><div class="cm-q-topline"><span class="cm-q-badge">Domanda del giorno</span><time class="cm-q-date" datetime="2026-09-06">6 settembre 2026</time></div><p class="cm-q-eyebrow">Uno spazio per fermarsi e pensare.</p><h1 id="question-title">{escape(QUESTION)}</h1><p class="cm-q-meta"><span>3 min di lettura</span><span class="cm-q-dot" aria-hidden="true"></span><span>CurioMondo</span></p></section><article class="q-flow cm-daily-flow" aria-label="Risposta alla Domanda del giorno">{paras}<a class="cm-daily-book-link" href="{BURL}"><span><small>Continua la riflessione</small><strong>Leggi l'eBook collegato</strong></span><span class="cm-daily-book-arrow" aria-hidden="true">→</span></a></article></main><footer class="cm-q-footer" aria-label="Collegamenti informativi"><a href="/pagine/privacy.html">Privacy</a><a href="/pagine/chi-siamo.html">Chi siamo</a></footer><script src="/assets/js/site-common-v210.js" defer></script></body></html>'''

def book_page():
    sections=[]
    total=len(book_pages)
    for i,(heading,paras) in enumerate(book_pages,1):
        attrs=' class="cm-book-page'+(' is-active' if i==1 else '')+'" data-book-page'+('' if i==1 else ' aria-hidden="true"')
        h = f'<h2>{escape(heading)}</h2>' if heading else ''
        body=''.join(f'<p>{escape(p)}</p>' for p in paras)
        title_tag = f'<h1>{escape(BOOK_TITLE)}</h1>' if i == 1 else f'<h2 class="cm-book-title">{escape(BOOK_TITLE)}</h2>'
        sections.append(f'<section{attrs}><span class="cm-book-kicker">eBook CurioMondo · 6 settembre 2026</span>{title_tag}{h}{body}<span class="cm-book-page-number">{i} / {total}</span></section>')
    return f'''<!doctype html><html lang="it"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{escape(BOOK_TITLE)} | eBook CurioMondo</title><meta name="description" content="{escape(BOOK_DECK, quote=True)}"><meta name="robots" content="index,follow"><link rel="canonical" href="https://curiomondo.it{BURL}"><link rel="stylesheet" href="/assets/css/biblioteca-v1.css?v=294"><link rel="stylesheet" href="/assets/css/biblioteca-book-reader-v1.css?v=273"><link rel="stylesheet" href="/assets/css/global-header-v275.css"><script defer src="/assets/js/global-header-v275.js"></script></head><body><header class="cm-global-header" data-cm-global-header="v275"><nav class="cm-global-header__inner" aria-label="Navigazione della pagina"><a class="cm-global-header__back" href="/" aria-label="Torna alla home di CurioMondo"><span class="cm-global-header__back-icon" aria-hidden="true"><svg viewBox="0 0 24 24"><path d="M19 12H5"></path><path d="m11 18-6-6 6-6"></path></svg></span></a><a class="cm-global-header__brand" href="/" aria-label="CurioMondo, home"><span aria-hidden="true">Curio<span>Mondo</span></span></a><button class="cm-global-header__theme" data-cm-global-theme type="button" aria-label="Attiva modalità scura" aria-pressed="false"><span aria-hidden="true">☾</span></button></nav></header><main class="cb-shell"><article class="cm-book-shell"><div class="cm-book-stage">{''.join(sections)}</div><nav class="cm-book-controls" aria-label="Navigazione eBook"><button data-book-prev type="button">← Indietro</button><button data-book-next type="button">Avanti →</button></nav><a class="cm-book-back" href="{QURL}">← Torna alla Domanda del giorno</a></article></main><noscript><style>.cm-book-page{{display:block!important;min-height:0;margin-bottom:20px}}</style></noscript><script defer src="/assets/js/biblioteca-book-reader-v1.js?v=273"></script><footer class="cb-footer"><div class="cb-shell">© 2026 CurioMondo</div></footer></body></html>'''

qp=ROOT/QURL.strip('/')/'index.html'; qp.parent.mkdir(parents=True,exist_ok=True); qp.write_text(question_page(),encoding='utf-8')
bp=ROOT/BURL.strip('/')/'index.html'; bp.parent.mkdir(parents=True,exist_ok=True); bp.write_text(book_page(),encoding='utf-8')

home=ROOT/'index.html'; s=home.read_text(encoding='utf-8').replace(f'/domanda-del-giorno/{OLD}/',QURL).replace('home-bundle-v291.css?v=293','home-bundle-v291.css?v=294'); home.write_text(s,encoding='utf-8')

ap=ROOT/'domanda-del-giorno/index.html'; d=html.fromstring(ap.read_text(encoding='utf-8')); grid=d.xpath('//section[contains(concat(" ",normalize-space(@class)," ")," cb-subgrid ")]')[0]; first=grid.xpath('./a')[0]
card=html.fragment_fromstring(f'<a class="cb-subcard" href="{QURL}"><span class="cb-kicker">6 settembre 2026</span><h2>{escape(QUESTION)}</h2><p>{escape(DECK)}</p><b>Leggi →</b></a>'); first.getparent().replace(first,card); ap.write_text('<!doctype html>'+html.tostring(d,encoding='unicode',method='html'),encoding='utf-8')
cp=ROOT/'biblioteca/vita-relazioni/domande-per-conoscersi/index.html'; d=html.fromstring(cp.read_text(encoding='utf-8')); grid=d.xpath('//section[contains(concat(" ",normalize-space(@class)," ")," cb-subgrid ")]')[0]; first=grid.xpath('./a')[0]
card=html.fragment_fromstring(f'<a class="cb-subcard" href="{BURL}"><span class="cb-kicker">6 settembre 2026 · eBook</span><h2>{escape(BOOK_TITLE)}</h2><p>{escape(BOOK_DECK)}</p><b>Sfoglia →</b></a>'); first.getparent().replace(first,card); cp.write_text('<!doctype html>'+html.tostring(d,encoding='unicode',method='html'),encoding='utf-8')

sp=ROOT/'assets/data/search-index-v210.json'; data=json.loads(sp.read_text(encoding='utf-8')); old_urls={f'/domanda-del-giorno/{OLD}/',f'/biblioteca/vita-relazioni/domande-per-conoscersi/{OLD}/'}; data['items']=[x for x in data['items'] if x.get('url') not in old_urls]
data['items'].insert(0,{'title':BOOK_TITLE,'excerpt':BOOK_DECK,'url':BURL,'section':'Biblioteca · Vita e relazioni'})
data['items'].insert(0,{'title':QUESTION,'excerpt':DECK,'url':QURL,'section':'Domanda del giorno'}); data['version']=VERSION; sp.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
for rel in ('assets/data/home-feed-v210.json','assets/data/editorial-images-v210.json'):
    p=ROOT/rel; data=json.loads(p.read_text(encoding='utf-8')); data['version']=VERSION; p.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')

sm=ROOT/'sitemap.xml'; tree=etree.parse(str(sm)); ns={'s':'http://www.sitemaps.org/schemas/sitemap/0.9'}
repl={f'https://curiomondo.it/domanda-del-giorno/{OLD}/':f'https://curiomondo.it{QURL}',f'https://curiomondo.it/biblioteca/vita-relazioni/domande-per-conoscersi/{OLD}/':f'https://curiomondo.it{BURL}'}
for loc in tree.xpath('//s:loc',namespaces=ns):
    if loc.text in repl: loc.text=repl[loc.text]
tree.write(str(sm),encoding='utf-8',xml_declaration=True,pretty_print=True)

np=ROOT/'notizie/laquila-monumenti-lego-maurizio-lampis-collemaggio-6-settembre-2026.html'; s=np.read_text(encoding='utf-8').replace(f'/domanda-del-giorno/{OLD}/',QURL).replace('Chi siamo quando cadono le maschere utili?','Cosa faremmo tornando indietro di dieci anni?'); np.write_text(s,encoding='utf-8')

mp=ROOT/'curiomondo-site-manifest.json'; m=json.loads(mp.read_text(encoding='utf-8')); m['site']['current_site_version']=VERSION; m['site']['site_version']=VERSION; m['daily_state']['last_question_date']='2026-09-06'; mp.write_text(json.dumps(m,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
print(json.dumps({'status':'ok','version':VERSION,'question':QURL,'ebook':BURL,'question_chars':sum(len(x) for x in question_paragraphs),'book_chars':sum(len(p) for _,ps in book_pages for p in ps)},ensure_ascii=False))
