#!/usr/bin/env python3
from pathlib import Path
from html import escape
import hashlib, json, runpy

ROOT=Path(__file__).resolve().parents[1]
VERSION=311
CAPTION="Illustrazione editoriale CurioMondo generata con IA per rappresentare questa notizia; non è una fotografia documentaria."

ARTICLES=[
{
"slug":"italia-banche-contributo-manovra-2027-proposta-lega-8-settembre-2026","title":"Manovra 2027, la Lega propone fino a 3 miliardi dalle banche","excerpt":"La proposta prevede un contributo del 5% sugli utili bancari per finanziare famiglie, imprese e sicurezza. Forza Italia preferisce anticipi fiscali concordati.","published":"2026-09-09T07:05:00+02:00","category":"Italia / Politica / Economia","place":"Roma","key":"italia-banche-manovra-2027-ai-v311","alt":"Edifici istituzionali italiani e settore bancario, scena editoriale contestuale fotorealistica generata con IA","points":[("2–3 mld €","la stima indicata dalla Lega"),("5%","il contributo proposto sugli utili"),("ottobre","il mese atteso per la manovra")],
"body":[
"La Lega propone che le banche contribuiscano con una somma compresa fra 2 e 3 miliardi di euro alla manovra italiana per il 2027. L’ipotesi, presentata l’8 settembre durante un incontro sulle priorità della prossima legge di bilancio, prevede un prelievo pari al 5% degli utili del settore. Le risorse, secondo il partito, dovrebbero sostenere famiglie e imprese e finanziare misure per la sicurezza. Non si tratta ancora di una norma approvata: aliquota, base imponibile e destinazione dovrebbero entrare in un provvedimento del governo e superare l’esame parlamentare.",
"Il ministro dell’Economia Giancarlo Giorgetti ha collegato la richiesta ai profitti elevati delle banche e alla debole concorrenza percepita in alcuni servizi. La sua posizione politica non equivale però a una quantificazione tecnica già validata dal ministero. La stima di 2–3 miliardi proviene dalla proposta della Lega e andrà confrontata con il gettito effettivamente ottenibile, gli effetti sui bilanci degli istituti e la formulazione definitiva della misura.",
"Nella maggioranza non c’è ancora una linea unica. Forza Italia, attraverso Antonio Tajani, ha indicato come alternativa un accordo per anticipare versamenti fiscali, sul modello di operazioni già utilizzate con banche e assicurazioni. Le due strade hanno conseguenze diverse: un’imposta aggiuntiva aumenta il prelievo dovuto; un anticipo fiscale sposta nel tempo entrate che lo Stato avrebbe comunque incassato e può quindi migliorare il saldo di un anno riducendo margini futuri.",
"Per capire la discussione bisogna distinguere utili contabili, imponibile fiscale e gettito. Il profitto pubblicato da una banca non coincide automaticamente con la somma sulla quale si calcola una tassa: entrano in gioco rettifiche, deduzioni, perdite pregresse e perimetro delle attività interessate. Anche una percentuale apparentemente semplice può produrre risultati diversi a seconda della definizione scelta dalla legge e del periodo di riferimento.",
"Il governo dispone già di entrate programmate dal settore finanziario. Reuters ricorda che misure esistenti rivolte a banche e assicurazioni dovrebbero assicurare circa 12 miliardi fino al 2028. La nuova proposta si aggiungerebbe a quel quadro e perciò dovrà essere valutata insieme agli impegni già iscritti nei conti pubblici, evitando di contare due volte la stessa capacità contributiva o anticipi che riducono entrate successive.",
"Un altro punto riguarda gli effetti indiretti. Gli istituti potrebbero assorbire il costo riducendo i margini, ma potrebbero anche rivedere commissioni, remunerazione dei depositi, credito o dividendi. Non esiste un trasferimento automatico e identico per tutte le banche: dipende dalla concorrenza, dalla solidità patrimoniale e dalla struttura della misura. Per questo il dibattito non può essere letto soltanto come confronto fra Stato e azionisti; interessa anche correntisti e imprese che cercano finanziamenti.",
"La proposta arriva mentre il governo prepara l’ultima manovra completa prima delle elezioni politiche previste nel 2027. Le priorità annunciate comprendono riduzioni fiscali e nuove spese, ma il margine dipende dalle previsioni di crescita, dal costo del debito e dalle regole europee. Una fonte una tantum può finanziare interventi temporanei più facilmente di una spesa permanente: se una misura produce costi ogni anno, servono coperture che continuino nel tempo.",
"I prossimi passaggi verificabili saranno la Nota di aggiornamento dei conti pubblici, le decisioni del Consiglio dei ministri e il testo della legge di bilancio. Solo allora sarà possibile sapere se il contributo resterà al 5%, quali banche riguarderà, come sarà calcolato e a quali capitoli verranno destinate le risorse. Fino a quel momento CurioMondo tratta i 3 miliardi come obiettivo politico, non come entrata già acquisita."
],"sources":[["https://www.reuters.com/business/finance/italys-league-says-banks-should-contribute-up-3-bln-state-budget-2027-2026-09-08/","Reuters — 8 settembre 2026 — proposta, stima e posizioni nella maggioranza"],["https://www.mef.gov.it/","Ministero dell’Economia e delle Finanze — documenti ufficiali sui conti pubblici e sulla manovra"],["https://www.bancaditalia.it/","Banca d’Italia — dati e analisi sul sistema bancario italiano"]]
},
{
"slug":"iran-attacchi-base-usa-giordania-navi-hormuz-petrolio-9-settembre-2026","title":"Iran-USA, nuova escalation tra Giordania e Stretto di Hormuz","excerpt":"Teheran ha lanciato missili contro una base statunitense in Giordania e rivendicato attacchi a navi vicino a Hormuz. Le autorità giordane e USA non segnalano vittime.","published":"2026-09-09T06:55:00+02:00","category":"Mondo / Medio Oriente / Economia","place":"Stretto di Hormuz","key":"iran-usa-hormuz-petrolio-ai-v311","alt":"Petroliere nello Stretto di Hormuz sorvegliate a distanza da unità navali, scena editoriale fotorealistica generata con IA","points":[("10 navi","gli obiettivi rivendicati dall’Iran"),("0 vittime","secondo Giordania e Stati Uniti"),("~100 $","la soglia avvicinata dal Brent")],
"body":[
"L’Iran ha intensificato il confronto con gli Stati Uniti lanciando missili contro la base militare di Al Azraq, in Giordania, e rivendicando attacchi contro dieci navi nell’area dello Stretto di Hormuz. Due delle unità indicate sarebbero statunitensi. Le autorità giordane e americane hanno riferito che gran parte dei missili è stata intercettata e che non risultano vittime. Le valutazioni sui danni restano divergenti: Teheran parla di effetti rilevanti, mentre le comunicazioni di Giordania e Stati Uniti ridimensionano l’impatto.",
"Gli attacchi seguono la distruzione, da parte statunitense, di cinque petroliere iraniane. Washington ha presentato l’operazione come risposta alle azioni iraniane contro il traffico marittimo e una nave militare americana. In un conflitto in corso, le rivendicazioni delle parti non costituiscono da sole una verifica indipendente: numero degli obiettivi colpiti, danni e responsabilità devono essere attribuiti alla fonte finché immagini, registri navali o riscontri di terzi non li confermano.",
"Lo Stretto di Hormuz è decisivo perché collega il Golfo Persico al Golfo di Oman e all’Oceano Indiano. È un passaggio stretto attraverso il quale transita una parte molto rilevante del petrolio e del gas naturale liquefatto esportati dai produttori del Golfo. Il rischio economico non dipende soltanto da una chiusura totale: ritardi, premi assicurativi più elevati, deviazioni, minore disponibilità di equipaggi e timori per le infrastrutture possono aumentare i costi anche quando le navi continuano a passare.",
"Il Brent si è avvicinato ai 100 dollari al barile dopo quattro sedute di rialzo, mentre il greggio statunitense ha superato i 94 dollari. Questi prezzi non misurano soltanto la quantità di petrolio fisicamente mancante; incorporano anche un premio per il rischio che le forniture future vengano interrotte. Se la tensione diminuisce senza danni duraturi agli impianti e alle rotte, una parte del rialzo può rientrare. Se gli attacchi si estendono, la pressione può invece trasferirsi a carburanti, trasporti e inflazione.",
"L’escalation coinvolge anche alleati regionali degli Stati Uniti. Forze Houthi sostenute dall’Iran hanno colpito città e infrastrutture saudite, aumentando il timore che il confronto si allarghi oltre il territorio iraniano. La cooperazione fra gruppi armati non implica però che ogni singola operazione sia diretta in tempo reale da Teheran: catene di comando, assistenza tecnica e autonomia locale vanno distinte quando le prove disponibili non consentono conclusioni più precise.",
"Per i Paesi importatori, Italia compresa, il primo effetto passa dai prezzi internazionali e dal cambio euro-dollaro. Il costo alla pompa non replica in modo immediato e proporzionale il movimento del Brent: comprende raffinazione, logistica, biocarburanti, accise, IVA e politiche commerciali. Tuttavia una fase prolungata sopra i livelli precedenti può raggiungere gradualmente bollette, trasporto merci e prodotti che utilizzano molta energia.",
"Le alternative logistiche allo Stretto esistono ma hanno capacità limitata rispetto ai flussi complessivi del Golfo. Oleodotti verso il Mar Rosso o il Golfo di Oman possono ridurre una parte dell’esposizione, senza sostituire integralmente il traffico marittimo. Per questo mercati e governi osservano non solo gli attacchi, ma anche la continuità dei terminali, la disponibilità di scorte e le decisioni dei grandi produttori.",
"I dati da seguire nelle prossime ore sono gli avvisi ufficiali alla navigazione, le conferme sulle navi danneggiate, l’eventuale variazione dei transiti e le comunicazioni militari verificabili. Anche il prezzo del petrolio va letto insieme ai volumi scambiati e alla durata del movimento. Un picco intraday segnala paura; una riduzione persistente dell’offerta segnala invece un problema materiale per l’economia mondiale."
],"sources":[["https://www.reuters.com/world/middle-east/iran-attacks-us-base-jordan-ships-near-hormuz-after-tankers-sunk-2026-09-09/","Reuters — 9 settembre 2026 — attacchi, risposte ufficiali e quadro militare"],["https://www.reuters.com/business/energy/oil-jumps-1-early-trade-after-iran-launches-missiles-jordan-2026-09-09/","Reuters — 9 settembre 2026 — andamento del petrolio e rischio per le forniture"],["https://apnews.com/article/41b104b908daeb58ad1d714224f8f570","Associated Press — 9 settembre 2026 — coordinamento regionale e attacchi Houthi"],["https://www.eia.gov/international/analysis/special-topics/World_Oil_Transit_Chokepoints","U.S. EIA — funzione dello Stretto di Hormuz nei flussi energetici"]]
}
]

ns={'__file__':str(ROOT/'tools/build_v310.py')}; src=(ROOT/'tools/build_v310.py').read_text(encoding='utf-8'); prefix=src.split('def article(a):',1)[0]; exec(prefix,ns)
tail='def article(a):'+src.split('def article(a):',1)[1].split("registry_path=",1)[0]; exec(tail,ns)
article=ns['article']
registry_path=ROOT/'assets/data/editorial-images-v210.json'; registry=json.loads(registry_path.read_text(encoding='utf-8'))
for a in ARTICLES:
 (ROOT/'notizie'/f"{a['slug']}.html").write_text(article(a).replace('8 settembre 2026','9 settembre 2026').replace('?v=310','?v=311'),encoding='utf-8')
 variants=[]
 for w in (480,800,1200):
  f=ROOT/'assets/images/editorial-auto'/f"{a['key']}-{w}.webp"; variants.append({'w':w,'src':f'/assets/images/editorial-auto/{f.name}','sha256':hashlib.sha256(f.read_bytes()).hexdigest(),'bytes':f.stat().st_size})
 registry['items'].insert(0,{'key':a['key'],'article':f"/notizie/{a['slug']}.html",'aiGenerated':True,'sensitiveContext':False,'documentaryPhoto':False,'variants':variants,'alt':a['alt'],'disclosure':CAPTION,'portraitOnly':False,'portraitFormat':'contextual-editorial-scene','reenactedEvent':False})
registry['version']=VERSION; registry_path.write_text(json.dumps(registry,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
runpy.run_path(str(ROOT/'tools/finalize_articles_20260906.py'),run_name='__main__')
for rel in ('assets/data/home-feed-v210.json','assets/data/search-index-v210.json','assets/data/editorial-images-v210.json'):
 p=ROOT/rel; d=json.loads(p.read_text(encoding='utf-8')); d['version']=VERSION; p.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
runpy.run_path(str(ROOT/'tools/generate_category_pages.py'),run_name='__main__')
mp=ROOT/'curiomondo-site-manifest.json'; m=json.loads(mp.read_text(encoding='utf-8')); m['site']['current_site_version']=VERSION; m['site']['site_version']=VERSION; mp.write_text(json.dumps(m,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
print(json.dumps({'status':'ok','version':VERSION,'articles':[a['slug'] for a in ARTICLES]},ensure_ascii=False))
